GovWifi/govwifi-admin

app/controllers/monitoring_controller.rb, config/routes.rb, spec/monitoring/healthcheck_spec.rb, spec/rails_helper.rb
AWS target groups use the healthchecking route to determine whether the app is ready for accepting incoming requests or not.  Once the app is ready, it will be registered with the load balancer to start receiving requests.
At the moment this healthcheck is very simple, as our app doesn't have any complex behaviour.
=> Add healthchecking route for ECS autoscaling

Jenkinsfile
This was hangover when copying from the other Jenkinsfiles,
but isn't actually needed as Jenkins multibranch pipeline will
do this automatically for us.
=> Remove the call to setBuildStatus

config/secrets.yml
Currently getting this error from the staging environment:
```
DEPRECATION WARNING: You didn't set `secret_key_base`.
Read the upgrade documentation to learn more about this new config option.
```
=> Add the secret key base to the staging environment

Gemfile, Gemfile.lock, spec/features/basic_feature_spec.rb
#17 is pretty heavy, so we're trying to slice stuff off.
This PR adds the most basic of feature specs, powered by Capybara to drive page interaction.
=> Add basic feature spec

Dockerfile
The Alpine docker image has a smaller stack size which results in
SystemStackError from being raised in situations where you have a
deep call stack.
This error was being raised in this repository when running
Capybara tests involving rack-test and SASS compilation.
Switching to Debian should fix this as it doesn't have this stack
size problem.
See more information on this issue here:
https://github.com/docker-library/ruby/issues/196
When switching to Debian, we're pulling in the yarn binary via
their apt repository as default Debian doesn't provide an npm
from which we could use `npm install -g yarn`.
An additional problem is that the default Debian install doesn't
support apt repositories on HTTPS urls.  We first have to install
the `apt-transport-https` before being able to use the yarn …
=> Replace Alpine for Debian in our Dockerfile

Jenkinsfile
This should remove any running docker images which helps keep Jenkins
in a healthy state.  This will run even if the build fails for whatever
reason.
=> Add post build cleanup step to the Jenkinsfile

Jenkinsfile
We call a scheduled task which will do the migrations for us in Jenkins.
Since we are running the migrations before making the task live, we will
need to keep the migrations non destructive.
We decided that this is ok, since we do this anyway for a blue green
setup.
We will look into making the new task live as soon as we have pushed a
new image into the ECR repository later on.
=> Allow Jenkins to run migrations

Makefile, docker-compose.development.yml
Mounting the repository as a volume allows any changes to
manifest themselves inside of docker immediately, which
creates faster feedback loops when running `make serve`.
Now that we are mounting the app as a volume we may have
a stray pid file left over from a previous `make serve`
execution.  `rm -f` before performing `make serve` will
prevent this from being an issue.
We are unable to do this on Jenkins because the Jenkins
image is already running inside of Docker.  To the
Jenkins node the parent directory is already a virtual
filesystem path.  Therefore if this was done on Jenkins,
the docker deamon would fail to find the parent path
(as it is passed in as a virtual path which the daemon
wouldn't be able to see).
If/when Jenkins moves to not being run inside of docker
we can remove …
=> Mount the repository directory in development

app/controllers/users/registrations_controller.rb, app/models/user.rb, app/views/users/confirmations/pending.html.erb, lib/use_cases/administrator/check_if_whitelisted_email.rb, spec/factories/users.rb, spec/features/logging_in_after_signing_up_spec.rb, spec/features/sign_up_as_an_organisation_spec.rb, spec/features/support/sign_up_helpers.rb, spec/models/user_spec.rb, spec/use_cases/administrator/check_if_whitelisted_email_spec.rb
This is branched off #17, so won't be merged until after it.
This PR implements basic whitelisting on sign up emails - .gov.uk and subdomains are allowed, everyone else isn't.
This was the quickest implementation, there are patterns that beat the very simple string test - not sure how much time it's worth spending on a bulletproof regex (should we lift the one we have from PHP? seems horrible.)
=> Verify email is in gov domain

Dockerfile, lib/use_cases/administrator/check_if_whitelisted_email.rb, spec/features/sign_up_as_an_organisation_spec.rb, spec/models/user_spec.rb, spec/spec_helper.rb, spec/use_cases/administrator/check_if_whitelisted_email_spec.rb
We've got a regex that the `build` repo pushes as an env-var to all environments - this uses that regex to validate emails (as the other systems do).
Long-term I'd like to see the approved domains expressed in a way that is less... buried. 
Since there's a lot of cases covered, it's a little tricky to reproduce with just a few rows in a table somewhere, but we could at least do approved domains _from now on_ a little more nicely to start.
=> Use regex from env-var to validate emails

config/environments/staging.rb
We need logging enabled for staging.
Copy over the rest of the production configuration to staging so that we
have the same environment to test in
=> Add a configuration file for the staging environment

app/mailers/authentication_mailer.rb, config/gov_notify.yml, config/initializers/gov_notify.rb, lib/use_cases/administrator/send_confirmation_email.rb, spec/support/confirmation_use_case_spy.rb, spec/use_cases/send_confirmation_email_spec.rb
GovNotify has two versions: production (live) and staging. They both
define different sets of templates and API keys. We must use a correct
app for specific env.
=> Use email templates per environment

spec/support/notifications_service.rb
Without this require the spec_helper would not load a spec
that actually has it and thus fail. Requiring it explicitly here
fixes the issue.
=> Allow to run single tests

app/controllers/users/confirmations_controller.rb, config/gov_notify.yml, lib/use_cases/administrator/notify_support_of_new_user.rb, spec/features/sign_up_as_an_organisation_spec.rb, spec/use_cases/administrator/notify_support_of_new_user_spec.rb, spec/use_cases/administrator/send_confirmation_email_spec.rb
Support (for today's date its Steve) wants to be CC'ed when
new user are registered so he can chase org admins to sign up
for MoU.
=> Add ability to send emails with notifications of new users

app/controllers/ips_controller.rb, app/views/ips/new.html.erb, spec/features/add_an_ip_address_spec.rb
Improve IP form to be safer for users:
- Add Errors:
- Add Guidance
=> Add guidance to new IP form

app/views/layouts/application.html.erb
We are not actually "Alpha" or "Beta" as the GovWifi service is not new. We are simply creating a new interface and updating content.
=> Remove Alpha banner

app/controllers/ips_controller.rb, spec/features/view_ip_addresses_spec.rb
Ensure that you cannot navigate to other IP addresses by modifying the
id in the URL
=> Disallow viewing other IP Adresses

config/gov_notify.yml
Since we are doing a lot of testing here, it will get pretty noisy in
Zendesk
=> Don't email support for staging signups

config/gov_notify.yml
When someone signs up we want to know about it on production.
This was breaking in development with an invalid email error, since we
stubbed out Notify
=> Fix bug in development with sending emails

app/controllers/users/confirmations_controller.rb, app/models/user.rb, app/views/users/confirmations/show.html.erb, db/migrate/20180822150340_add_name_to_users.rb, db/schema.rb, spec/factories/users.rb, spec/features/asking_users_to_sign_in_spec.rb, spec/features/logging_in_after_signing_up_spec.rb, spec/features/resend_confirmation_instructions_spec.rb, spec/features/sign_up_as_an_organisation_spec.rb, spec/features/support/sign_up_helpers.rb, spec/models/user_spec.rb, spec/spec_helper.rb
We want to store additional details for users once they follow the
confirmation link from their inbox.
Rename some of the set_password methods to be more general
=> Ask user for name on password confirmation page

config/application.rb, spec/features/resend_confirmation_instructions_spec.rb, spec/features/reset_password_spec.rb
Confirmation and reset password links were using "http" only, which meant users could not follow them in many browsers.
This forces "HTTPS" on the entire application, except for the healthcheck path.
=> Force SSL except for Healthcheck path

app/views/users/confirmations/pending.html.erb
Some improvements to copy, large clear layout.
Notably, this PR doesn't include the "actual" email address, or the "resend confirmation email", as the Devise resource is not in context at this path. Time is short, so that comes later.
=> Improve UX of "confirmation email sent" page

app/views/ips/index.html.erb
This PR introduces three tabs - home, locations and team - that
will hopefully help to make it clearer to a user what's happening once
they've logged in.
I think this version of the content is too dense to guide a user, and
I'm not happy with a lot of the language, we can refine it from here.
"Home" part of this: 
"Locations" takes what the page used to look like (which will soon get updated as well):
Team isn't available yet:
Notably tabbed view isn't something GOV.UK are confident in yet, but things can be moved around pretty easily.
=> Tabify logged-in landing, add placeholder content

config/gov_notify.yml
Notify (the GOV service) needs a "real" email address, or it blows up.
=> Make notify valid (if fake) email address

app/controllers/users/invitations_controller.rb, app/views/users/invitations/new.html.erb, config/routes.rb, db/seeds.rb, spec/factories/users.rb, spec/features/team/accept_an_invitation_and_sign_up_spec.rb, spec/features/team/invite_a_team_member_spec.rb
Assigns the current user's organisation to the invited user.
I realise I am testing model attributes from a feature spec, however we currently have no indication of the user's organisation in the view, so it kind of has to be here for now. (Unless we want to make some controller specs that is 🤢 )
=> Assign Invited User to Organisation

app/models/ip.rb, app/views/ips/_activation_notice.html.erb, app/views/ips/index.html.erb, app/views/ips/new.html.erb, spec/features/add_an_ip_address_spec.rb, spec/features/support/activation_notice.rb, spec/models/ip_spec.rb
This commit changes various markup and messages to better illustrate to users the purpose and functionality of the now "Add Locations" page. it also adds a functioning 'back' link.
It also modifies the feature specs that were checking against these pages.
Notably this changes the language from "adding IPs" to "adding locations", which I'm not sure if correct. Feels like we have divergent language around this concept.
=> Improve UX of add IP page

app/mailers/authentication_mailer.rb, spec/features/reset_password_spec.rb
Unconfirmed users don't have names set yet so
going through reset password flow will yield
errors about missing name.
To fix that, we re-send confirmation email if you
are unconfirmed user who wants to reset your password.
=> Handle unconfirmed users resetting passwords

Gemfile, Gemfile.lock, lib/use_cases/administrator/health_checks/calculate_health.rb, spec/use_cases/administrator/health_check/calculate_health_spec.rb
This introduces the Aws SDK for Route53.
The process of establishing whether an IP is healthy requires 2 steps:
- Get healthcheck Id for that IP, excluding the latency health check
- Do another API request to establish whether the health check is
healthy based on the 6 health checkers associated with it
This doesn't display it on the view yet.
There is a failing feature spec for this that isn't a part of this PR.
This creates the use cases and wraps tests around them with fake AWS
gateways.
=> Route53 Healthchecks

app/controllers/health_checks_controller.rb, app/views/health_checks/index.html.erb, config/environments/development.rb, config/environments/test.rb, config/routes.rb, lib/gateways/route53.rb, lib/use_cases/administrator/health_checks/calculate_health.rb, spec/features/health_checks/view_health_checks_spec.rb, spec/gateways/route53_spec.rb, spec/use_cases/administrator/health_check/calculate_health_spec.rb
This is unstyled, but uses the use cases created in the previous pr.
We won't be displaying actual health checks in development, so this is
stubbed out in config/environments/development.rb
=> Display health checks to the user

config/environments/development.rb, lib/use_cases/administrator/health_checks/calculate_health.rb, spec/use_cases/administrator/health_check/calculate_health_spec.rb
There is no need to filter out latency health checks as they are
actually just an attribute on a regular health check.
This was missed due to changes between staging and production route53
health checks setup.
=> Don't filter out latency health checks

app/views/status/_result.html.erb
For accessibility we can't rely on just the colour of the status icon.
Print the status next to the icon as well.
=> Display "healthy" or "unhealthy" along with the icon

app/controllers/users/confirmations_controller.rb, app/models/user.rb, app/views/users/confirmations/show.html.erb, app/views/users/passwords/edit.html.erb, spec/factories/users.rb, spec/features/sign_up_as_an_organisation_spec.rb, spec/models/user_spec.rb
Validates the password confirmation correctly at the model. Wasn't working correctly before so we were forcing the controllers to check the two fields matched.
=> Validate password_confirmation at the model

lib/use_cases/administrator/health_checks/calculate_health.rb, spec/features/status/view_status_spec.rb, spec/use_cases/administrator/health_check/calculate_health_spec.rb
Improve wording on the GovWifi status page.
=> Reword healthy/unhealthy to operational/offline

app/controllers/ips_controller.rb, app/models/user.rb, app/views/ips/_activation_notice.html.erb, app/views/ips/_radius_details.html.erb, app/views/ips/_table.html.erb, app/views/ips/index.html.erb, app/views/ips/new.html.erb, app/views/team_members/_table.html.erb, app/views/users/confirmations/new.html.erb, spec/features/add_an_ip_address_spec.rb, spec/features/team/resend_invitation_spec.rb, spec/features/view_ip_addresses_spec.rb
This PR separates out the "add an IP" and "configure your access points" tasks a little better. Planning to move them to separate screens in the near-future, based on Anna/Constance's feedback.
Adds a warning about IPs not being immediately available to the messaging feedback and some other scattered bits of copy.
=> Improve layout/messaging of IP Addresses page (+ other minor copy/layout tweaks across app)

app/views/users/invitations/new.html.erb
Makes this consistent with our other form-style pages (and GOV in general)
=> Give users a way to escape invitations flow

app/views/ips/index.html.erb
This was hard to read before, now it's better:
=> Add section markers on dense infrastructure page

Jenkinsfile
Right now Jenkins waits for 5 minutes before failing the build - this keeps gumming up the build pipeline when there's lots of builds going on. 
If I want to push something to staging or production I'm there waiting already, or I can just re-trigger a build (which only takes about a minute anyway).
As a quick fix, reduce the time before timing out to 1 minute instead.
=> Reduce 'deploy to X?' wait time on Jenkins

app/controllers/ips_controller.rb, app/models/ip.rb, app/models/location.rb, app/models/organisation.rb, app/views/ips/_radius_details.html.erb, db/migrate/20180907133507_add_locations.rb, db/migrate/20180907134753_add_location_id_to_ips.rb, db/migrate/20180907144200_remove_radius_secret_key_from_organisations.rb, db/schema.rb, spec/factories/locations.rb, spec/features/view_ip_addresses_spec.rb, spec/models/ip_spec.rb, spec/models/location_spec.rb, spec/models/organisation_spec.rb
This is a spike to add locations to the admin portal. I have approached this from the angle of trying to get the schema ready to accept the old system data, without changing the frontend user flow. Its the smallest slice I could think of. 
Mainly this PR is about the schema and association changes.
But theres some obvious hacks that I will have to remove in the next iteration:
- For a new user, I'm creating a location when they create their organisation.
- Every IP they add is added to this location.
- I've done this so everything works until we modify the frontend flow.
OLD SYSTEM DATA: We need to import the existing data, which has locations, to this DB. So I've looked at the following schema to bring things over. Some names will need to be changed. I think its better to have nice names …
=> WIP: Add locations to db

Jenkinsfile
Turns out this timeout is from the beginning of the build step,
so as this step takes about 40 seconds, you have to click 'proceed'
in a 20-second window.
Given the UI update speed, this is a little tight - 2 minutes should
do the trick.
=> Lengthen timeout for Jenkins deploy step

config/environments/production.rb, config/environments/staging.rb
In test and development we stub AWS responses.
We recently changed this configuration to be S3 and Route53 specific.
This was missed for staging and production
=> Empty AWS configuration overrides for staging and production

db/migrate/20180912133317_add_service_email_to_organisations.rb, db/schema.rb
T "notifications" column on the old database needs to be transferred to the new admin db. This column holds the email for service for the organisation. 
I've gone with `service_email` because I thought `organisation.service_email` made a lot of sense.
This doesn't exist as a feature in the front end.
I don't think this will require any changes to the other apps / APIs.
https://trello.com/c/8xyIhzal/32-1-add-notifications-to-new-organisations-table
=> Add service_email column to Organisations table

db/migrate/20180912135253_add_phone_number_to_users.rb, db/schema.rb
The `mobile` column on the old database needs to exist in the new admin DB. 
Is there a better name than `user.mobile`?
I don't believe this change will ripple anywhere else, eg: allowed-sites-api.
https://trello.com/c/rOskvxcm/33-1-add-mobile-to-new-users-table
=> Add mobile column to Users table

lib/tasks/repair_migrated_data.rake
We're migrating data from the 'other' GovWifi database so it can be used in the admin app - users, organisations, locations and IPs.
When we bring them across, there's a few bits to repair - we've done these in Rake tasks so they're louder about the way they break, easier to work with, etc.
=> Add rake task to support data migration

app/models/user.rb, spec/models/user_spec.rb
We want to make sure users have an email that's from .gov (or other 
whitelisted) domains, so that not anyone can sign up for GovWifi.
After the fact, however, users might hand over control to an external 
provider (e.g. BT), but those organisations aren't on the whitelist 
(and can't be in some cases - we can't let everyone from BT sign up!)
We have data covering our existing organisations that defies our 
whitelist already, so this is necessary if we want to bring it across 
and get all organisations using admin.
This PR changes the validation on Users to be only on creation.
=> Only validate emails for new users

app/controllers/home_controller.rb, app/views/application/_subnavigation.html.erb, app/views/home/index.html.erb, app/views/layouts/application.html.erb, spec/features/asking_users_to_sign_in_spec.rb, spec/features/logging_in_after_signing_up_spec.rb, spec/features/reset_password_spec.rb, spec/features/sign_up_as_an_organisation_spec.rb, spec/features/support/sign_up_helpers.rb, spec/features/team/accept_an_invitation_and_sign_up_spec.rb, spec/features/team/resend_invitation_spec.rb
This PR moves the subnav into a partial and uses it from the application layout, so that it's available throughout the app when logged in.
It also changes the top-right nav to be closer to the other GDS services:
Formatting for the subnav is poor - this is being addressed in another change.
=> Improve navbar, show subnav bar on all pages

app/controllers/users/confirmations_controller.rb, app/models/user.rb, spec/features/resend_confirmation_instructions_spec.rb
Resetting the token doesn't seem to be necessary - looks like we were digesting the token before comparing, which might have confused things.
Still not super-clear on how this Devise functionality is working, but we removed some code and got the test passing, so it's a step in the right direction.
=> Fix resend confirmation bug

app/controllers/help_controller.rb, app/views/help/index.html.erb, app/views/home/index.html.erb, app/views/team_members/index.html.erb, config/site.yml
Broken links:
- help link on teams page
Incorrect Links:
- End user troubleshooting
- Admin troubleshooting
Also removed the links out of controllers. The `SITE_CONFIG` is already in memory, so I don't see the point in assigning an in memory string to an instance variable. I see controllers more for interacting with models. Happy with views accessing this in memory config directly.
=> Update support and troubleshooting links

app/views/layouts/_flash_notices.html.erb, app/views/users/sessions/new.html.erb
Turns out the problem was with the `sessions#new` view managing its own flash messages, rather than using the partial.
There's still two types of error reporting in the app - one partial for validation errors on models, and one for flash messages - but I think this is a step in the right direction.
=> Use partial for all flash notices

lib/gateways/s3.rb, lib/use_cases/performance_platform/publish_locations_ips.rb, spec/gateways/s3_spec.rb, spec/use_cases/performance_platform/publish_locations_ips_spec.rb
The content we will upload to S3 will not always be JSON.
Ensure data is prepared before handed over to this gateway.
=> Remove casting to JSON from the S3 Gateway

Dockerfile, bin/yarn
**Why:** We were seeing a flaky bug introduced by a new version of yarn released
* Yarn 1.9.4
* Nodejs 8~
=> Lock yarn and nodejs versions

app/controllers/home_controller.rb, lib/use_cases/organisation/view_radius_ip_addresses.rb, spec/use_cases/organisation/view_radius_ip_addresses_spec.rb
For example, for our test organisation, they're now not in 'natural' order:
(We checked a few more and they're in different orders too)
=> Order radius IPs based on organisation ID

app/controllers/ips_controller.rb
Some organisations have a lot of locations, and finding the correct
location becomes difficult.  By ordering them alphabetically, it's
easier to find.
=> Order locations by address

app/controllers/logs_controller.rb, spec/features/logging/view_auth_requests_for_a_username_spec.rb
Before: When searching the authorisation requests the logs showed ALL of the IP's, even if  that organisation did not own it.
After: When searching the authorisation request logs it now only displays the results for IP's that the organisation owns.
=> Filter authorisation requests

app/models/read_replica_base.rb, config/database.yml, config/initializers/read_replica_database.rb
Keep this configuration together which will make it easier to find down
the line. Can also access this constant easily if we were to manually
establish another database connection, which is going to be required by
database cleaner down the line.
=> Read replica config in database yaml file

app/assets/stylesheets/components/health_checks.scss, app/views/status/_result.html.erb
Ticket was just to add colouring to make it clearer, but think this is clearer in table (not list) styling:
=> Put health checks in table and colorize

lib/use_cases/administrator/validate_log_search_query.rb, spec/use_cases/administrator/validate_log_search_query_spec.rb
This will be used to ensure that search queries are valid for viewing
logs.
=> Extract log search query validator

app/views/logs/index.html.erb, spec/features/logging/view_auth_requests_for_a_username_spec.rb
@logs can be nil if the search has not happened yet.
Check for this and make the error message more general since we are
searching for usernames and IP addresses now.
=> Use .present? instead of .empty? for displaying logs

app/assets/stylesheets/application.scss, app/views/ips/index.html.erb, app/views/ips/new.html.erb, app/views/team_members/index.html.erb
I don't think this needs any new tests, but I'm happy to hear opinions.
(Cheeky to put aligning in the same PR, can rebase rather than squash to keep them separate)
The form without locations, and an example of the right-aligned button looking nice:
=> When adding IPs and this is the first location, hide locations dropdown (+minor styling fix)

app/views/ips/new.html.erb, app/views/logs/search.html.erb, app/views/users/confirmations/new.html.erb, app/views/users/confirmations/show.html.erb, app/views/users/invitations/edit.html.erb, app/views/users/invitations/new.html.erb, app/views/users/passwords/edit.html.erb, app/views/users/passwords/new.html.erb, app/views/users/registrations/new.html.erb, app/views/users/sessions/new.html.erb
GDS design guidelines recommend against HTML5 attribute-driven validation messages.
This PR removes explicit `required: true` attributes, and puts a `novalidate` marker on forms that have special field types. Removing the special field types is undesirable, as they have other useful behaviour (e.g. email fields giving you a different keyboard on mobile devices)
These messages (+positioning) still need some love, but this is a step forward.
=> Remove HTML5 validation from forms

spec/features/logging/view_auth_requests_for_a_username_spec.rb, spec/features/logging/view_auth_requests_for_an_ip_spec.rb
Log requests are only shown for the last two weeks, so hardcoding the date meant they switched from passing to failing yesterday.
=> Dynamic dates for log search spec

Makefile
I'm not sure how `make test` is working in our pipeline without this, but it doesn't work on a fresh checkout. If you `serve` before you `test` it'll work, which might give the false impression things are fine.
Should we `make stop` before we `serve` or `test`, to make sure we don't have problems like this in the future?
Alternately, is this something about my specific machine setup, rather than an actual problem?
=> Start read-replica container for tests

lib/gateways/sessions.rb
We limit results to be within the last 2 weeks, but even so it can be a
large number of results.
There was an additional limit of 100, this isn't enough.
Increase this to 500.
=> Increase limit on the amount of logs shown

app/views/layouts/_flash_notices.html.erb, config/locales/devise.en.yml
This disables two error messages:
1. When a user is signed in and visits a non-authenticated route (eg `/users/sign_in`), devise flashes a notice that says "You are already signed in.". This is now disabled.
2. When a user is not signed in and tries to visit an authenticated route (eg: `/team_members`), devise redirects to the login page and flashes a notice "You need to sign in or sign up before continuing". This is also disabled.
Now when users are already signed in, they will be silently redirected to the correct place. When they are not signed in, they will simply be presented with the sign in screen.
This approach seemed preferable to overriding this controller: https://www.rubydoc.info/github/plataformatec/devise/DeviseController:require_no_authentication
=> Disable devise's sign in error messages

db/seeds.rb
The .email on Faker::Company is raising an error about missing
translations.  We don't need this to be a dynamic email, just use a
static one.
=> Fix seeding of organisations in development

Dockerfile
**What**
Match the ruby version in the Dockerfile to the one specified in `.ruby-version`
**Why**
Dockerfile was only referencing `major`.`minor` version of ruby which meant it was pulling in the latest version of 2.5.x (2.5.3), where as the solution is bound to 2.5.1. This causes `make build` to fail with the following error:
```shell
Your Ruby version is 2.5.3, but your Gemfile specified 2.5.1
ERROR: Service 'app' failed to build: The command '/bin/sh -c ${BUNDLE_INSTALL_CMD}' returned a non-zero code: 18
make: *** [build] Error 1
```
=> Match ruby version in .ruby-version

app/views/layouts/application.html.erb
Add script to allow cross tracking across admin, tech-docs and the product pages.
=> Add google analytics script for cross tracking

Gemfile, Gemfile.lock, config/initializers/rack_profiler.rb
**What**
Enables [`rack-mini-profiler`][link_rack_mini_profiler] for the development environment.
**Why**
Required for [Live Services Supportability][link_lss].
[link_rack_mini_profiler]: https://github.com/MiniProfiler/rack-mini-profiler
[link_lss]: https://github.com/madetech/live-services-field-guide/blob/master/processes/checklists/supportability.md
=> Add profiler

app/views/help/index.html.erb, config/site.yml
I started off looking for broken links to tech-docs, but this link isn't really relevant any more.
This could do with some :eyes: on the content, but it does resolve a broken state, so you could argue we should press ahead and then change again later.
Old:
New:
=> Troubleshoot through admin features

config/site.yml
Couple of links are broken because of the product page's new paths (no .html).
Should have looked for these when changing the product page paths. Not sure how best to prevent these links breaking in general, feels like they'll be changing less often now.
=> Change external app links to new paths

app/views/layouts/application.html.erb
Based on recommendations from researchers, the feedback banner needs to go to contact us page rather than be a mailto link.
=> Direct feedback to contact us page

app/views/layouts/application.html.erb
Remove gtag script
Script for installing tag manager has been added on a previous commit in a different branch.
=> Remove previous gtag script for google tag manager.

Jenkinsfile, app/views/layouts/application.html.erb
From the AWS docs:
> If your updated Docker image uses the same tag as what is in the existing task definition for your service (for example, my_image:latest), you do not need to create a new revision of your task definition.
> You can update the service using the procedure below, keep the current settings for your service, and select `Force new deployment`.
> The new tasks launched by the deployment pull the current image/tag combination from your repository when they start."
Pretty sure this is the model we're following - tagging a docker image as 'latest' or similar and then wanting to deploy it.
This command seems to works locally, but 
a) I'd need to get a new master build up to check and 
b) it leaves an extra container running (this PR might need a terraform friend for autoscaling …
=> Run aws update-service command to deploy

Jenkinsfile
The ECS production cluster is called `wifi-admin-cluster` rather than `production-admin-cluster`, and the service is called `admin-wifi` rather than `admin-production`.
=> Key on 'wifi' rather than 'production'

app/assets/stylesheets/components/main_nav.scss, app/views/layouts/application.html.erb
We want the active state to be blue like the other applications.
This adds a style to do this and markup.
No need to do this on sign out as you will be redirected.
=> Ensure the top navigation is consistent for all 3 apps

Makefile
Switch to adhere to [Made Tech's Makefile standards](https://github.com/madetech/rfcs/blob/master/rfc-012-makefile-standards.md), but mainly because I forget this particular app is `bash` not `shell` when I'm working on multiple apps.
Also simplify the command within it, `docker-compose` can handle finding the container to run against by its friendly name.
=> Rename make bash -> make shell, simplify

app/assets/stylesheets/components/sub_nav.scss, app/assets/stylesheets/utilities/layout.scss, app/views/application/_subnavigation.html.erb
When a user has a large organisation name it affects the alignment of the sub navigation bar. This change allows an organisation to have a large name and maintain a professional look for the sub navigation bar.
Before: 
After:
=> Fix large organisation name disrupting the sub nav

Makefile
This does 2 things:
- use docker-compose for executing the app
- try to execute within a running container first, then fall back to building + running a new container
It might be worth turning this into a macro in the future to reduce duplication in the makefile, but can slate that for another day
=> fix running of 'make shell'

config/environments/development.rb
This enables support for partial preprocessing, which greatly speeds
up page loads after a style change.
=> Disable debug mode in asset pipelines

app/models/permission.rb, app/models/user.rb, db/migrate/20181112122154_create_permissions.rb, db/schema.rb, spec/models/user_spec.rb
This PR allows you to check whether a User `can_manage_locations` or `can_manage_team`, and makes it so all new Users have both permissions, but does not implement checking these permissions anywhere.
At one point this did have more methods for the permissions everyone has - like `view_locations` - but given that _everyone_ has these for the foreseeable future, leaving them out for now.
=> Add basic permissions to users

app/controllers/users/invitations_controller.rb, app/views/team_members/_table.html.erb, app/views/team_members/index.html.erb, spec/features/team/permissions_spec.rb
We don't want everyone to be able to add and remove team members.
Use the permission system to check that a user is allowed to manage the
team before displaying the button to the invite page.
Also redirect to the root page if the URL was visited directly.
=> Restrict managing team to users with permissions

app/controllers/ips_controller.rb, app/views/home/index.html.erb, app/views/ips/index.html.erb, spec/features/ips/permissions_spec.rb
We don't want everyone to be able to add and remove IP addresses and
locations.
Use the permission system to check that a user is allowed to manage
this.
This will hide certain UI elements and redirect people if a page was
visited directly for managing IP addresses.
=> Restrict managing IP addresses and locations

app/controllers/permission_controller.rb, app/views/permission/edit.html.erb, app/views/team_members/_table.html.erb, config/routes.rb, spec/features/team/edit_permissions_spec.rb
We want to restrict some features.
An admin with the .can_manage_team permission can change the permissions
of other existing users.
=> Allow a user to edit team permissions

app/controllers/users/invitations_controller.rb, app/models/user.rb, app/views/users/invitations/new.html.erb, spec/features/team/invite_with_permissions_spec.rb
When you invite another network administrator, you can set their
permissions to manage their team and ips/locations.
=> Allow setting permissions for a new invite

app/views/ips/index.html.erb
=> Remove text explaining how to remove IPs

app/views/admin/mou/index.html.erb, app/views/admin/organisations/_mou_form.html.erb, app/views/admin/organisations/index.html.erb, app/views/application/_radius_details.html.erb, app/views/help/index.html.erb, app/views/home/index.html.erb, app/views/ips/_table.html.erb, app/views/logs/search.html.erb, app/views/mou/index.html.erb, app/views/team_members/_table.html.erb, app/views/team_members/index.html.erb, app/views/users/mailer/confirmation_instructions.html.erb, app/views/users/shared/_links.html.erb
All text links require the `govuk-link` class.
=> Add govuk-link class to all text links

app/models/organisation.rb, app/views/users/registrations/new.html.erb, config/locales/en.yml, spec/features/registration/sign_up_as_an_organisation_spec.rb, spec/models/organisation_spec.rb
Two ways:
1. Organisation name validation is now case insensitive, eg: `Toms Org == toms org`.
2. There is a more explanatory error message when a duplicate organisation tries to sign up:
=> Prevent duplicate organisation signups

db/seeds.rb
The `seeds.rb` file didn't work offline as the unconfirmed users it created tried to fire off invitations via Notify.
This has been fixed so that `rake db:seed` and therefore `make serve` now work offline.
=> Let seeds.rb file work offline

lib/use_cases/administrator/validate_log_search_query.rb, spec/use_cases/administrator/validate_log_search_query_spec.rb
There's thousands of older GovWifi accounts with 5-character usernames, so feels like we should cover them here.
=> Allow 5-character usernames for log searching

config/site.yml
Based on suggestions from the content designers to separate end-user support and admin-user support, end user support links redirect to the GOV.uk page and not to the GovWifi Product page.
=> Replace end user support links

app/controllers/users/confirmations_controller.rb, app/models/user.rb, app/views/users/confirmations/show.html.erb, app/views/users/invitations/edit.html.erb, app/views/users/passwords/edit.html.erb, lib/tasks/repair_migrated_data.rake, spec/factories/users.rb, spec/features/authentication/lock_user_account_spec.rb, spec/features/authentication/logging_in_after_signing_up_spec.rb, spec/features/authentication/reset_password_spec.rb, spec/features/registration/sign_up_as_an_organisation_spec.rb, spec/features/support/sign_up_helpers.rb, spec/features/team/accept_an_invitation_and_sign_up_spec.rb, spec/features/team/resend_invitation_spec.rb, spec/models/user_spec.rb
Requiring a user to confirm their password is rare and not done at GDS.
It was advised that we remove this as it doesn't provide that much
value.
=> Remove Password Confirmation

app/assets/stylesheets/components/team_members.scss, app/views/team_members/_table.html.erb, app/views/team_members/edit.html.erb, app/views/team_members/index.html.erb, spec/features/team/remove_a_team_member_spec.rb, spec/features/team/resend_invitation_spec.rb
Change "resend invite" from button to link 
Pull "edit permissions" to be in right-hand column instead of below
Made changes to edit team member page with rewording and styling.
After:
=> Improve team members UX

app/models/user.rb, spec/features/registration/sign_up_as_an_organisation_spec.rb
This validation was removed when the password confirmation was removed.
Restore this and print the error in the form if the password is left
blank.
=> Ensure error when password is blank when signing up

app/views/ips/new.html.erb, app/views/users/confirmations/show.html.erb
Remember the submitted params, and populate the form with it for a
better user experience
=> Don't lose form field values when a validation error occurs

app/controllers/ips_controller.rb, app/controllers/locations/ips_controller.rb, app/views/ips/_table.html.erb, app/views/ips/new.html.erb, app/views/locations/ips/new.html.erb, config/routes.rb, spec/features/ips/add_ip_to_location_spec.rb
This is the first cut using a `hidden_field` and utilising the existing `IpsController#create` action.
Next step will be using the `Locations::IpsController#create` action and refactoring the "after creating an IP" logic into a re-useable service. This won't change the user experience, it will just be a refactor.
=> Add IP to location

app/views/users/invitations/new.html.erb, config/locales/en.yml, spec/features/team/invite_a_team_member_spec.rb
Previously:
Now:
and with error:
=> Remove outdated text from team members page

app/views/logs/index.html.erb, spec/features/logging/view_auth_requests_for_a_username_spec.rb
=>  Improve results message that appears when logs are not found

app/views/logs/index.html.erb, lib/gateways/sessions.rb
If there are 500 results returned, the user gets an explanation explaining that results are truncated:
=> Explain to user if log results are limited

app/views/users/invitations/new.html.erb
Already existed in `team_members/edit` but needed to be added to `invitations/new`
=> Explain that all team members can see logs when inviting a user

app/controllers/users/invitations_controller.rb, app/views/users/invitations/new.html.erb, spec/features/team/invite_a_team_member_spec.rb
A requirement as often GovWifi admins will be external suppliers eg: bt.com
=> Allow non-gov.uk email addresses to be invited

app/controllers/users/invitations_controller.rb, app/controllers/users/registrations_controller.rb, app/models/user.rb, config/locales/en.yml, spec/features/registration/sign_up_as_an_organisation_spec.rb, spec/features/team/invite_a_team_member_spec.rb, spec/models/user_spec.rb
The validation that checks that a user's email is on the whitelist is only used during registration. During invitation the user can have any email address.
Having this validation on the model meant there was a lot of code in the invitations controller trying to avoid this check. 
As it only applies to 20% of the users, I have moved the whitelist validation off the model to the only controller that uses it. This simplifies the code changes coming in https://github.com/alphagov/govwifi-admin/pull/360
=> Move email whitelist validation to controller

Gemfile, Gemfile.lock, app/controllers/users/passwords_controller.rb, app/mailers/authentication_mailer.rb, config/locales/devise.en.yml, config/routes.rb, spec/features/authentication/reset_password_spec.rb
**WHAT:** The aim was to stop a user who hadn't confirmed their account from trying to reset their password.
**WHY:** Users who went down this route encountered an error stating that `Name can't be blank`. The name referred to here is the name they would have set through _confirming and finishing the creation of their account._
**IN THIS PR:** An initial solution was to send a confirmation email to the unconfirmed user instead of the reset password email, whenever they clicked on the reset password link in the admin portal. 
However, in terms of user experience, the user still sees a flash notice along the lines of `An email with instructions on how to reset your password has been sent`. So, the current idea of a solution is to deal with this at the controller level so that the …
=> Block unconfirmed users from resetting passwords

app/controllers/users/registrations_controller.rb, app/views/users/confirmations/pending.html.erb, spec/features/registration/sign_up_as_an_organisation_spec.rb
**WHY:**
It was suggested that the design of the pending confirmations page needed to be clearer. 
Currently a big green box is used and is unlike what other GDS services do.
The text in the `pending.html.erb` was edited to sound more like an example from a GDS site. And the styles on the tags were changed too.
**BEFORE:**
**AFTER:**
**SOLUTION**
In the snapshot above, the phrase " your email address " was left bold. The idea is to replace this phrase will the user's own email that they just used to sign up. 
To do this, a method in the `RegistrationsController` was modified to receive the user's email as an argument. This added the user's email as a parameter that could …
=> Clean up design of the page with confirmation instruction meant for after signing up

app/models/location.rb, lib/use_cases/administrator/generate_radius_secret_key.rb, spec/requests/monitoring/healthcheck_spec.rb, spec/use_cases/generate_radius_secret_key_spec.rb
We had a couple of extra folders for specs, folded things together so there's less noise.
11 folders before, 9 with this change:
I've got my eyes on more changes, but this was simple and uncontroversial (I hope!), so just a quick one before I look at the mocks.
=> Remove some noise in spec folders

app/views/help/index.html.erb, app/views/ips/new.html.erb, app/views/logs/search.html.erb
**WHY:**
This was done based on a suggestion to edit the design of text boxes to suit the length of the input required in them.
**IN THIS PR:** 
Edit the input classnames for the appropriate text fields.
**SOLUTION EXAMPLE:**
**BEFORE:**
**AFTER:**
=> Resize the input boxes on admin

spec/features/authentication/lock_user_account_spec.rb, spec/features/authentication/reset_password_spec.rb, spec/features/support/mock_notification_client.rb
Doing these tests a few at the time to help inform the design of the notifications mock. This PR adds recording the URLs that are often found in the emails we sent out, should make it easier for these tests to.
Replacing five requires with a single one is pretty sweet.
=> Extend notifications mock to include links

spec/features/guidance_after_sign_in_spec.rb, spec/features/ips/view_ip_address_readiness_spec.rb, spec/features/ips/view_ip_addresses_spec.rb, spec/features/locations/add_new_location_spec.rb, spec/features/team/invite_with_permissions_spec.rb, spec/features/team/permissions_spec.rb
This should make what's going on with these specs a little clearer, plus less maintenance cost than all these separate mocks (which can eventually be removed). 
Some of the specs aren't just a drop-in replacement - going to address those more slowly, probably as we touch the related areas.
=> Replace old mock with new mock

app/views/help/new.html.erb
Just noticed this as I was looking at the signed-out support page.
OLD;
NEW:
=> Link to referenced guidance, correct language

app/assets/stylesheets/utilities/layout.scss, app/controllers/home_controller.rb, app/views/home/index.html.erb
**WHY:**
It was suggested that if an organisation has setup and are running GovWifi then they don't need to see the get started checklist as the first page when they login. They should instead see something that gives them an overview of their current installation.
The changes to get to the solution would be added in increments and not implemented as a one large feature. This may allow for user feedback changes/additions to be easily implemented. 
The `index.html` file for the `HomeController` was modified to include a separator. 
Above the separator, html elements were added to create the overview dashboard look.
Below the separator, the setup instructions remain unchanged in this PR.
**BEFORE:**
**AFTER:**
**NEXT STEPS:**
The next iteration would involve reorganisation. …
=> Add dashboard display to overview page

config/routes.rb, spec/features/contact_us_when_not_signed_in_spec.rb, spec/features/contact_us_when_signed_in_spec.rb
The links from product page and tech docs were broken with the introduction of the new help pages. 
Could fix this here or on those apps, I'm easy. Here being permissive seems good.
=> Allow requests to /help

app/views/home/index.html.erb
**WHY:**
It was suggested that the bottom link looked out of place on this page since its contents is light.
There is also the non-scrollable link in the top nav bar for getting support should the user require it.
Remove the associated code within the `index.html` file for the `HomeController`.
**BEFORE:**
**AFTER:**
=> Remove getting help link at bottom of overview page.

app/assets/stylesheets/components/overview.scss
**WHY:**
In certain instances, the link styles for the links in the overview would be a different colour and/or disappear when the mouse hovers over it. One such instance is the incognito mode in Google Chrome.
More CSS pseudo-classes were added to the `summary-link-colour` CSS class to work around the limitations some browsers may put on changing the colour of links, especially visited links.
**BEFORE:**
**Google Chrome's Incognito Mode**
**Hovering over a link in this state (note: IPs has disappeared**
**AFTER:**
=> Fix the colour of the overview links in unique browser scenarios

app/controllers/admin/organisations_controller.rb, spec/features/admin/sort_view_in_organisation_list_spec.rb, spec/features/admin/view_organisation_tab_spec.rb
**WHY:**
It was suggested that viewing organisations in the order of most recently joined was an easier view to use.
Change the current setup of the associated tests to reflect the preferred change. The initial default view was by alphabetical order. 
**BEFORE:**
**AFTER:**
=> Make default super admin view of organisations ordered by most recent

app/models/logs_search.rb, app/views/logs_searches/_error_message.html.erb, app/views/logs_searches/ip.html.erb, app/views/logs_searches/new.html.erb, app/views/logs_searches/username.html.erb, spec/features/logging/view_auth_requests_for_a_username_spec.rb, spec/features/logging/view_auth_requests_for_an_ip_spec.rb, spec/models/logs_search_spec.rb
- Added the error highlighting class to each form field
- Added an error hint to each form field
- Improved the error messages
- Removed the duplicate error summaries when a search term was blank (it used to say "blank" and "invalid", now it just says "blank".
=> Add better errors to logging pages

app/controllers/help_controller.rb, app/views/help/signed_in.html.erb, app/views/setup_instructions/index.html.erb, spec/features/admin/view_organisation_list_spec.rb, spec/features/contact_us_when_signed_in_spec.rb, spec/features/guidance_after_sign_in_spec.rb
- Uses account email instead of asking a user to enter it
- Gives clearer direction to other ways of resolving problems
- Cuts out superfluous text
- Removes back link (there are multiple ways to get here and plenty of escape routes, "back" is more likely to confuse than help)
This page is serving multiple needs, I would expect to split it out in the near future, but think this is an improvement already.
=> Improve signed-in support page

app/views/ips/index.html.erb, app/views/ips/new.html.erb, app/views/locations/new.erb, app/views/setup_instructions/index.html.erb, spec/features/locations/add_new_location_spec.rb
**WHY:**
When a user's organisation has no locations and the user wants to add an IP, they get an empty drop-down selector in the "Add IP address" flow. A link to `Add a new location` is present but may cause confusion for a user whose desire is to **add a new IP address** since it is not stated that a location is required first before adding an IP address.
**Current Display for organisations without any locations:**
**Current Display for organisations with at least one location:**
- A working suggestion is to redirect the user to the `new_location_path` when they click on the `add an IP address` button, if their organisation has not added any locations. 
- When they land …
=> Fix confusion when an organisation is adding IPs for the first time with no existing locations

app/assets/stylesheets/components/main_nav.scss, app/views/layouts/application.html.erb
**WHY:**
When viewed on a mobile device, the top navigation links: `Documentation`, `Support` & `Sign Out`(or `Sign in` depending on the user's state) disappeared from the user's view.
**PREVIOUS DISPLAY ON MOBILE:**
- Include the gov-uk styled `button` html tag within the `application.html.erb` file.
- Add gov-uk classes to the `html` and `body` tags based on the html layout of the [Customised page template](https://design-system.service.gov.uk/styles/page-template/) example.
- Add span tags to align the menu to the right of the screen.
- Add media query for desktop and iPad Pro screens. Reasoning explained below:
The custom css class involved was done in a previous PR …
=> Fix visibility of the top navigation links on mobile view

app/assets/stylesheets/components/sub_nav.scss, app/views/application/_subnavigation.html.erb
**WHY:**
When viewing the support page, the sub-navigation shifts downwards since none of the tabs on the sub-nav are active. 
Add a "default" white border bottom to all the sub-nav tabs to keep the alignment consistent regardless of active state. When a tab is active, the appropriate CSS class will change the colour of the border from white to black.
**1. SUPPORT PAGE BEFORE:**
**2. SUPPORT PAGE AFTER:**
**3. WHEN TAB IS ACTIVE:**
**Any suggestion/feedback would be …
=> Align sub-navigation on support page for consistency across the platform

app/controllers/ips_controller.rb, app/controllers/locations_controller.rb, lib/facades/ips/publish.rb, spec/facades/ips/publish_spec.rb, spec/requests/ips/delete_spec.rb
We publish an IP whitelist to S3 whenever we create one, do the same
when we delete them
=> Ensure IP whitelist is updated when deleting IPs

db/seeds.rb
We've changed the validation to only allowed private IPs, but generated seeds can still be private IPs, which causes `make serve` to fail.
This PR changes the seed generation to only use public IPs (there's a Faker method for it out of the box).
Follow-up to https://github.com/alphagov/govwifi-admin/pull/428.
=> Fix make serve to reflect public IP validation

app/views/help/signed_in.html.erb
**WHY:**
- When an organisation has no locations and they click on the `search logs by location` link it takes them to the "hidden from navigation" `logs/search` page with no locations in the drop-down.
- The `logs` sub navigation link is hidden when an organisation has no locations(PR #404).
The thinking behind this was that there would be no logs if the organisation has not set up an IP to receive traffic with. Setting up an IP is not standalone but depends on there being a location added to the organisation's profile.
- Since the navigation to `logs` is hidden from view when an organisation has no locations, the remaining routes to that part of the app were the `search logs by location` & `search logs by username` links in the signed in support page.
- The two bullet …
=> Hide logs link if org has no locations

app/controllers/organisations_controller.rb
Due to the register implementation whenever we updated the organisation settings, the org name was also being updated, due to some orgs not being in our register it caused a validation error. This fix allows the user to ONLY update their service email and stop the validation error.
=> Validate only on service email

app/controllers/help_controller.rb, spec/features/contact_us_when_not_signed_in_spec.rb
**WHY:**
When a non signed-in user has `/help/new/signed_in` in their URL, the page displays an error. 
The signed-in support form uses details from the user's organisation that a non signed-in user lacks.
The `signed-in` method within the `HelpController` was modified to include a conditional check for the user's sign-in status. If the user is not currently signed in, it redirects the user to the non signed-in version of the support page.
=> Redirect signed out users to correct support page

app/models/custom_organisation_name.rb, db/migrate/20190207105214_create_custom_organisation_name.rb, db/schema.rb, lib/gateways/govuk_organisations_register_gateway.rb, lib/use_cases/organisation/fetch_organisation_register.rb, spec/factories/organisations.rb, spec/features/admin/add_custom_organisation_as_super_admin_spec.rb, spec/features/admin/delete_organisation_as_super_admin_spec.rb, spec/features/admin/edit_organisation_details_spec.rb, spec/features/admin/sign_in_as_super_admin_spec.rb, spec/features/admin/sort_view_in_organisation_list_spec.rb, spec/features/admin/view_organisation_tab_spec.rb, spec/features/registration/sign_up_as_an_organisation_spec.rb, spec/features/team/view_team_members_spec.rb, spec/fixtures/gov_orgs_payload.json, spec/fixtures/local_auths_payload.json, spec/gateways/govuk_organisations_register_gateway_spec.rb, spec/models/organisation_spec.rb, spec/use_cases/organisation/fetch_organisations_register_spec.rb
Allows custom organisations to be added, as before you could only choose organisations from the register provided. However now we have the ability to append other organisations to these registers to allow us to add other organisations that may not be on the official register yet.
=> Add custom organisations 

app/controllers/admin/custom_organisations_controller.rb, app/models/custom_organisation_name.rb, app/views/admin/custom_organisations/index.html.erb, app/views/application/_subnavigation.html.erb, config/routes.rb, lib/use_cases/administrator/send_confirmation_email.rb, spec/features/admin/add_custom_organisation_spec.rb
**This PR provides the user with a UI to add custom organisations to the combined registers list, so that the organisation added can then sign up to GovWifi through the normal signup journey.**
=> UI for adding custom orgs

app/views/layouts/application.html.erb
**WHY:**
Documentation link in the footer didn't go anywhere when clicked. It had no URL assigned to it.
Assigned the [tech docs](https://docs.wifi.service.gov.uk/#requirements) URL to it.
=> Fix documentation link in the footer

app/views/layouts/application.html.erb
**WHY:**
Design suggestion to move the feedback link to the footer.
Add feedback as list-item in the footer and make it link to the feedback form at `/help/new/feedback`.
**BEFORE:**
**AFTER:**
**_Suggestions and/or feedback welcome._**
=> Add feedback link into footer

app/assets/javascripts/googletagmanager.js, app/views/layouts/application.html.erb, config/initializers/assets.rb, config/site.yml
**WHAT:** 
This removes the current installation of Google Tag Manager in the admin portal. 
**WHY:**
This was done in preparation for the current installation of Google Analytics in the admin portal to be reconfigured.
=> Remove Tag manager Implementation

docker-compose.yml
this will ensure the database is launched when running the app directly
=> add the database as a dependency for the app

.dockerignore, Dockerfile, Makefile, docker-compose.development.yml
This avoids stale cache making it in, as well as `node_modules`, which can cause complications if compiled packages are used.
We also avoid putting implicit hidden files going in, such as the git directory.
Docker can do this in parallel, so let's do it in parallel.
Bind mounts are expensive, and we don't need them. Use volumes for cache, storage, and node modules
**note**, storage will now be discarded. Given the database is discarded, I assume this doesn't matter for our usecase.
This takes time, so defer it for when they're actually required.
**note** they'll still precompile on Jenkins
=> Various quick wins for docker

Makefile
For most operations, we need a populated database.
Ensure it is populated by launching the serve command.
This isn't ideal, as we are launching a server when it probably isn't necessary.
We should look into breaking out the database population from all our tasks.
=> always serve before opening a shell

lib/use_cases/administrator/create_signup_whitelist.rb, spec/use_cases/administrator/create_signup_whitelist_spec.rb
Given a list of domains, generate the PERL regular expression that will
be used to make sure someone is allowed to sign up to the admin or user
signup API.
A list of:
foo.com, bar.gov.uk
Will result in a regex like:
^.*@(foo\.com|bar\.gov\.uk)$
=> Use case to generate a signup whitelist

app/assets/stylesheets/components/sub_nav.scss, app/views/application/_subnavigation.html.erb
- Adds the gov.uk design system breakpoints to the subnav.
- On mobile the subnav and org name go to a new line and are centred.
- On desktop the subnav is inline and right aligned.
Mobile:
Tablet & Desktop:
=> Add responsive breakpoints to subnavigation

Jenkinsfile
With the move to fargate, we use awsvpc. This requires all tasks to have a network configuration.
Clone from the running service for running migrations
=> fetch parameters from admin service for run-task

app/models/authorised_email_domain.rb, spec/models/authorised_email_domain_spec.rb
There is a danger that malformed data entered here could produce a
corrupt whitelist regular expression.
Validate that only domains / subdomains are allowed to be saved.
=> Validate shape of the data being whitelisted

app/controllers/admin/authorised_email_domains_controller.rb, app/views/admin/authorised_email_domains/_confirm_remove_email_domain.html.erb, app/views/admin/authorised_email_domains/_table.html.erb, app/views/admin/authorised_email_domains/index.html.erb, config/routes.rb, spec/features/super_admin/authorised_email_domain_spec.rb, spec/requests/email_domain/delete_spec.rb
**WHY:**
As part of the upcoming functionality to delete an email domain. This makes sure that a new whitelist is uploaded after a deletion occurs.
- Add a test to describe the function in the feature.
- Add a test to describe the DELETE request.
- Add remove button in the whitelisted email domains table.
**STEP ONE:**
**STEP TWO:**
**STEP THREE:**
**Any feedback/suggestions would be appreciated.**
=> Upload whitelist after deleting an entry

lib/gateways/s3.rb, spec/gateways/s3_spec.rb, spec/spec_helper.rb
NB: In a later change, will rename the upload method to write to maintain consistency.
- Add read method to s3 gateway.
- This will be used to fetch the user sign up whitelist regex from the s3 bucket. 
- This read method is currently unused at this point.
=> Add read method to s3 gateway

lib/use_cases/administrator/create_signup_whitelist.rb, spec/features/super_admin/authorised_email_domain_spec.rb, spec/use_cases/administrator/create_signup_whitelist_spec.rb
We need this regex to be more lenient and to allow any subdomains of trusted TLDs.
This won't cause an issue and should remain largely the same.
=> Allow any subdomain for signup whitelist

app/controllers/users/registrations_controller.rb
We're using our new whitelist functionality and want to know
if someone was denied from signing up a new account in the admin.
=> Log unsuccessful signup attempts

app/controllers/users/registrations_controller.rb
We do this to see these logs in slack.
=> Replace cloudwatch logging with sentry capture message logging

app/controllers/users/registrations_controller.rb
Print to Cloudwatch instead when someone couldn't sign up due to
whitelisting
=> Disable sentry notifications

app/controllers/admin/organisations_controller.rb, app/views/admin/organisations/index.html.erb, spec/features/super_admin/view_organisation_list_spec.rb
Steve wasn't interested in IP totals (especially now you can't add a location without an IP) - from talking/demoing to him, I believe this is what is needed.
It's possible I missed some context whilst out of the office, so feel free to challenge this!
=> Show total orgs/locations to super-admins

app/views/admin/authorised_email_domains/_confirm_remove_email_domain.html.erb, app/views/admin/authorised_email_domains/_table.html.erb, app/views/admin/authorised_email_domains/index.html.erb, spec/features/super_admin/authorised_email_domain_spec.rb
When removing a domain from the signup whitelist, print that domain for
extra protection
=> Improve deletion confirmation by printing domain

app/controllers/users/registrations_controller.rb, app/views/users/confirmations/pending.html.erb, spec/features/registration/sign_up_as_an_organisation_spec.rb
**WHY:**
PII is any data that can potentially identify a particular individual. 
We currently pass the email address of a new user signing up as a query string in the pending page URL. This allowed for the confirmation message to be personalised to the specific user.
**INITIAL SCREENSHOT:**
**Please note:** 
**- The URL in the screenshot.**
**- The personalised message.**
However, in order be more compliant with GDPR standards and be prepared to use Google Analytics more effectively _(We were advised that G.A have some policies around user-specific details being passed as query strings in URLs)_:
1. We have stopped passing params to this URL.
**RESULT 1:**
**Please note:** 
**- The URL in the screenshot.**
**- The lack of a personalised message.**
2. The personalised …
=> Stop passing the user email as a query string to the pending URL

app/controllers/users/registrations_controller.rb, app/views/layouts/_form_errors.html.erb, app/views/users/registrations/new.html.erb, config/locales/en.yml, spec/features/invite_existing_user_spec.rb, spec/features/registration/sign_up_as_an_organisation_spec.rb, spec/features/team/invite_a_team_member_spec.rb
Empty or invalid email domain:
Already existing email:
=> Better error messaging on signup 

app/views/layouts/_form_errors.html.erb, config/locales/en.yml, spec/features/registration/sign_up_as_an_organisation_spec.rb
**WHY:**
When a user signs up to create an account for an existing organisation. The error message includes the support email. 
It would be better to change this to a link to the offline support form with the app.
Add a link within the message in the `en.yml` file.
**BEFORE:**
**AFTER:**
**Any suggestions/feedback would be appreciated.**
=> Replace support email with contact us link

app/views/admin/manage_users/index.html.erb, db/seeds.rb
**WHY:**
Better to change the `created_at` time to a more human readable format.
- Add unconfirmed users to the `seeds.rb` file
- Use `strftime` method to format the time in the `index.html.erb`.
**BEFORE:**
**AFTER:**
**Any suggestions/feedback would be appreciated.**
=> Format date in the unconfirmed user list in super admin

app/models/support_form.rb, spec/features/contact_us_when_not_signed_in_spec.rb
A Sentry error was being raised due to bad emails being submitted via the offline support form. Eg `test@gov. uk`.
https://sentry.io/organizations/government-digital-services/issues/937104856/?project=1259357&referrer=slack&statsPeriod=14d
This solution uses Devises email validator that we already use on the User model by virtue of it being a Devise model.
Had to refactor the spec slightly so its a bit hard to see the new specs in the diff. I left a comment to help find the new specs.
=> Prevent bad emails being submitted to Zendesk

.dockerignore, .erb-lint.yml, .rubocop.yml, Dockerfile, Gemfile, Gemfile.lock, Makefile
running: `make lint-erb`
I've purposefully not linked it up to `make lint` yet, as the fixes should come in another PR, lest this PR be made up of 70 file changes.
I've also deliberately disabled `ErbSafety` on a file which uses `html_safe`. While this isn't ideal, it's what is needed.
This also adds a rubocop config that inherits from the GDS styling. This is so other tools (namely erblint) can utilise a common styling.
This inadvertently adds support for running `rubocop`, as well as being able to enable `rubocop` based autofixing in our editors
=> introduce an ERB Linter

Dockerfile
a recent change to puma means the default bind is 'localhost' instead of '0.0.0.0' for development.
This breaks when running rails inside docker.
move to using '0.0.0.0' as default. This does not affect hosted environments, which already defaults to '0.0.0.0'
=> ensure we bind the IP address when serving in development

.rubocop.yml, spec/features/logout_user_after_inactivity_spec.rb
`spec/features/logout_user_after_inactivity_spec.rb`
Explicitly return timecop.
=> Lint logout user after inactivity spec

app/views/logs/_back_link.html.erb, app/views/logs/_filtered_results_explanation.html.erb, app/views/logs/_no_logs_explanation.html.erb, app/views/logs/index.html.erb
When the super admin views logs, the copy was geared towards organisations and made no sense to super admins.
This PR:
- removes organisation specific copy from the super admin view
- gives super admin advice on how to solve the problem
- uses partials to make the view file easier to comprehend
**SUPER ADMIN**
**ORGANISATION**
=> Super admin logs copy

app/controllers/admin/mou_controller.rb, spec/features/super_admin/upload_download_mou_spec.rb, spec/fixtures/mou.not_accepted_file_type
This PR fixes the error when the user does not select an MoU template and clicks upload.
=> Validate MoU upload for super admin

Makefile
This greatly speeds up anything that doesn't need the database, namely the linting and autocorrecting.
This is safe, as the main reason we explicitly stop is to clear out the database.
Anything that needs the database clearing must now be explicit.
=> Makefile: don't clear the database to rebuild the image

app/controllers/mou_controller.rb, config/routes.rb, spec/features/upload_download_mous_spec.rb
`/mou -> /mou/created`
`/mou -> /mou/replaced`
=> add analytics paths for MOU uploading

app/models/organisation.rb, app/views/layouts/_form_errors.html.erb, spec/features/registration/sign_up_as_an_organisation_spec.rb, spec/models/organisation_spec.rb
**WHY:**
When a user doesn't select an organisation from the drop down list of whitelisted organisations and tries to finish creating their account at the confirmation stage. The page would display both these errors: 
- `Organisation name can't be blank`
- `Organisation base isn't a whitelisted organisation`
The organisation name field can only be filled by selecting from the drop-down menu of whitelisted organisations.
The field does not receive/pass any user text inputted directly.
So an instance of a user 'filling in' the field with a name not on the list and an instance of a user leaving the field blank result in the same thing: 
- No organisation is selected and so, no name is received for the organisation name value.
- The subsequent validation of the name value (based on presence) …
=> Don't display whitelist error when no organisation is selected

app/views/users/confirmations/new.html.erb, app/views/users/confirmations/show.html.erb, app/views/users/passwords/new.html.erb, app/views/users/registrations/new.html.erb, app/views/users/sessions/new.html.erb, app/views/users/shared/_end_user_warning.html.erb, spec/features/authentication/reset_password_spec.rb, spec/features/registration/sign_up_as_an_organisation_spec.rb
Improve the "end user warning" as well as display it everywhere an end user could potentially find themselves.
=> Improve language to help redirect lost end users

app/views/admin/authorised_email_domains/_table.html.erb
**WHY:**
The table for the whitelisted emails just displays email domains and a remove link to the super admin.
See below:
- The table style was edited so that a `Date Added` table heading could be added.
- Added heading for email domains.
- Extra wording to describe the table.
**Any feedback/suggestions on this, would be appreciated.**
=> Add whitelisted email domains table headings 

app/controllers/admin/organisations_controller.rb, app/controllers/team_members_controller.rb, app/views/admin/organisations/_team.html.erb, app/views/admin/organisations/show.html.erb, lib/gateways/organisation_users.rb, lib/use_cases/administrator/sort_users.rb, spec/features/super_admin/organisations/view_organisation_page_spec.rb, spec/gateways/organisation_users_spec.rb, spec/use_cases/administrator/sort_users_spec.rb
Alphabetising the list on the "show organisation page" in super admin. Must have been missed off the original task.
Involves a refactor using Clean Architecture to DRY up the code. Not 100% sure this is the right way to do it with CA so welcome feedback.
=> Alphabetise team list in super admin

app/controllers/home_controller.rb, app/views/application/_subnavigation.html.erb, config/routes.rb, spec/features/allow_GA_to_track_new_org_spec.rb, spec/features/contact_us_when_signed_in_spec.rb, spec/features/ips/permissions_spec.rb, spec/features/ips/view_ip_addresses_spec.rb, spec/features/overview/view_overview_page_spec.rb, spec/features/super_admin/authorised_email_domain_spec.rb, spec/features/super_admin/upload_download_mou_spec.rb, spec/features/support/setup_instructions.rb, spec/features/support/user_not_authorised.rb, spec/features/team/permissions_spec.rb, spec/features/track_new_organisations_spec.rb
**WHY:**
Google analytics (GA) will be used to track users using the app. GA needs to be able to follow a new organisation's "conversion" pathway. i.e an organisation creating its first IP.
A new organisation is an organisation with **zero IPs**, regardless of when they signed up and how many team members or locations they have.
However, there was no way for GA to differentiate between a new org and an org with an IP setup when the land .
e.g 
- Setup Instructions Page URL for a new organisation: `/setup_instructions`.
- Setup Instructions Page URL for an org with at least one IP setup: `/setup_instructions`.
This is the same url, and would therefore look the same when tracking in GA.
_This PR is the first step to allowing GA to track activity paths of new organisations._ …
=> Modify setup instructions URL structure for new orgs

app/controllers/admin_controller.rb, app/controllers/application_controller.rb, app/controllers/home_controller.rb, app/controllers/logs_controller.rb, app/controllers/users/invitations_controller.rb, app/views/application/_subnavigation.html.erb, app/views/logs/_filtered_results_explanation.html.erb, app/views/logs/_no_logs_explanation.html.erb, app/views/logs_searches/new.html.erb, db/schema.rb, db/seeds.rb, spec/factories/users.rb, spec/features/super_admin/authorised_email_domain_spec.rb, spec/features/super_admin/custom_organisations/add_custom_organisation_spec.rb, spec/features/super_admin/custom_organisations/delete_custom_organisation_spec.rb, spec/features/super_admin/invite_user_to_organisation_spec.rb, spec/features/super_admin/logging/view_logs_for_ip_spec.rb, spec/features/super_admin/logging/view_logs_for_username_spec.rb, spec/features/super_admin/organisations/delete_organisation_spec.rb, spec/features/super_admin/organisations/sort_organisation_list_spec.rb, spec/features/super_admin/organisations/view_organisation_list_spec.rb, spec/features/super_admin/organisations/view_organisation_page_spec.rb, spec/features/super_admin/sign_in_as_super_admin_spec.rb, spec/features/super_admin/upload_download_mou_spec.rb, spec/requests/email_domain/delete_spec.rb
Moves the `super_admin` boolean to organisation. So now to invite a super admin, the super admin would just need to invite them to the "GovWifi Super Administrators" organisation.
=> Move super admin privileges to the organisation

app/views/application/_subnavigation.html.erb
We used to not show the real organisation name if you were signed in as a super admin. This is no longer required.
Before:
After:
=> Always show organisation name in subnav

app/views/layouts/_google_analytics.html.erb
**WHY:**
_This PR is version 2 of second step to allowing GA to track first IP creation activity paths. PR #602_
First step is PR #595 
A new organisation is an organisation with no IPs set up regardless of adding other things e.g location, team members.
We want to follow a new organisation's conversion i.e adding their first IP address and thus making their installation of GovWifi count as an active one.
We need to follow the difference between new and existing organisations through the "create IP" pathway.
- Add data layer script with `signed_in` and `hasIPs` variables:
**_Added  a `signed_in` variable because `hasIPs` is false when the user is not signed in._**  …
=> Track new organisation first IP creation pathway v2.0

.rubocop.yml, spec/gateways/govuk_organisations_register_gateway_spec.rb, spec/gateways/ips_spec.rb, spec/gateways/s3_spec.rb, spec/gateways/zendesk_support_tickets_spec.rb
**WHY:**
Consistency & general housekeeping.
Lint and refactor the following files in the `spec/gateways` folder:
- `spec/gateways/s3_spec.rb`
- `spec/gateways/zendesk_support_tickets_spec.rb`
- `spec/gateways/govuk_organisations_register_gateway_spec.rb`
- `spec/gateways/ips_spec.rb`
**Any suggestions/feedback would be appreciated.**
=> Lint specs in gateways folder part one

Dockerfile, Makefile
- it causes issues with file detection
- we don't need it, as the lock file is auto generated
=> don't glob on the Gemfile

Jenkinsfile
a recent change means we only pass flags in now. Ensure we building production ready images for deployment
=> ensure we set the new build arg for deployment images

.rubocop.yml, spec/features/invite_existing_user_spec.rb, spec/features/super_admin/invite_user_to_organisation_spec.rb, spec/features/team/accept_an_invitation_and_sign_up_spec.rb, spec/features/team/invite_a_team_member_spec.rb, spec/features/team/resend_invitation_spec.rb, spec/requests/users/invitations/create_spec.rb, spec/support/invite_use_case.rb, spec/support/reset_password_use_case.rb
Lint and refactor the following files in the spec/requests folder:
`spec/support/reset_password_use_case.rb`
`spec/support/invite_use_case.rb`
Rename shared example usage were relevant
=> Lint support specs part two v2

Dockerfile
This is a partial revert of #617 
We seem to have some issues on our Jenkins installation where every so often, builds will fail due to issues with the `/tmp` directory.
Roll back to debian as a short term resolution
=> Rollback alpine

.rubocop.yml, app/assets/stylesheets/components/plain_list.scss, app/views/application/_radius_details.html.erb, spec/features/guidance_after_sign_in_spec.rb
This list of Ips should have been a `ul` from the start. So I've fixed this which makes it easier to test properly and pass linting.
Still looks the same:
=> Refactor and improve specs for displaying radius Ips

app/views/layouts/_google_analytics.html.erb
**WHY:**
Based on feedback from Merkle, refactored the dataLayer script.
Also, the variable `hasIPs` is always false for super admins and this might lead to a false negative.
Another variable i.e `superAdmin` was added to the data layer.
- Changed `dataLayer` to `window.dataLayer`
- Added superAdmin variable
_Super Admin view (note: `hasIPs` has a false value for a super administrator):_
Should we be considering using the Data Layer with HTML Event Handlers, we currently don't?
We assign methods as the value to our dataLayer variables.
**Any suggestions/feedback on this would be appreciated.**
=> Refactor dataLayer script

app/models/ip.rb, lib/use_cases/administrator/check_if_valid_ip.rb, spec/features/ips/add_ip_to_existing_location_spec.rb, spec/models/ip_spec.rb, spec/use_cases/administrator/check_if_valid_ip_spec.rb
**WHY:**
An IPv4 address is what we take from the user. 
We don't accept other types of IP addresses and we let the user know through error messaging when an invalid IP address was inputted.
However, the error message displayed to the user is vague.
When a user enters a valid IPv6 address they see:
`'1200:0000:AB00:1234:0000:2552:7777:1313' is not valid`
but are not informed why it is not valid.
IN THIS PR:
- Add hash key-value to the use case that checks the validity of submitted IP addresses. This would describe whether the IP address is IPv6 or not.
- Add custom error message for when the value of the IPv6 hash key is true.
- Refactor modified files.
**BEFORE:**
**AFTER:** …
=> Add custom IPv6 error message

lib/use_cases/administrator/check_if_valid_ip.rb, spec/features/ips/add_ip_to_existing_location_spec.rb, spec/models/ip_spec.rb, spec/use_cases/administrator/check_if_valid_ip_spec.rb
**WHY:**
A public IPv4 address is what we take from the user. 
We don't accept private IP addresses and we let the user know through error messaging when a private IP address was inputted.
However, the error message displayed to the user is vague.
When a user enters a private IP address they see:
`'192.168.0.0' is not valid`
but are not informed why it is not valid.
IN THIS PR:
- Add conditional message for private IP addresses.
- Refactor modified files.
**BEFORE:**
**AFTER:**
**Any feedback/suggestions would be appreciated. Currently looking at refactoring opportunities**
=> Add custom private IP address error message

ci/pipelines/pr.yml
We've recently moved from ruby-alpine to debian, as alpine was giving us some issues.
Ensure we're caching the correct image, which takes us from 9 minutes to 4.5 minute run times
=> cache the ruby debian image

app/models/ip.rb, spec/features/ips/add_ip_to_existing_location_spec.rb, spec/models/ip_spec.rb
**WHY:**
When a user is adding an IP and tries to submit a blank IP address field, the user receives two error messages:
- the blank IP error: `Address can't be blank`
- the IP invalid errors: `Address '' is not valid`
We should only display the blank error message for when a user tries to submit a blank IP address field. `Address '' is not valid` adds no meaning.
- Test that only error message is displayed when a blank IP address is submitted.
- Add condition to skip adding the custom error message when the IP is blank.
**BEFORE:**
**AFTER:** …
=> Fix multiple ip errors when adding a blank IP

Guardfile, Makefile, bin/setup, bin/update, config/environments/development.rb, config/initializers/read_replica_database.rb, config/routes.rb, db/seeds.rb
Removes the arguments from  `bundle exec govuk-lint-ruby` in the `Makefile`.
Did a lot of disabling here.
=> Lint all remaining ruby files

lib/use_cases/administrator/check_if_valid_ip.rb, spec/features/ips/add_ip_to_existing_location_spec.rb, spec/models/ip_spec.rb, spec/use_cases/administrator/check_if_valid_ip_spec.rb
**WHY:**
When a user enters a wrong IP address (e.g looks like an IP but isn't). The error message currently says for example, `Address '1.2.1111.2222.111' is not valid` which is a bit vague. 
We want the user to be more informed when they see an error message.
- Reword the message to read `Address '1.2.1111.2222.111' is not a valid IP address`
**BEFORE:**
**AFTER:**
**Any suggestions/feedback would be appreciated. Especially on the rewording.**
=> Edit invalid ip error message

ci/pipelines/deploy.yml
docker-image resource no longer supports passing in the tag directly as a parameter
=> write deployment tag to a file

README.md, app/views/ips/index.html.erb, app/views/shared/_filter_search.html.erb
This is a better user experience than not displaying any error messages.
=>  Print no results message when filtering in the UI 

app/models/ip.rb, app/views/ips/_table.html.erb, spec/features/ips/view_ip_addresses_spec.rb, spec/models/ip_spec.rb
Administrators find it challenging to identify which IPs are no longer
serving traffic.  Label an IP as inactive so they can safely remove
them.
=> Display when an IP is inactive

config/initializers/devise.rb, config/locales/devise.en.yml, spec/features/authentication/lock_user_account_spec.rb, spec/features/authentication/reset_password_spec.rb, spec/features/registration/resend_confirmation_instructions_spec.rb
**WHY:**
We should not display messages that could give an attacker any information about the existence or status of a user account. 
e.g When entering a username/password combo, we would potentially be telling an attacker that the username entered was correct if the error message only displays `password is incorrect` or vice-versa.
Good read on this is the [OWASP Cheatsheet.](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Authentication_Cheat_Sheet.md)
We should be responding with generic messages that give no indication as to whether:
- An account exists or doesn't.
- Any sign-in credentials are correct or incorrect.
Devise has a [paranoid feature](https://github.com/plataformatec/devise/wiki/How-To:-Using-paranoid-mode,-avoid-user-enumeration-on-registerable). 
This …
=> Give no indication of the existence of a user's account.

app/models/organisation.rb, spec/features/edit_organisation_details_spec.rb, spec/features/registration/sign_up_as_an_organisation_spec.rb, spec/models/organisation_spec.rb
**WHY:**
When a user adds or edits their organisation's service email, it only validates the email's presence i.e. `email can't be blank` but it doesn't validate the email's format.
As a result, this allowed any form of text to be accepted and saved to the organisation, even if the text was not an email address.
- Add validation on the service email to match Devise's email regex.
- Add tests on the model and on the feature to describe validating a service email's format.
**BEFORE:**
Adding any text and clicking on save, redirected to the Team members page and displayed:
**AFTER:**
Adding any text and clicking on save, check's the format of the text and displays an error …
=> Validate service email format when creating or updating it

app/controllers/help_controller.rb, spec/features/contact_us_when_signed_in_spec.rb
**WHY:**
There's a bug that occurs when a signed in user clicks on the `Documentation` menu link and then subsequently clicks on the `Support` menu link.
The support page displayed to the signed in user is the offline support page.
Clicking on the `Support` link again redirects the user to the online support page.
A signed in user should only ever see the online support page and user not signed in, should only ever see an offline version of the support page.
- Add a redirect in the new method in the [`HelpController`](app/controllers/help_controller.rb) to redirect to the signed_in version of support if the user is signed in.
- Refactor a [test](https://github.com/alphagov/govwifi-admin/compare/fix-display-error-offline-support?expand=1#diff-102458bca0162d5fc48989ced7de8b51 …
=> Redirect from offline support if signed in

app/views/layouts/application.html.erb, config/site.yml
Normalised the main navigation to match our other GovWifi related pages, so not to confuse the user.
=> Add 'Connect to GovWifi' & Offer GovWifi' links to main nav

Makefile
Ever since we set up inheritance of the rubocop config for ERB linting,
'rubocop' and 'govuk-lint-ruby' both do the same thing.
Recently, govuk-lint has been giving us random failures due to not finding a temporary file.
As govuk-lint is being deprecated ( alphagov/govuk-lint#109 ), move to rubocop as it just works.
This fixes the random lint failures we've been getting sporadically:
```
Configuration file not found: /tmp/tmp-rubocop-all.yml20190429-1-1l4lnm2
```
=> use rubocop directly instead of govuk-lint-ruby

app/assets/stylesheets/components/footer.scss, app/views/layouts/application.html.erb, app/views/setup_instructions/index.html.erb, spec/features/ips/view_ip_addresses_spec.rb, spec/features/support/setup_instructions.rb, spec/features/support/user_not_authorised.rb, spec/features/team/permissions_spec.rb
**WHY:**
Need to match the footer across all admin pages for consistency.
- Restructure footer to be the same as the one in the product page.
- Fix & refactor tests that failed as a result of the footer change.
BEFORE:
**AFTER:**
**Any feedback/suggestions would be appreciated.**
=> Update footer to match product page

app/views/help/admin_account.erb, app/views/help/technical_support.html.erb, app/views/help/user_support.html.erb
This task involved adding titles and meta descriptions to the three help pages which are exposed to users without having to sign in.
=> Add title and meta descriptions to help pages

app/views/help/new.html.erb, spec/features/contact_us_when_not_signed_in_spec.rb, spec/features/registration/sign_up_as_an_organisation_spec.rb
**WHY:**
We needed to update the content on: `https://admin.wifi.service.gov.uk/help` to effectively signpost and triage users more effectively and reconcile with incoming links from product pages, particularly `/support`. 
- update page title
- update meta description:
- update content per [spreadsheet](https://docs.google.com/spreadsheets/d/141spueIa6sG7Eyv6EjsqFn8s4ubJ8YX0LzpS0kGT91Q/edit#gid=175160880)
**BEFORE:**
_**Page content**_
**AFTER:**
_**Page content**_
**_Meta description_**
**_Page title_**
**Any feedback/suggestions would be appreciated.**
=> Update admin help page

app/models/organisation.rb, db/migrate/20190501150308_add_uuid_to_organisations.rb, db/migrate/20190502092749_add_uuid_index_to_organisations.rb, db/schema.rb, spec/models/organisation_spec.rb
When creating an organisation, it will create its own uuid and persist
it in the database. All existing organisations will be manually
backfilled to contain new uuids.
=> Add uuid to organisations

app/controllers/admin/whitelists/email_domains_controller.rb, spec/features/super_admin/whitelists/authorised_email_domain_spec.rb, spec/requests/email_domain/delete_spec.rb
This PR allows the S3 email domains list object to be update on delete.
=> Publish list of domain names to S3 on delete

app/controllers/application_controller.rb, app/controllers/users/invitations_controller.rb, app/models/cross_organisation_invitation.rb, app/models/user.rb, config/gov_notify.yml, db/migrate/20190513111153_create_cross_organisation_invitations.rb, db/schema.rb, spec/features/invite_existing_user_spec.rb, spec/features/invite_user_to_join_organisation_spec.rb, spec/features/team/invite_a_team_member_spec.rb, spec/models/cross_organisation_invitation_spec.rb, spec/models/user_spec.rb
Inviting existing users to join other organisations has a different flow to inviting non-existent users.
We don't create a new user, rather just create an invitation for them to join another organisation.
There is no confirmation of invitations yet.
=> Invitations for joining other organisations

app/controllers/application_controller.rb, app/controllers/users/cross_organisation_confirmations_controller.rb, app/models/cross_organisation_invitation.rb, config/routes.rb, db/migrate/20190514101700_add_confirmed_at_to_cross_organisation_invitations.rb, db/schema.rb, spec/factories/cross_organisation_invitation.rb, spec/features/confirm_cross_organisation_invitation_spec.rb, spec/models/cross_organisation_invitation_spec.rb
Allow confirming cross organisation invitations
This endpoint will join the invited user to the invitee's organisation.
Some more edgecase testing required, like dealing with duplicates and
token not found.
=> Confirm invite org

app/models/organisation.rb, db/migrate/20190514130843_remove_uuid_column.rb, db/schema.rb, spec/models/organisation_spec.rb
This PR removes the unused UUID column from the organisations table
=> Remove UUID column from the organisations table

app/models/membership.rb, spec/models/membership_spec.rb
This PR fixes the issue when a user switches organisations and sees two of the same organisations
=> Fix duplicate organisations when switching to another organisation

db/migrate/20190522111050_update_memberships_with_permissions.rb, db/schema.rb
- prepare schema for moving permissions from user to user x organisation
Co-Authored-By: Emile Swarts <emile.swarts@digital.cabinet-office.gov.uk>
Signed-off-by: Paula Valenca <paula.valenca@digital.cabinet-office.gov.uk>
=> Add permissions fields to membership table.

app/models/ip.rb, app/views/ips/_table.html.erb, spec/features/ips/view_ip_addresses_spec.rb, spec/models/ip_spec.rb
https://trello.com/c/axmPZhV7/12-2-improve-the-no-traffic-for-last-10-days-message
- Adds _No traffic received yet_ message for unused Ip records
- Fixes issue with `Ip#inactive?` date comparison
- Rewords _Inactive (no traffic for the last 10 days)_ to _No traffic for the last 10 days_
---
---
=> Improve no traffic message

app/controllers/team_members_controller.rb, spec/features/team/remove_a_team_member_spec.rb, spec/requests/team_members/delete_spec.rb
https://trello.com/c/ztLrtJEj/26-when-removing-a-user-from-a-team-only-delete-membership
The 'through' association between and `Organisation` and a `User` is `Membership`.
Operations to disassociate users from organisations (ie removing a team member)
will now remove the relevant `Membership` record.
=> Remove the membership association between org and user

app/models/organisation.rb, spec/models/organisation_spec.rb
https://trello.com/c/Ds40Fd3O/27-when-deleting-an-organisation-also-delete-all-memberships
When an `Organisation` is removed the associated `Membership` record
will also be destroyed. The `User` record will be left intact.
=> Remove dependent organisation memberships

app/controllers/users/invitations_controller.rb, app/models/membership.rb, spec/features/team/accept_an_invitation_and_sign_up_spec.rb, spec/models/membership_spec.rb
When a user confirms their account, we want to confirm the membership as well.
All users have memberships for all the organisations they belong to, so keep
this consistent.
=> Ensure a membership is confirmed for a new user

app/controllers/users/invitations_controller.rb, spec/features/memberships/invite_user_to_their_first_organisation_spec.rb
Fixes the issue where a new user was receiving both an invitation email based on them being a new user and a membership invitation email based on them being invited to an organisation.
Eventually it would be nice to only have one way of being invited to an organisation. Currently you can either be invited via the `User` (devise, for new users) or via the `Membership` (ours, for existing users). But that can be another PR
=> Fix duplicate email sent on first invite

app/controllers/users/memberships_controller.rb, spec/features/invite_user_to_join_organisation_spec.rb
After confirming an invite, it should log me into the organisation that I just joined
=> Redirect to newly joined organisation on confirmation

app/controllers/organisations_controller.rb, app/controllers/users/confirmations_controller.rb, app/controllers/users/invitations_controller.rb, app/models/user.rb, spec/features/register_an_additional_organisation_spec.rb, spec/features/registration/sign_up_as_an_organisation_spec.rb, spec/models/user_spec.rb
Memberships need to be confirmed when:
- Creating the first organisation for a new user
- Creating a subsequent organisation for an existing user
=> Ensure memberships are confirmed when creating organisations

app/views/admin/organisations/show.html.erb, spec/features/invite_user_to_join_organisation_spec.rb
This PR hides the 'Add team member' button if a super admin does not have the `can_manage_team` permission.
=> Hide 'Add team member' button conditional

app/controllers/application_controller.rb, app/views/application/_subnavigation.html.erb, app/views/help/signed_in.html.erb, app/views/layouts/_google_analytics.html.erb, spec/features/user_with_no_organisation_memberships_spec.rb
https://trello.com/c/0g3MYHja/28-allow-a-orphaned-user-to-login
When a user is no longer associated with any organisation (this is possible if an admin deletes a user's only org) we need to ensure that, once authenticated, they associate themselves with an organisation.
This PR makes sure the orphaned user is redirected to the support form with an additional explanation of why they are there.
=> Redirect users without memberships to orgs

Dockerfile, Makefile, app/controllers/admin/wifi_user_search_controller.rb, app/models/wifi_user.rb, app/views/admin/wifi_user_search/lookup.html.erb, config/database.yml, config/initializers/wifi_user_database.rb, config/routes.rb, docker-compose.yml, mysql_user/Dockerfile, mysql_user/bin/wait_for_mysql, mysql_user/bin/wait_for_wifi_user_db, mysql_user/wifi_user_schema.sql, spec/factories/wifi_users.rb, spec/features/super_admin/lookup_wifi_user_contact_details_spec.rb, spec/models/wifi_user_spec.rb
https://trello.com/c/ydPR0kkx/33-l-allow-gds-super-admin-to-find-user-details-of-a-username-and-vice-versa-7
Allows a super admin to search for users by email, phone number or username and retrieve useful contact information.
Provides a link to search logs for the resulting user.
See https://github.com/alphagov/govwifi-terraform/pull/259 for terraform changes to allow connection to user db.
This search feature doesn't have any navigation yet, we need to decide where it lives.
=> Lookup user contact details from username

app/views/logs_searches/new.html.erb, spec/features/logging/choosing_how_to_filter_spec.rb
Adds link to the new feature worked on by Steve and Paula. Link is for super admins only.
=> Add link for super admins to user details lookup

app/controllers/users/registrations_controller.rb
Replace raw HTML in flash message with call to Rails view helper `link_to` method.
=> Use Rails view context to construct link in flash message

app/views/help/user_support.html.erb
Give admins clearer sense of the support we can provide regarding users connecting to GovWifi in their organisation
=> Update user information support

app/views/help/admin_account.erb
Offer existing admins a clear route to get support for setting up an existing GovWifi installation in their organisation
=> Update support form to filter 'setup GovWifi' tickets

app/views/help/technical_support.html.erb
Offer existing admins a clear route to get support for managing an existing GovWifi installation in their organisation
=> Update support form to filter 'manage GovWifi' tickets

app/controllers/help_controller.rb, app/views/application/_subnavigation.html.erb, app/views/layouts/application.html.erb, config/site.yml
The black top navigation bar for GovWifi has a link titled "Support". Currently, it works in a confusing way:
If you're logged in as an admin, the link is supposed to take you to the **support contact form** (i.e. https://admin.wifi.service.gov.uk/help/new/signed_in). Otherwise, it is supposed to take you to the **product support page** (https://www.wifi.service.gov.uk/support/).
The link works as per the expected flow, except when you're **not** logged in as an admin but on the admin login page where it still takes you to the **support contact form**.
Make the "Support" link on the black top navigation bar always take you to the **product support page**, regardless of whether a user is logged in as an admin or not.
Add a new "Admin Support" link specifically for logged in admins, to the …
=> Add admin support link for logged in admins

app/assets/stylesheets/components/left_nav.scss, app/assets/stylesheets/components/sub_nav.scss, app/views/application/_left_navigation.html.erb, app/views/application/_subnavigation.html.erb, app/views/help/signed_in.html.erb, app/views/layouts/application.html.erb, app/views/memberships/_service_email.html.erb, app/views/memberships/_table.html.erb, app/views/memberships/edit.html.erb, app/views/memberships/index.html.erb, app/views/overview/index.html.erb, app/views/setup_instructions/index.html.erb, app/views/users/invitations/new.html.erb, spec/features/guidance_after_sign_in_spec.rb, spec/features/ips/permissions_spec.rb, spec/features/locations/rotate_radius_secret_key_spec.rb, spec/features/overview/view_overview_page_spec.rb, spec/features/switch_organisation_spec.rb, spec/features/user_with_no_organisation_memberships_spec.rb
This is consistent with what GOV.UK Notify does, and what GOV.UK Pay is moving towards.
Our research has shown it has two main advantages:
- more clearly associates which navigation items are associated with the organisation, and which are about the platform generally
- the vertical arrangement is quicker to scan, so new users can get an idea of what they can do once signed in
This commit also makes a bunch of spacing and style tweaks to generally tidy things up and make them clearer. Sorry I couldn’t split them into cleaner, atomic commits.
=> Move sub navigation to left hand side

db/seeds.rb
In order to make some design changes to the locations page I need to be able to see all the various states of the page. This can be done by adding some more variety to the script that seeds the database.
This pull request:
- adds a user with no locations or IP addresses to show what it’s like when a user first signs up (switch to the _Academy for Social Justice Commissioning_ organisation to see this)
- adds a new, empty location to the existing organisation
- adds a more realistic number of IP addresses per location (based on looking at how many IP addresses real users create)
- creates some of the IP addresses in the past so they don’t all say ‘Available at 6am tomorrow’
Before | After 
---|---
=> Add more realistic seed data

app/views/application/_left_navigation.html.erb
Because the word `memberships` contains the characters `ips` the _IP addresses_ navigation item was being selected when on the team members page.
This adds the leading slash to the matching string to make things a bit more strict and make sure the right navigation item is selected for the right URL.
=> Fix selected state in left hand navigation

app/controllers/super_admin/organisations_controller.rb, app/models/organisation.rb, app/views/super_admin/organisations/index.html.erb, spec/features/super_admin/locations/locations_spec.rb, spec/features/super_admin/organisations/sort_organisation_list_spec.rb, spec/models/organisation_spec.rb
https://trello.com/c/wOXIzpOb/42-make-super-admin-organisations-view-of-organisations-list-sortable-filterable
First part of sorting and filtering by Location and IP count.
=> Sort by Location and IP count

app/controllers/super_admin/organisations_controller.rb, app/models/organisation.rb, app/views/super_admin/organisations/index.html.erb, config/routes.rb, spec/features/super_admin/organisations/view_organisation_list_spec.rb, spec/models/organisation_spec.rb, spec/requests/admin/organisations/get_spec.rb
https://trello.com/c/4iIBUDdC/71-allow-superadmins-to-export-govwifi-organisations-information-as-csv
- Adds a link to export organisations list in CSV format
- Amends service email CSV to include useful fields for use with Notify
=> Export organisations list as csv

app/controllers/users/two_factor_authentication_setup_controller.rb, spec/models/organisation_spec.rb
This helps users identify which service the TOTP code is for
and also includes the Rack environment.
=> Include the issuer in the 2FA QR code

app/assets/stylesheets/components/ip_address.scss, app/assets/stylesheets/components/key.scss, app/assets/stylesheets/components/result_row.scss, app/models/location.rb, app/views/application/_left_navigation.html.erb, app/views/application/_radius_details.html.erb, app/views/ips/_confirm_remove_ip.html.erb, app/views/ips/_ip_address.html.erb, app/views/ips/_table.html.erb, app/views/ips/index.html.erb, app/views/locations/new.erb, spec/features/ips/permissions_spec.rb, spec/features/ips/view_ip_address_readiness_spec.rb, spec/features/ips/view_ip_addresses_spec.rb, spec/features/locations/add_new_location_spec.rb, spec/features/logging/view_auth_requests_for_an_ip_spec.rb, spec/features/overview/view_overview_page_spec.rb
See individual commits for each specific change.
The overall aims of this pull request is to make the locations page clearer by:
- removing redundant information
- changing the prominence of the actions on the page 
- changing the spacing of elements of the page so related things group together more strongly
=> Rationalise the locations page

config/application.rb
There is an issue with `govuk-frontend` and `libsass`[1] (caused by
the min/max macros) so implement the suggested fix on all
environments.
Also see [2] for similar fix.
[1] https://github.com/alphagov/govuk-frontend/issues/1350#issuecomment-493129270
[2]: https://github.com/DFE-Digital/dfe-teachers-payment-service/commit/25403df7409659ff352d28dcc938d0004b01621b
=> config: disable css_compressor

app/models/location.rb, app/views/locations/add_ips.html.erb, spec/features/ips/add_ip_to_existing_location_spec.rb
The error summary should only show if there are IP addresses which couldn’t be persisted. It’s supposed to do this by filtering out blank ones and seeing if there are any left. It was doing the opposite, leaving only the blank ones. In other word the presence of any blank IP addresses (like the 5 we create when you view the page) was causing the error to show.
However this confuses the page if the user hasn’t submitted anything, because the model doesn’t know whether there’s a `GET` or a `POST` going on. So I’ve had to put a bit of logic in the view as well to check which controller method is rendering the page.
=> Fix error summary shown before entering IPs bug

app/controllers/locations_controller.rb, spec/features/ips/add_ip_to_existing_location_spec.rb
We’ve had a couple of users report that changes users have made to their IP addresses haven’t taken effect.
As far as I can tell this line of code sets off a process of re-publishing some kind of configuration file which contains all the IP addresses (see here: https://github.com/alphagov/govwifi-admin/blob/master/lib/use_cases/radius/generate_radius_ip_whitelist.rb#L15-L20). So I’m fairly sure that the reason for the bug is that the process is not being triggered when someone changes or adds an IP address.
This happened because adding the IP addresses used to happen at the same time as adding the location, and the code to publish the changes still lives there.
I’m not sure why this bug wasn’t present before, because the publishing looks like it wasn’t happening in the old `update` …
=> Fix new IP addresses not being published

app/views/layouts/application.html.erb
This adds a footer link to the accessibility statement published as part of this PR: https://github.com/alphagov/govwifi-product-page/pull/218
=> footer: add a link to our accessibility statement

app/controllers/setup_instructions_controller.rb, config/routes.rb, spec/features/download_poster_spec.rb
We need to link to the poster from a public place, but we still only want people who are signed in to be able to download it. So we can’t link to the asset directly.
What we can do instead is add an endpoint which serves the asset but has authentication.
=> Add an authenticated URL to download the poster 

app/controllers/overview_controller.rb, app/views/overview/index.html.erb, spec/features/overview/view_overview_page_spec.rb
We should highlight to organisations if they haven't submitted the MOU, and provide an action item for them to remediate the situation.
Quite often, organisation admins forget about or do not understand the need for signing an MOU. We need to make it more prominent if an org hasn't signed the MOU, and encourage them to sign it.
Add a warning text at the top of the dashboard that warns org admin users, after logging in, that an MOU must be signed, if it hasn't been uploaded yet. The text should include an action item, which the admin user could then click to go to a place where they can download the MOU for signing and upload it back.
---
This is how the warning will look like:
=> Highlight to organisations if MOU has not been signed yet

.rubocop.yml, Gemfile, Gemfile.lock, Guardfile, bin/rspec, bin/spring, ci/tasks/test.yml, spec/rails_helper.rb, spec/spec_helper.rb
Improve the RSpec start time to enable a proper feedback loop, namely by using [Spring](https://github.com/rails/spring) to preload RSpec and not running coverage on every single run.
From the commit log:
Commit 1:
> feature: use rails/spring to preload RSpec
>
> There is probably a lot more to fix for us to achieve near-instant
> boot times, but this is by far the most yielding performance
> improvement across the board. From a quick benchmark using hyperfine:
>
> ```bash
> bash-5.0# hyperfine --warmup=3 -i 'bundle exec rspec spec/empty_spec.rb'
> Benchmark #1: bundle exec rspec spec/empty_spec.rb
>   Time (mean ± σ):     17.861 s ±  2.544 s    [User: 4.104 s, System: 1.943 s]
>   Range (min … max):   12.748 s … 21.520 s    10 runs
> ```
> 
> compare with the new version:
> 
> ```bash
> …
```
=> test: improve RSpec boot time by +400%

app/views/layouts/application.html.erb
This is temporary and will be enabled back once we are ready to roll out
changes to cookie opt-in model in the near future.
=> Disable GA

app/views/organisations/new.html.erb
The page had a two-thirds column inside a two-thirds column inside a three quarters column, resulting in a one-thirds column, which is too narrow.
The commit removes the superfluous two thirds columns, for a normal three quarters-thirds column width on the page.
This gives more space for long email addresses and organisation names, but doesn’t make the measure of the text too long.
Originally attempted in 7d0c9e412317ced431d9ecd31a1638d89999975f
=> Fix the grid on the new organisation page

Gemfile, Gemfile.lock, app/assets/stylesheets/components/team_members.scss, app/controllers/users/two_factor_authentication_setup_controller.rb, app/models/user.rb, app/views/memberships/_table.html.erb, app/views/super_admin/organisations/_team.html.erb, app/views/super_admin/organisations/show.html.erb, app/views/users/two_factor_authentication_setup/edit.html.erb, config/routes.rb, spec/controllers/users/two_factor_authentication_setup_controller_spec.rb, spec/factories/users.rb, spec/features/team/reset_2fa_spec.rb, spec/models/user_spec.rb, spec/rails_helper.rb, spec/support/filters/validate_can_manage_team.rb
This PR adds the functionality to allow org admins and super admins to be able to reset two-factor authentication device for other admin users. 
We already require super admins to login with 2FA, and will soon allow normal admins to do the same. Currently, there isn't a way to reset 2FA device for super admins from the web admin portal, and devs have to do the dirty work of doing this directly on the database! This PR adds the necessary options to the web admin portal, so admins can easily do this themselves (as it should be!). This will become much more important once we roll out 2FA for org admins.
For super admins, a button that resets 2FA has been added next to each member of an organisation, on the organisation detail pages.
For normal admins, a link that resets 2FA has been added …
=> Implement the ability for admins to be able to reset 2FA for others

.dependabot/config.yml
The admin repo has a fair bit of movement and everytime we merge a PR, all pending dependabot PRs will automatically rebase and trigger a PR build on concourse. This can significantly impact build run time when you are regularly pushing on a branch.
So, for the time being, we are only running rebases at 3AM, which should also decrease the number of rebases and jobs triggered.
=> BAU: Run auto rebase for dependabots at night

config/initializers/devise.rb, spec/features/logout_user_after_inactivity_spec.rb
We were allowing session lasting a full hour, which isn't optimal with regards to security. Downgrade back 30 minutes and update the relevant tests.
=> fix: restrict session lifetime to 30 minutes

ci/pipelines/pr.yml
Fixes an error caused by a change to the yml parser used on CI. Similar to alphagov/govwifi-acceptance-tests#25
=> FIX: Move yml anchor declaration above usage

ci/pipelines/pr.yml
Occasionally a concourse PR build job will fail for reasons unrelated with the PR itself (network timeout, for example). This means we usually need to do a workaround of force pushing an "empty" commit to re-trigger the job.
This PR allows for concourse jobs to be triggered via the concourse GUI or via fly by pinning the version
=> BAU - allow manual trigger of PR jobs

app/controllers/active_storage/blobs_controller.rb, app/models/ability.rb, spec/features/upload_download_mous_spec.rb, spec/models/ability_spec.rb
We don't want unauthenticated users to download files so override the ActiveStorage controller to prevent this. See commit and and commit message.
=> fix: don't let unauthenticated users download blobs

spec/features/support/downloads.rb, spec/features/upload_download_mous_spec.rb
Rather than using all sorts of hacks to check our file downloads (due
to the fact that Rails abstracts the underlying storage service and
therefore generates temporal, unique URLs), create an actual matcher
that accepts a Capybara::Session object (i.e the `page` variable) and
an ActiveStorage::Attached attachment to then compare their raw value
through `page.body` and the attachement's `blob.download` method.
=> feat: add a RSpec matcher to make sure Capybara downloads a file

app/controllers/users/two_factor_authentication_setup_controller.rb, app/models/user.rb, app/views/users/two_factor_authentication_setup/show.html.erb, config/locales/en.yml, spec/features/authentication/set_up_two_factor_authentication_spec.rb, spec/features/registration/sign_up_as_an_organisation_spec.rb, spec/features/support/sign_up_helpers.rb, spec/models/user_spec.rb, spec/requests/home/get_spec.rb, spec/requests/ips/delete_spec.rb, spec/requests/locations/delete_spec.rb, spec/requests/users/invitations/create_spec.rb
This will basically present the two factor authentication (2FA) setup screen, as currently shown to super admin users only, to all org admins. At the moment, this is an optional thing, and users can skip setting it up, until next time.
We already require two factory authentication for super admins. This PR extends it to org admins, for better security.
Once org admins log into the admin portal, they will be presented with a screen to setup 2FA, by scanning a QR code - this is how it works for super admins currently and hasn't changed.
However, there is a new option added for skipping the 2FA setup, until next time, if the user isn't ready for this yet.
---
---
=> Make it optional for org admins to be able to setup 2FA

Gemfile.lock
Reverts alphagov/govwifi-admin#957
Tests are failing on concourse; reverting this to unblock the pipeline while I investigate.
=> Revert "build(deps-dev): bump rack-mini-profiler from 1.1.4 to 1.1.6"

Gemfile.lock
Reverts alphagov/govwifi-admin#964
The tests were failing on Concourse and we assumed my merge of PR #957 might be to blame.  We were wrong; the test failures seem to be spurious and transient.  So, we are reverting the revert.
=> Revert "Revert "build(deps-dev): bump rack-mini-profiler from 1.1.4 to 1.1.6""

app/views/layouts/_google_analytics.html.erb
The development environment doesn't have a GA ID, which means the
substitution just ends up as
```js
gtag('config',)
```
which is perfectly valid in JS. However in staging and production, the
GA string isn't quoted so it's interpreted and inevitably crashes.
=> fix: properly quote the GA ID

app/assets/stylesheets/components/team_members.scss, app/views/memberships/_table.html.erb
Styling of (for example) the 'memorandum of understanding' reminder link was broken during implementation of the 2FA reset task (PR 931).
https://trello.com/c/eGfyV8mO/69-fix-broken-styling-of-links-on-admin-portal-estimate-small-1-2-days
=> Fix broken styling on various links

app/controllers/users/invitations_controller.rb, spec/features/super_admin/invite_user_to_organisation_spec.rb
A super-admin may be part of other organisations and try to invite
team members on their own team, going through the normal org flow (as
opposed to the omniscient superadmin one). In that scenario, we can't
assume an organisation ID was passed and need to fallback on the
current organisation.
- pull branch;
- invite member as normal user;
- invite member of a foreign org as super-admin;
- invite member of an org the super-admin belongs-to.
=> fix: let superadmins invite team members to their own team

app/models/user.rb, spec/features/authentication/edit_password_spec.rb, spec/models/user_spec.rb
Password confirmation was not being enforced on the password change screen.
=> Fix: Enforce password confirmation validation

app/views/logs_searches/contact.html.erb, app/views/logs_searches/new.html.erb, app/views/super_admin/whitelists/steps/_fifth.html.erb, app/views/super_admin/whitelists/steps/_fourth.html.erb, app/views/super_admin/whitelists/steps/_sixth.html.erb
Forms created with `form_with` helper got broken (e.g. the logs search feature), ever since jQuery UI library was added (for password strength indicator).
This is because Rails forms created with `form_with` are remote (i.e. AJAX-based) by default. Due to this, when jQuery UI was introduced to the codebase, it also brought with it AJAX event handlers for such forms, which hijack form submissions in order to facilitate JS processing.
In this PR, we explicitly marks forms, which were supposed to be submitted locally (i.e. without AJAX), as local, so that their submission isn't hijacked.
=> Fix the submission of forms created with `form_with`

app/assets/javascripts/application.js.erb, app/assets/javascripts/password_validation.js, app/assets/stylesheets/components/team_members.scss, app/assets/stylesheets/utilities/colours.scss, app/views/users/registrations/edit.html.erb
This PR does the following:
* Fix the bug where jQuery UI had a conflict, which caused AJAX submissions outside of password strength feature to fail
* Improve password strength feedback message format
* Add password score, in order to make it easier for the user to know how much stronger a password needs to be, before being acceptable
* Code tightening and cleanup
Look at commit messages for better context.
The following examples describe the before and after behaviour.
=> Improve password strength feedback

app/assets/javascripts/password_validation.js
This is because, for some weird reason, `status` field had a value of empty string, on production. Due to this flakiness, it's best not to rely on it, and as our existing checks for `score` being a number should suffice. It's also a success event handler anyway, so we should be good in theory.
=> Get rid of `status` check in password validation API response handler (in JS)

app/models/authorised_email_domain.rb, app/models/user.rb, db/migrate/20200803151344_add_uniqueness_index_to_organisation.rb, db/migrate/20200803151856_add_uniqueness_index_to_authorised_email_domain.rb, db/schema.rb, lib/gateways/route53.rb, lib/tasks/repair_migrated_data.rake, spec/gateways/authorised_email_domains_spec.rb, spec/models/organisation_spec.rb, spec/requests/admin/organisations/get_spec.rb, spec/requests/home/get_spec.rb
Fixing these issues allows us to upgrade to the latest GOV.UK Rubocop version
- Added two migrations to add indices to models with uniqueness constraints
- Added a ```dependent: :destroy``` option to the user model to make sure that memberships get destroyed when a user is deleted.
- The indices to the name column of the authorised_email_domain table means that the order of ips returned in the test in authorised_email_domains_spec file is reversed. The order does not seem to matter so that is now reflected in the test
=> Fixed linting issues.

app/models/user.rb, spec/features/authentication/set_up_enhanced_two_factor_authentication_spec.rb, spec/models/user_spec.rb
An email was not sent if:
- a user signs up for email 2fa
- the user successfully 2fa authenticates
- the user signs out
- the user signs back in again
In this case ```user.direct_otp``` would be ```nil``` and the email not set.
This fix ensures that the email is always sent regardless wether
```user.direct_otp``` is set.
The feature tests have been update to simulate successfully authenticating, which is a step that had previously been omitted an which highlights the error.
=> Fixes a bug in which 2fa emails are not sent.

db/migrate/20201020154112_change_default_value_of_second_factor_attempt_count.rb, db/schema.rb
The database column now defaults to 0 instead of null.
https://trello.com/c/sEnMZaaW/451-second-factor-attempt-is-null-by-default-on-admin-database
=> Fix null second factor attempts count bug

ci/tasks/build-deployable.yml, ci/tasks/pre-build.yml, ci/tasks/scripts/pre-build.sh
Add credentials to allow Concourse pipeline tasks to pull images from Docker Hub. Also update build script to include login step.
We need to do this because Docker Hub will introduce rate limiting on 1 November.
paired: @camdesgov & @sarahseewhy
=> Add Docker Hub credentials and login command

app/models/user.rb, app/views/memberships/_table.html.erb, spec/factories/users.rb, spec/models/user_spec.rb
We've previously used `totp_enabled?` to decide if we should display
2fa reset link, however this only checks app 2fa. This method checks both
app and email.
Note, the `reset_2fa!` method on `user` already resets the
`second_factor_method` column, which covers email, so no changes are
required there.
=> Add `has_2fa?` method to `user`, and use in memberships table

package.json, yarn.lock
the newer version of the shared-frontend sets the cookies on the top
domain so this bug should go away with the upgrade.
=> fix: don't show cookie banner multiple times on different pages

app/models/user.rb, spec/models/user_spec.rb
has_2fa? needs to take into account the feature flag, and fall back to
totp_enabled? when off.
Previous fix to allow resetting of Email 2FA had not accounted for the feature flag, so was checking `second_factor_method` which is not currently set in production - this resulted in the *Reset 2FA* option being missing.
=> Fix issue where 2FA can't be reset when enhanced 2fa isn't enabled

app/controllers/help_controller.rb, spec/features/contact_us_when_not_signed_in_spec.rb, spec/features/support/mock_zendesk_client.rb
This can occur when an email address passes the local form validation
but is rejected by Zendesk
Trello: https://trello.com/c/dpv3GGFg/526-handle-malformed-emails-in-our-support-form
=> Rescue Zendesk exceptions when submitting tickets

Dockerfile, config/application.rb, config/environments/production.rb
I suspect this was disabled as a optimisation as it wasn't relevant to
asset compilation, but now we've added the ActiveStorage route it's required.
=> Don't prevent load of ActiveStorage when precompiling assets.

app/controllers/users/invitations_controller.rb
An error occurred where `invited_user` was `nil`. 
I was able to reproduce this by appending `resend=true` to the post data, however I don't think this was the likely cause in 'the field'. In any case, we only want to delete the user account at this point _if it already exists_.
=> Don't attempt to `destroy!` a `nil` record

Dockerfile, app/controllers/active_storage/blobs/redirect_controller.rb, config/application.rb, config/environments/production.rb, config/routes.rb
On updating to Rails/ActiveStorage 6.1, our `ActiveStorage::BlobsController` stopped overriding the default.
I fixed this by renaming it to `ActiveStorage::SecureBlobsController` and referencing it directly in the routes.
As ActiveStorage is disabled when compiling assets, this caused a build failure when deploying to Staging.
I attempted to work around this, but there were further issues.
On further investigation, I identified that `ActiveStorage::BlobsController` had been renamed to `ActiveStorage::Blobs::RedirectController` which is why our custom controller was no longer automatically overriding it.
So, this PR reverts the previous changes to fix it, and implements the new fix, which is to rename our custom file accordingly,.
=> Resolve deploy build issue by applying correct fix.

Gemfile, Gemfile.lock, config/initializers/session_store.rb, db/migrate/20210226140906_add_sessions_table.rb, db/schema.rb
There is a 4kb limit on cookie sessions, which occasionally gets passed causing CookieOverflow exception.
Switching to database storage solves this.
```
ActionDispatch::Cookies::CookieOverflow: ActionDispatch::Cookies::CookieOverflow
actionpack (6.0.3.4) lib/action_dispatch/middleware/cookies.rb:637:in `commit'
actionpack (6.0.3.4) lib/action_dispatch/middleware/cookies.rb:472:in `[]='
actionpack (6.0.3.4) lib/action_dispatch/middleware/session/cookie_store.rb:110:in `set_cookie'
rack (2.2.3) lib/rack/session/abstract/id.rb:403:in `commit_session'
rack (2.2.3) lib/rack/session/abstract/id.rb:268:in `context'
...
(32 additional frame(s) were not displayed)
```
=> Switch to active_record_store for sessions

config/site.yml
We restructured the product pages when we added the text number to them. This is to use the new URLs.
=> Update links to product pages

app/controllers/users/invitations_controller.rb, spec/controllers/users/invitations_controller_spec.rb
The solution to this alert is as the exception suggests - adding `and return` however it is not for the reason suggested.
The intent of this message is that if you have a method:
```ruby
def check_something
if (something)
redirect_to some_path
end
redirect_to some_other_path
end
```
Then both redirects are triggered, causing the error. Adding `and return` to the one in the `if` block solves this.
In our case, there was only one redirect, so this couldn’t be the problem.
In debugging, I noticed that the `authenticate_inviter!` method was being called twice. The second call is from the `current_inviter` method which is called through `has_invitations_left?` at https://github.com/scambra/devise_invitable/blob/cf77519ca9d02c112d99fd176a8852272c1b8d99/app/controllers/devise/invitations_controll …
=> Prevent double render error when calling invitation `create` when not logged in

Gemfile, Gemfile.lock, config/initializers/devise_safe_store_location.rb, config/initializers/session_store.rb, db/migrate/20210322122355_drop_sessions_table.rb, db/schema.rb, spec/requests/large_request_spec.rb
As we've now established the cause of the large cookies leading to the cookie overflow error, we can now revert the switch to ActiveRecord storage.
We now check the length of the requested URL, and if it is more than 1/2 of the cookie storage available (4096) then the URL is not stored for redirection.
=> Revert session to cookies and handle overflow

spec/spec_helper.rb
the GOVERNMENT_ORGS and LOCAL_AUTHORITIES constants were redefined
in the spec_helper, causing a lot of warnings to appear.
The correct way to redefine them is by using stub_const which
supresses the warnings
=> Use stub_const to redefine constants in specs

app/controllers/users/two_factor_authentication_setup_controller.rb, app/controllers/users/two_factor_authentication_unable_controller.rb, app/views/users/two_factor_authentication_setup/show.html.erb, app/views/users/two_factor_authentication_unable/show.html.erb, config/locales/en.yml, config/routes.rb, spec/features/authentication/set_up_two_factor_authentication_spec.rb
Currently non-superadmins can skip setting up 2fa but that is
going to disappear soon. This commit adds a warning page that this
is happening and a link where users can get help.
Trello: https://trello.com/c/jCZwXfk6/1149-change-admin-site-to-warn-of-two-factor-authentication-changes
=> Add a warning page that 2fa is going to be mandatory soon.

app/views/super_admin/whitelists/organisation_names/index.html.erb, app/views/users/confirmations/new.html.erb, app/views/users/invitations/new.html.erb, app/views/users/passwords/edit.html.erb, app/views/users/passwords/new.html.erb, app/views/users/registrations/new.html.erb, app/views/users/sessions/new.html.erb, app/views/users/two_factor_authentication/_show_app.html.erb, app/views/users/two_factor_authentication/show.html.erb, app/views/users/two_factor_authentication_setup/show.html.erb
Remove `autofocus` attribute from form fields
Autofocus is frowned upon for accessibility purposes, as "users would expect to navigate the page in reading order, from top to bottom and left to right."
=> Remove `autofocus` attribute from form fields

app/views/ips/index.html.erb, app/views/super_admin/locations/index.html.erb, app/views/super_admin/organisations/index.html.erb
Implement `aria-role="status"` on "no results" messages.
Screen readers don't automatically know to read the no results message when searching. This adds the hint that it's relevant content.
Based on [this](https://www.davidmacd.com/blog/test-aria-live-display-none.html) the role needs to be on a containing element, as it relates to the inner content, so setting it on the `p` that's being shown/hidden wouldn't have an effect.
=> Wrap the "no results" messages in `aria-role="status"`

app/assets/stylesheets/components/sub_nav.scss, app/views/layouts/application.html.erb
The line under the heading was implemented with an `hr` tag. Remove it.
`hr` now has semantic meaning - "paragraph-level thematic break" - this doesn't make sense under the heading and the same appearance can be easily achieved with CSS.
=> Remove `hr` under main heading.

app/views/ips/_confirm_remove_ip.html.erb, app/views/ips/_confirm_rotate_radius_key.html.erb, app/views/ips/_table.html.erb, app/views/super_admin/whitelists/steps/_sixth.html.erb
1. Move table caption content outside of table
2. Add headers to table rows
1. Caption should be used as just that - our captions had heading, radius key, option to rotate, delete location button.
2. Some tables had rows with `label: value` - `label` in that context should be a `th`
=> Accessibility:  information and relationships fixes

app/views/ips/_confirm_remove_ip.html.erb, app/views/ips/_confirm_remove_location.html.erb, app/views/ips/_confirm_rotate_radius_key.html.erb, app/views/ips/index.html.erb, app/views/layouts/_flash_notices.html.erb, app/views/layouts/_form_errors.html.erb, app/views/locations/add_ips.html.erb, app/views/locations/new.erb, app/views/memberships/_confirm_remove_team_member.html.erb, app/views/organisations/edit.html.erb, app/views/super_admin/locations/index.html.erb, app/views/super_admin/organisations/_confirm_remove_organisation.html.erb, app/views/super_admin/whitelists/email_domains/_confirm_remove_email_domain.html.erb, app/views/super_admin/whitelists/organisation_names/_confirm_remove_custom_organisation.html.erb, app/views/users/invitations/edit.html.erb, app/views/users/two_factor_authentication/edit.html.erb, spec/features/registration/sign_up_as_an_organisation_spec.rb
* Update form errors template to repeat errors and link to fields
* Use form errors template where previously not used
* Set "Error: " prefix on page title within form errors template
* Repeat on Add IPs as this has custom errors
Because the DAC Doc says so.
The implementation of the links in the top errors is a bit of a hack - Devise just isn't designed to do that, but this works pretty well. 
Additionally adding the "Error: " prefix to the page titles is a similar hack. [In the top error template](https://github.com/alphagov/govwifi-admin/pull/1312/files#diff-66b69dc0610365d039ef8e12646a3e263511ec7e3deffec7914747225c6318b4R2) If we're displaying the errors, then we also take the previously set page title and add the prefix there.
=> DAC Validation Pattern fixes

app/views/ips/_confirm_remove_ip.html.erb, app/views/ips/_confirm_remove_location.html.erb, app/views/ips/_confirm_rotate_radius_key.html.erb, app/views/memberships/_confirm_remove_team_member.html.erb, app/views/users/two_factor_authentication/edit.html.erb
Add action titles... e.g. when you click "Remove Location" and you get a confirmation dialog, now the title changes to indicate the action
So that the page is more accessible.
=> Add action prefixes to page titles.

config/locales/devise.en.yml
When you sign in and complete 2FA, there's a message telling you it's been set up successfully. Remove it.
[](url)
There's already the [same message, defined separately](https://github.com/alphagov/govwifi-admin/blob/343ae2a5f039604072afff4e630402ffe6f365ac/app/controllers/users/two_factor_authentication_setup_controller.rb#L16) when you do _set up_ 2FA. Having the same message when you sign in is incorrect - it would correctly say "you have successfully signed in" however this is superfluous.
=> Remove the success message on 2fa authentication

app/views/users/two_factor_authentication/show.html.erb
Updates the copy for the heading & hint, and links them to the input field with `label` and `aria-describedby`
The page does not say where the 6 digit code will come from and some people are thinking it will be via SMS
Accessibility fix
=> Update heading/hint, and add help for resetting 2FA

app/views/users/two_factor_authentication/show.html.erb
* Change button "Authenticate" to "Continue"
* add `govuk-link` class to the email link
Because these were missed on earlier PR
=> Correct the button text. Add class to link, to style it as link.

config/application.rb
Set the config to skip the IP spoofing check
There are lots of false positives for this, due to proxies we have no control over. As it's not a big risk for us, the solution is to just disable the check.
=> Disable the IP spoofing check that's being problematic with proxies.

config/initializers/devise.rb, spec/features/authentication/reset_password_spec.rb
After resetting a password, immediately sign the user out.
Otherwise the user can skip 2FA
Link to Trello card (if applicable): https://trello.com/c/StEsu73m/1417-bugfix-forgot-password-reset-process-logs-the-user-in-without-completing-2fa
=> After resetting a password, immediately sign the user out.

app/views/ips/index.html.erb, app/views/super_admin/locations/index.html.erb, app/views/super_admin/organisations/index.html.erb
Add labels to search fields that are only "labelled" with placeholder. Remove placeholders.
Labels are required for accessibility. Raised in DAC report. Adding a submit button doesn't really work, so have added aria-live instead.
> Users were not presented instructions or labels to identify the controls in a form and
> describe what input data is expected. Placeholder text has been used as the only visible
> labelling technique. Those with cognitive, language, and learning disabilities may find labels
> help them to enter information correctly. Labels may also help to prevent users from
> making submission errors. For voice activation users, visible labels can be used to indicate
> the accessible name by which this component may be referenced to assistive technology.
> Otherwise, users …
=> Replace placeholders with labels, and add `aria-live` to results region

.erb-lint.yml
Use the correct namespace for LineLength Rubocop rule
It was wrong
Link to Trello card (if applicable): https://trello.com/c/qyOF6wLc
=> Correct LineLength rule (should be within Layout)

Gemfile.lock, app/views/ips/index.html.erb, app/views/super_admin/locations/index.html.erb, app/views/super_admin/organisations/index.html.erb
search fields.
* Update erb_lint to `0.1.1` - dependabot had tried to update to `0.1.0` but further changes were required to allow linter to pass.
* Set `autocomplete="off"` on search inputs. These forms are never actually submitted as it's live filtering, so the browser won't have any sensible input to autofill anyway.
Updates are good. Changing code to comply with new linter rule.
Link to Trello card (if applicable): https://trello.com/c/iAR5MpSz
=> Update erb_lint to `0.1.1` and add required `autocomplete` attribute to

app/views/logs/index.html.erb, lib/gateways/sessions.rb, mysql/rr_schema.sql, spec/features/logging/view_logs_spec.rb, spec/gateways/sessions_spec.rb
Recently the Logging API has started recording the Radius server task ARN for
each request so it can now be included in the log table.
It can be useful to know which request has been served by which Radius server
so that potential problems can be diagnosed.
Link to Trello card (if applicable): https://trello.com/c/htMbaqCQ/1469-show-which-radius-server-was-used-to-serve-a-request-in-the-admin-portal2
=> Display the Radius server in the logs for super admins.

app/views/memberships/_table.html.erb, app/views/setup_instructions/_organisation.html.erb, app/views/shared/_manage_ips.html.erb, app/views/super_admin/organisations/_team.html.erb
Add visually hidden text to make links with identical text clearer for screen readers. e.g. Add IP addresses [for {location}]
Screen readers can list all links on a page... if the text of the link is repeated, it can be unclear what it will do.
Link to Trello card (if applicable): https://trello.com/c/isClWtzI
=> add hidden text for screen readers

app/models/ip.rb, app/models/session.rb, app/views/shared/_manage_ips.html.erb, db/seeds.rb, spec/features/ips/view_ip_addresses_spec.rb, spec/models/ip_spec.rb
We want to display the rate of successful vs unsuccessful requests for an IP address
As an admin, I want to be able to see quickly if an IP address has a high error rate so I can take
action if something is misconfigured.
https://trello.com/c/4SN3SpTB/1488-show-successful-failed-requests-in-the-last-hour-in-admin-portal2
Added the "71% success rate" column in the screenshot below
=> Display the success rate of requests per IP in the last day

db/migrate/20210813083000_eliminate_null_postcodes.rb
Adds a migration to set a non-NULL constraint on the postcode column of the locations table and changes any existing NULL values to an empty string.
Where organisations have created a location without a valid postcode (which the app no longer allows), IP addresses could not be added as this triggers a location validation.
https://trello.com/c/nfH54Zzk/1495-enforce-database-rules-to-prevent-things-like-null-postcode-in-the-ui
=> Eliminate NULL postcodes in locations table

app/views/ips/index.html.erb, app/views/memberships/index.html.erb, app/views/shared/_manage_ips.html.erb, app/views/super_admin/organisations/show.html.erb, app/views/super_admin/whitelists/email_domains/index.html.erb, app/views/super_admin/whitelists/steps/_first.html.erb, app/views/super_admin/whitelists/steps/_second.html.erb, app/views/super_admin/whitelists/steps/_third.html.erb, app/views/users/two_factor_authentication_unable/show.html.erb
Add role, draggable, and data-module attributes to links styled as buttons.
As they're styled as buttons they should also behave like buttons, so as not to confuse the user.
Link to Trello card (if applicable): https://trello.com/c/SLDfWeAe
=> Make link buttons behave like buttons

app/views/memberships/_table.html.erb, spec/features/team/view_team_members_spec.rb
- add a Permissions heading to explain the list
- add role=list so Voiceover treats it as a list
- make image alt blank and use hidden text instead on recommendation in the audit
- Changes 'allowed' to 'can' and 'not allowed' to 'cannot' so for example 'Can view team members'
From the audit:
> Users did not understand the purpose of the allowed/ not allowed images and assumed them to be decorative. This may be because the fact that these are presented to users as ‘images’ obscures the primary purpose of the information they are delivering.
Screen reader user comments:
>“When navigating in context, I located a multitude of images on the page described as ‘Allowed’. It seems that these images are present for decorative purposes, therefore providing no benefit to a screen reader user.”
When …
=> Make permissions more accessible

ci/pipelines/pr.yml
Set a higher max in flight threshold for the Concourse pipeline
So that Concourse can process multiple Pull Requests at once. This is
helpful when there are lots of Dependabot Pull Requests open.
=> Set a higher max in flight threshold for the Concourse pipeline

lib/gateways/orphan_users.rb, lib/tasks/delete_orphans.rake, spec/gateways/orphan_users_spec.rb
Delete users that aren't associated with an organisation and are older than a week.
When a user is removed from an organisation, and that is the last organisation they are a member of, their user record is also deleted. There appear to be historical users where this has not happened - possibly prior to a code fix.
Additionally, it seems some users who intend to sign up for an end-user account, mistakenly sign up for an admin account instead. As they never create an organisation (presumably due to realising they've made a mistake) their user record remains and can pollute stats (e.g. on 2FA uptake).
Link to Trello card (if applicable): https://trello.com/c/M13twt1f
=> Delete orphan users older than a week

app/models/ip.rb, app/models/session.rb
Force the use of the sessions_start_username index in session calc
Mysql uses the SiteIP index instead of the much faster sessions_start_username
index when calculating the number of sessions for an IP address.
This change forces the use of this index.
In future we may add a new index which could speed things up
even more if necessary
Link to Trello card (if applicable): https://trello.com/c/QMqQGD6i/1545-handle-504-when-accessing-hmctss-page-in-the-super-admin-site
=> Force the use of the sessions_start_username index in session calc

app/models/ip.rb, app/models/session.rb
Reverts alphagov/govwifi-admin#1393
This is a good idea on MySQL 8 but not so on MySQL 5 where the query planner chooses the
correct index.
This PR will also interfere when we add a new index to solve the problem this PR was trying to
address
=> Revert "Force the use of the sessions_start_username index in session calc"

db/seeds.rb
Limit username to 6 characters
Because the database field is only 6 characters long. It sometimes
throws an error using Faker. It also more accurately reflects
the type of usernames we use.
https://trello.com/c/Ri0gKF0S/1558-prevent-faker-from-generating-long-names-causing-mysql-errors-when-building-govwifi-admin
=> Limit username to 6 characters

app/assets/stylesheets/components/header.scss, app/views/shared/_header.html.erb, spec/features/common/header_spec.rb
On non-production systems, the header border, and label tag are yellow, and the tag is named for the environment rather than "beta"
Note, I've made the border the "full" yellow, rather than the pastel to match the tag, as it reduces its visibility against the white.
We want to be able to see at a glance which environment we're in, and specifically know when we're on production, to avoid making any breaking changes to live data.
Link to Trello card (if applicable): https://trello.com/c/oXE4L3F0
=> Use different header/label when on non-production

app/models/location.rb, spec/models/location_spec.rb
Only display one validation message for postcode (blank or valid)
When you don't enter a postcode, both validations fire, but it's only really relevant that you haven't entered it.
=> Only validate postcode on pattern if not blank

db/migrate/20210915111502_drop_permissions_table.rb, db/schema.rb
Drop the `permissions` table
It's no longer used, and is messy.
Link to Trello card (if applicable): https://trello.com/c/qkwhsASY
=> Drop the permissions table as it's unused

app/controllers/ips_controller.rb, app/views/ips/index.html.erb, spec/features/ips/search_locations_spec.rb
The search box to find a location on postcode was broken when the paging feature was introduced. 
This feature used to depend on Javascript
and would only work on locations that were displayed on the current page.
This commit now enables search without javascript by loading a new page
from the server.
This also ensures that the search functionality works even though Javascript is disabled.
Link to Trello card (if applicable): https://trello.com/c/BV9KYkX5/1605-fix-search-functionality-for-locations-in-admin-portal
=> Fix search in the locations view.

app/views/ips/index.html.erb
Persist value in the locations search box
It didn't persist and so if you search for something it disappears and you can't see what it was you searched for.
=> Persist value in the locations search box

config/environments/staging.rb
Update default staging URL to point to `staging-temp`.
* The staging components in the primary AWS account have been decommissioned therefore there is no more URL for `admin.staging.wifi.service.gov.uk`.
* We need to point to the URL for our secondary AWS account where staging components now run.
* This fixes broken email links generated when inviting a new user to Staging Admin site, they were pointing to the decommissioned `admin.staging.wifi.service.gov.uk` URL.
=> Update default staging url

app/models/organisation.rb, spec/models/organisation_spec.rb
Removed user input from an error message in the Organisation model
Error messages are not escaped and so we should not include unescaped
user input in error messages as this runs the risk of introducing a reflected
XSS vulnerability
https://trello.com/c/Sft4bDMo/1824-sanitise-error-messages-in-admin-portal
=> Fix ITHC weakness with reflected user input

Dockerfile, config/application.rb, config/environments/production.rb
This was introduced to get around the fact that activestorage
requires the secret key base to be set
This no longer works because in config/initializers/activestorage.rb
explicit references are made to the ActiveStorage module.
An easier fix is to set the SECRET_KEY_BASE to a random string
when compiling assets
This also ensures production and staging are more alike
(see https://github.com/alphagov/govwifi-admin/pull/186#discussion_r224438529)
=> Remove ASSET_PRECOMPILATION_ONLY references.

app/controllers/application_controller.rb
The protect_from_forgery action needs to be the first in the sequence
of before_action handlers otherwise the exception
'ActionController::InvalidAuthenticityToken' is thrown,
=> Fix the CSRF protection

config/application.rb, config/environments/development.rb, config/environments/staging.rb
Because the feature is live and this is no longer used
=> Remove enable_enhanced_2fa_experience feature flag

app/controllers/concerns/able_to_read_mou.rb, app/controllers/settings_controller.rb, app/mailers/authentication_mailer.rb, config/application.rb, config/initializers/active_storage.rb, lib/facades/ips/publish.rb, lib/gateways/email_gateway.rb, lib/use_cases/organisation/view_radius_ip_addresses.rb, lib/use_cases/radius/publish_whitelist.rb, spec/facades/ips/publish_spec.rb, spec/gateways/email_gateway_spec.rb, spec/use_cases/organisation/view_radius_ip_addresses_spec.rb, spec/use_cases/publish_whitelist_spec.rb
We are using the classic rails autoloader and this PR makes the switch to the newer Zeitwerk one
Zeitwerk is the new Classloader for Rails. The classic version will soon be deprecated when Rails 7 is released. Furthermore it is good to follow the new class/module naming convention
https://trello.com/c/gQXR8Usc/1241-switch-to-zeitwerk-autoloader
=> Switch to the Zeitwerk class loader

app/controllers/organisations_controller.rb, app/views/organisations/new.html.erb, spec/features/register_an_additional_organisation_spec.rb
Prevents the side-bar menu from displaying when an email field error occurs, changes instances of 'register organisation' and 'create organisation' to 'add organisation' and adds a 'Cancel' (back) link.
To make the page display consistently in the case of all error types, use language consistently and match the design prototype
https://trello.com/c/KvrKdbSM/1946-make-display-of-navigation-sidebar-consistent-between-the-default-register-organisation-page-and-the-page-displayed-in-case-of-i
=> Make side bar menu display consistently

app/views/organisations/new.html.erb, app/views/shared/_organisation_register_dropdown.html.erb, spec/features/register_an_additional_organisation_spec.rb
Ensure error messages display as intended on 'register new org' admin page
When leaving the organisation empty, a design-system compliant error message
is now shown. Value are now also retained if the input is not valid
https://trello.com/c/coP1mjaU/1951-ensure-error-messages-display-as-intended-on-register-new-org-admin-page
=> Error messages on the 'register new org' pages are design system compliant

.github/dependabot.yml
Remove old ignore things from the dependabot.yml
Most of these are dependency versions that have now been passed, I
don't see any value in keeping this in the config file.
=> Remove old ignore things from the dependabot.yml

app/views/shared/_header.html.erb
Remove links to ''connect to GovWifi'' and ''Offer GovWifi'' as these
are separate product page functions and not admin functions.
This simplifies the admin user experience and creates further distinction between product pages and admin specific pages
https://trello.com/c/sr564a5z/2031-admin-site-header
=> Remove links from the header

app/helpers/application_helper.rb, app/views/users/registrations/edit.html.erb, spec/features/authentication/edit_password_spec.rb
Improve error display on the change password form.
This makes the form easier to use.
Link to Trello card: https://trello.com/c/CwZ50yCx/1950-make-error-messages-produced-by-devise-gem-design-system-compliant
=> Improve edit password form

app/controllers/users/registrations_controller.rb, app/views/users/invitations/new.html.erb, app/views/users/registrations/new.html.erb, config/locales/en.yml, spec/features/registration/sign_up_as_an_organisation_spec.rb, spec/features/support/sign_up_helpers.rb, spec/features/team/invite_a_team_member_spec.rb
Start using the form builder gem for a couple more forms
This is mostly aimed at adjusting the error messages shown by the
invite team member form. Since there's some overlap with validation
for the sign up form, I've ended up changing that as well.
Using the form builder gem means that the error messages don't all
start with the name of the field, which makes the format less
constrained.
I haven't changed the invite team member form checkboxes to be
generated through the gem provided helpers since I believe this part
of the form is changing shortly.
Link to Trello card: https://trello.com/c/CwZ50yCx/1950-make-error-messages-produced-by-devise-gem-design-system-compliant
=> Start using the form builder gem for a couple more forms

app/views/ips/index.html.erb, app/views/shared/_manage_ips.html.erb, spec/features/ips/remove_an_ip_spec.rb, spec/features/ips/view_ip_address_readiness_spec.rb, spec/features/ips/view_ip_addresses_spec.rb, spec/features/locations/remove_a_location_spec.rb, spec/features/logging/view_auth_requests_for_an_ip_spec.rb
Represent 'Rotate key' and 'Remove Location' links as buttons as they are actions
Present the 'view logs' and 'remove ip' links in a list for each IP address
Use insets for messaging
Make various changes to make the layout more design system compliant
This will make the locations page simpler and more compliant with the GOV.UK design system
https://trello.com/c/DcaU32qu/2058-simplify-location-page-building-actions
https://trello.com/c/Wtrfd94o/1261-simplify-location-page-ip-address-actions
=> Simplify Location Page

Gemfile, Gemfile.lock
Add more mail related gems to the Gemfile
net-smtp was added when upgrading to Ruby 3.1.1, as the tests failed
without it. This wasn't sufficient though to get the app running in
the production Rails environment though, since eager loading is enable
there, and the mail gem also tries to require net/imap and net/pop.
I think there's something wrong with how ActionMailer is being handled
here, as I'm not aware that the app actually uses the mail gem, let
alone SMTP, POP or IMAP, I think GOV.UK Notify is used for all the
sending of emails.
Anyway, as a quick fix, just include more gems in the Gemfile.
=> Add more mail related gems to the Gemfile

app/views/layouts/application.html.erb, package.json, yarn.lock
Bump `govuk-frontend` from 3.14.0 to 4.0.1. Resolves this dependabot PR (#1555). Bumping the version required some minor tweaks (see commit history).
I _highly_ recommend reviewers also look at the [`govuk-frontend` change log](https://github.com/alphagov/govuk-frontend/blob/main/CHANGELOG.md). As part of this PR I went point by point to double check we won't be impacted by the breaking changes but I might have missed something.
Keeping up to date with third-party libraries reduces the risk for future errors and vulnerabilities.
Link to Trello card (if applicable): https://trello.com/c/LBxSFWom/2048-bump-govuk-frontend-from-3140-to-401-in-govwifi-admin
=> Bump `govuk-frontend` from 3.14.0 to 4.0.1

app/models/organisation.rb, db/migrate/20220310094230_remove_super_admin_from_organisation.rb, db/schema.rb, spec/models/organisation_spec.rb
Remove the super_admin field from organisations
This is now managed at the user level, rather than through association
with a super_admin organisation.
Link to Trello card: https://trello.com/c/08QFeITR/2093-admin-site-migrate-from-super-admin-organisations-to-individual-super-admins-5
=> Remove the super_admin field from organisations

db/seeds.rb
Update the seeds.rb for the super admin organisation removal
This should have happened in be684b6b66bd4370508da8d1566b16a568b89287,
but was missed.
=> Update the seeds.rb for the super admin organisation removal

app/assets/stylesheets/application.scss, app/controllers/memberships_controller.rb, app/controllers/users/invitations_controller.rb, app/models/membership.rb, app/views/memberships/_table.html.erb, app/views/memberships/edit.html.erb, app/views/memberships/index.html.erb, app/views/users/invitations/new.html.erb, spec/features/logout_user_after_inactivity_spec.rb, spec/features/pending_user_spec.rb, spec/features/super_admin/invite_user_to_organisation_spec.rb, spec/features/team/edit_permissions_spec.rb, spec/features/team/invite_with_permissions_spec.rb, spec/features/team/permissions_spec.rb, spec/features/team/view_team_members_spec.rb
Change the designs for 3 pages related to team members within an organisation.
The new design is simpler, which is better for users.
Link to Trello card: https://trello.com/c/qGBxPnU0/2087-changes-to-invite-team-member-and-edit-team-member-page-2 and https://trello.com/c/Xs1ICSKc/2086-display-admin-users-and-their-roles-in-table-1
=> Change team member related page designs

app/assets/stylesheets/components/left_nav.scss
Add left-side border to active menu item in navigation side-bar
Make it clearer which page the user is currently on and make
compliant with design system
https://trello.com/c/gm1r5gXK/1948-update-admin-side-navigation
=> Add left-side border to active menu item in navigation side-bar

app/controllers/application_controller.rb, app/controllers/concerns/gov_wifi_authenticatable.rb, app/controllers/help_controller.rb, app/controllers/home_controller.rb, app/controllers/logs_controller.rb, app/controllers/logs_searches_controller.rb, app/controllers/memberships_controller.rb, app/controllers/super_admin_controller.rb, spec/factories/locations.rb, spec/factories/users.rb, spec/features/authentication/reset_password_spec.rb, spec/features/authentication/set_up_two_factor_authentication_spec.rb, spec/features/logging/view_logs_spec.rb, spec/features/super_admin/logging/view_logs_for_ip_spec.rb, spec/features/super_admin/logging/view_logs_for_username_spec.rb, spec/features/super_admin/lookup_wifi_user_contact_details_spec.rb, spec/features/super_admin/organisations/sort_organisation_list_spec.rb, spec/features/super_admin/organisations/view_organisation_list_spec.rb, spec/features/super_admin/upload_download_mou_spec.rb, spec/features/team/reset_2fa_spec.rb, spec/features/user_with_no_organisation_memberships_spec.rb
The logic redirecting users when they are not part of an organisation needs to be improved. Currently, some useful pages, such as logging, cannot be accessed by a super admin that is not part of an organisations. 
We want to remove the requirement that a super admin has to be a member of an organisation. Only those pages that are specifically scoped to an org should disallow users without organisations.
To be created
=> Update no organisation redirect

app/views/users/invitations/new.html.erb, spec/features/super_admin/invite_user_to_organisation_spec.rb
Tweak the back link on the invite a team member page
So that it's by the button at the bottom. This should be easier for
users to see.
The behaviour here is still not great, since the button does different
things for super admins, but that should be fixable in the future.
Link to Trello card: https://trello.com/c/qGBxPnU0/2087-changes-to-invite-team-member-and-edit-team-member-page-2
=> Tweak the back link on the invite a team member page

app/views/locations/new.erb, spec/features/locations/add_new_location_spec.rb
Replace 'back to list' breadcrumb with 'Cancel' link
More clearly represents the navigation which takes place
when clicking on the link, and generally easier to see.
https://trello.com/c/1DbWYmzf/2085-improve-the-ui-of-the-add-location-page-through-rewording-buttons-1
=> Replace 'back to list' breadcrumb with 'Cancel' link

db/migrate/20220316111522_change_membership_permissions_to_not_null.rb, db/migrate/20220316112023_change_membership_can_manage_locations.rb, db/schema.rb
Remove the NULLs from the membership permissions and set `can_manage_locations` to true where `can_manage_team` is true. 
So that the NULLs aren't confusing, and the values for these two fields match up with the 3 permission levels.
Link to Trello card: https://trello.com/c/qGBxPnU0/2087-changes-to-invite-team-member-and-edit-team-member-page-2
=> Improve membership permissions

app/controllers/ips_controller.rb, app/controllers/locations_controller.rb, app/views/shared/_manage_ips.html.erb, app/views/super_admin/organisations/_ips.html.erb, config/routes.rb, spec/controllers/locations_controller_spec.rb, spec/features/ips/add_ip_to_existing_location_spec.rb, spec/features/ips/remove_an_ip_spec.rb, spec/features/locations/add_new_location_spec.rb, spec/features/locations/remove_a_location_spec.rb
There were a lot of routes that all point to the same ips#index action. This
is confusing because the associated paths imply different actions exist whereas
in fact they are all synonyms.
Removing these makes the flow within the application clearer and shortens
the route table
=> Remove superfluous ips#index routes

app/controllers/memberships_controller.rb, app/controllers/mou_controller.rb, app/controllers/users/invitations_controller.rb, config/routes.rb, spec/features/team/edit_permissions_spec.rb, spec/features/team/invite_a_team_member_spec.rb, spec/features/team/remove_a_team_member_spec.rb, spec/features/upload_download_mous_spec.rb
There were a lot of routes that all point to the the same action. This
is confusing because the associated paths imply different actions exist whereas
in fact they are all synonyms.
Removing these makes the flow within the application clearer and shortens
the route table
=> Remove superfluous memberships#index and mou#index routes

app/views/help/signed_in.html.erb, app/views/super_admin/wifi_user_searches/show.html.erb, config/routes.rb, spec/features/super_admin/lookup_wifi_user_contact_details_spec.rb
1. There are a number of superfluous routes that can now be removed
2. The username link in the userdetails view now point to the right page
3. A link in the help page now points correctly to the logging page
=> Implement several small fixes for the recent logging changes.

app/controllers/locations_controller.rb, app/models/location.rb, app/models/location_ips_form.rb, app/views/locations/add_ips.html.erb, spec/controllers/locations_controller_spec.rb, spec/features/ips/add_ip_to_existing_location_spec.rb, spec/features/ips/view_ip_address_readiness_spec.rb, spec/features/track_new_organisations_spec.rb, spec/models/location_spec.rb
Use GOV.UK form builder for the UI to add IPs to a Location
The GOV.UK form builder provides simpler view code. The previous approach
of using 'field_for' has been replaced by a form model which is more
straight-forward, and requires less code in the controller, view and model
and is compatible with the form builder.
=> Use GOV.UK form builder for the UI to add IPs to a Location

app/controllers/users/two_factor_authentication_controller.rb, app/controllers/users/two_factor_authentication_setup_controller.rb
Do no show subnav and sidebar for 2FA views.
None of the links in the subnav or sidebar work until 2FA authentication is completed and so showing them introduces unnecessary clutter and can confuse users
berfore:
after:
https://trello.com/c/xzsViBpP/1394-do-not-show-links-during-2fa
=> Do no show subnav and sidebar for 2FA views.

app/views/help/signed_in.html.erb, config/site.yml
Change page contents to match updated design
So that it is more consistent with the design system.
https://trello.com/c/zOmwfje7/2119-changes-to-support-page
=> Change page contents to match updated design

app/views/settings/_account.html.erb, app/views/settings/_organisation.html.erb, app/views/settings/_servers.html.erb, spec/features/authentication/edit_password_spec.rb
Make settings page consistent with new design
Change the layout of the page. Retains the basic page structure (tables)
rather than using divs/dls as per the prototype.
https://trello.com/c/dQVU1o17/2118-changes-to-the-setting-page-1
=> Make settings page consistent with new design

Gemfile.lock, app/controllers/users/two_factor_authentication_setup_controller.rb, spec/features/authentication/set_up_two_factor_authentication_spec.rb
Allow users to only set up 2FA once.
Users were able to overwrite 2FA by manually visiting the 2FA setup page.
https://trello.com/c/9rkusm1t/2214-it-health-check-high-risk-mfa-bypass
=> Allow users to only set up 2FA once.

.secrets.baseline, app/models/organisation.rb, app/views/organisations/edit.html.erb, config/application.rb, config/locales/en.yml, spec/features/registration/sign_up_as_an_organisation_spec.rb
Use the govuk form builder for organisation#edit view
Simplifies the code, benefit from automatic updates
=> Use the govuk form builder for organisation#edit view

app/controllers/memberships_controller.rb, app/models/membership.rb, app/views/memberships/edit.html.erb
Update permissions form with GOV.UK form builder
So that the form is in line with the design system and contains simpler view code
=> Update permissions form with GOV.UK form builder

Dockerfile
Switch to using puma directly in the Dockerfile
As this allows passing options like --threads, to increase the number
of threads being run.
Currently there are only a maximum of 5 threads being run, which leads
to poor utilisation of the tasks in ECS.
=> Switch to using puma directly in the Dockerfile

app/controllers/users/confirmations_controller.rb, app/models/organisation.rb, app/models/user.rb, app/models/user_membership_form.rb, app/views/shared/_organisation_register_dropdown.html.erb, app/views/super_admin/whitelists/organisation_names/index.html.erb, app/views/super_admin/whitelists/steps/_third.html.erb, app/views/users/confirmations/new.html.erb, app/views/users/confirmations/show.html.erb, config/locales/en.yml, spec/features/registration/resend_confirmation_instructions_spec.rb, spec/features/registration/sign_up_as_an_organisation_spec.rb, spec/models/user_membership_form_spec.rb
Update confirmations#new and confirmations#show to use GOV.UK form builder
This simplifies code, ensures the frontend and error messages are consistent
=> Update confirmations#new and confirmations#show to use GOV.UK form builder

app/views/users/registrations/edit.html.erb, config/locales/en.yml, spec/features/authentication/edit_password_spec.rb
Update password edit form to use GOV.UK form builder
This simplifies code, ensures the frontend and error messages are consistent
=> Update password edit form to use GOV.UK form builder

app/controllers/organisations_controller.rb, app/views/organisations/new.html.erb
Update organisations#new views to use GOV.UK form builder
It simplifies code, ensures the frontend and error messages are consistent
=> Update organisations#new views to use GOV.UK form builder

app/views/users/passwords/edit.html.erb, app/views/users/passwords/new.html.erb, spec/features/authentication/reset_password_spec.rb
Update password forms to use GOV.UK form builder
It simplifies code, ensures the frontend and error messages are consistent
=> Update password forms to use GOV.UK form builder

app/controllers/super_admin/wifi_user_searches_controller.rb, app/models/search_form.rb, app/views/super_admin/wifi_user_searches/show.html.erb, app/views/users/invitations/edit.html.erb, config/locales/en.yml, spec/features/super_admin/lookup_wifi_user_contact_details_spec.rb
Update invitations#edit and contact details forms to use GOV.UK form builder
It simplifies code, ensures the frontend and error messages are consistent
Introduced a form model to handle the 'search_term' parameter for the
contact details form.
=> Update invitations#edit and contact details forms to use GOV.UK builder

app/assets/javascripts/application.js.erb, app/views/layouts/_google_analytics.html.erb, app/views/layouts/_google_tag_manager_no_script.html.erb, app/views/layouts/application.html.erb, config/initializers/content_security_policy.rb, config/site.yml
This reverts commit 9fc5a48edab7ae7769e4bc23ff247530608a50d3.
Revert "Remove google tag manager" and add CSRF protection
So we can record and access analytics data on the admin site.
https://trello.com/c/wy54K9rM/2263-analytics-on-admin-user-journeys
=> Restore Google Tag Manager to Admin Site

config/initializers/content_security_policy.rb
Removes the CSP added in 64643534efa6cf329350fc58c50caa22f30785a1
as part of work to re-implement Google Analytics. Adding a CSP will
be split out into another PR.
To separate this proposed change into another PR, TBC after further
discussion.
https://trello.com/c/wy54K9rM/2263-analytics-on-admin-user-journeys
=> Remove Content Security Policy

app/models/location.rb, db/migrate/20220525140423_add_address_organisation_id_index_to_locations.rb, db/schema.rb, spec/features/ips/search_locations_spec.rb
Add model validation and database constraint
So that the same location address cannot be entered twice for any given organisation.
A single organisation may still have two different addresses with the same postcode.
https://trello.com/c/YDAI28UQ/2217-upload-a-list-of-locations-and-associated-ip-addresses-to-connect-to-govwifi
=> Add model validation and database constraint

app/controllers/super_admin/wifi_user_searches_controller.rb, app/views/super_admin/wifi_user_searches/confirm_destroy.html.erb, app/views/super_admin/wifi_user_searches/show.html.erb, config/routes.rb, spec/features/super_admin/lookup_wifi_user_contact_details_spec.rb
Support deleting wifi users.
So this task can be done by clicking in the admin app, rather than manually running queries against the database.
Link to Trello card: https://trello.com/c/yw5VYGdD/2265-a-super-admin-can-delete-user-credentials
=> Support deleting wifi users

docker-compose.yml
This is to ensure compatibility with M1 based macs
=> Explicitly add platform: linux/x86_64

app/controllers/users/two_factor_authentication_setup_controller.rb, app/views/layouts/_flash_notices.html.erb, spec/features/authentication/set_up_two_factor_authentication_spec.rb
Change wording and styling for 2FA error message
Current wording for 2FA error message is inaccurate
Link to Trello card (if applicable): https://trello.com/c/Cb2s7VqC/2444-wording-for-2fa-error-message-and-help-text
=> Six digit code error message

app/controllers/locations_controller.rb, app/views/locations/edit.erb, app/views/shared/_manage_ips.html.erb, config/routes.rb, spec/features/locations/update_location_spec.rb
Change a registered location address
Admin users are unable to amend address from the admin site. This is rarely a problem but on occasion an admin may need to make an amendment to an address and its associated IP. We could do this from the database but that requires scheduling dev time for an arbitrary task that could be performed by the admin as a self serve function.
Link to Jira ticket (if applicable): 
https://technologyprogramme.atlassian.net/browse/GW-102
Image attached:
=> GW-102-Change-a-registered-location-address-(Q2)

lib/use_cases/radius/publish_radius_ip_allowlist.rb, spec/use_cases/radius/publish_radius_ip_allowlist_spec.rb
Handle invalid IP models when publishing IP allow lists
There are a few IP models in the database that have no corresponding
location. This causes the PublishRadiusIpAllowlist to crash and results
in the user seeing an error when adding an IP address
This commit makes the code a bit more robust and ignores Ip models
without a location
=> Handle invalid IP models when publishing IP allow lists

app/controllers/ips_controller.rb, app/controllers/logs_controller.rb, app/views/ips/index.html.erb, app/views/logs/index.html.erb, spec/features/ips/search_locations_spec.rb, spec/features/logging/view_auth_requests_for_an_ip_spec.rb, spec/features/logging/view_logs_spec.rb
Describe the change
Extend search functionality to allow searches using the IP address and to add address information to the IP logs
Describe why the change was necessary
The first page of the admin tool (/IPS) allows users to search by location and postcode but not by IP address.
If admins search for a user who is having problems, they will see the IP address they are connecting to but won't know what location the IP address is attributed to.
https://technologyprogramme.atlassian.net/browse/GW-270
=> Search for an ip address on the ips screen and address address to logs

app/controllers/application_controller.rb, app/controllers/super_admin/wifi_admin_searches_controller.rb, app/models/user.rb, app/views/shared/sidebar/_default.html.erb, app/views/super_admin/wifi_admin_searches/show.html.erb, config/routes.rb, spec/features/super_admin/wifi_admin_searches_spec.rb, spec/models/user_spec.rb
Add search functionality to allow super admins to search for an admin and show organisations the admin is a part of
It is not possible to know which organisation an admin user belongs to without them providing this information up-front via Zendesk
https://technologyprogramme.atlassian.net/browse/GW-82
=> Add search functionality to allow super admins to search for an admin

config/locales/en.yml, spec/features/team/accept_an_invitation_and_sign_up_spec.rb
Re-word error message for password not strong enough.
Current wording for password not strong enough is confusing.
https://technologyprogramme.atlassian.net/browse/GW-298
=> Wording for password not strong enough error message

spec/controllers/locations_controller_spec.rb
Ip addresses can't be private for the form to add IP addresses to
be valid. Once in a while, the method Faker:Internet#public_ip_v4_address
would produce a private IP address causing the form to be invalid and
the test to fail.
This change ensure that only public IP addresses are chosen for the
test
=> Ensure the /update_ips feature test passes reliably.

app/views/shared/_manage_ips.html.erb, app/views/super_admin/locations/index.html.erb, spec/features/super_admin/locations/locations_spec.rb
As a super admin, when you’re investigating a thing, you might look for the location. But then you need to click the hyperlink for the organisation and then have to start working through the pages to find that location. It’s a pain when the organisation has lots of different locations - and the big users of GovWifi can often be the ones where tickets come in for.
Make it easier for super admins to find a location and find the IPs associated with it.
https://technologyprogramme.atlassian.net/browse/GW-291
=> add hyperlinks for locations to find associated IP addresses

app/helpers/pagy_helper.rb, spec/features/super_admin/locations/locations_spec.rb
Implement Design System Pagination component from the GovWifi admin tool.
To ensure that our admin tool follows the best practice with the Government Design System.
https://technologyprogramme.atlassian.net/browse/GW-279
=> update pagination for the admin site

app/helpers/pagy_helper.rb, spec/features/super_admin/organisations/view_organisation_page_spec.rb
When a large number of elements are present, the paginator will display a 'gap', usually 3 dots in the pagination index.
In a previous commit the code that handles this was accidentally removed and this commit reinstates this.
The removal of the code caused the website to display an error when too many pages are displayed
=> Fix an error in the pagination code

app/assets/stylesheets/components/locations.scss, app/controllers/locations_controller.rb, app/models/upload_form.rb, app/views/locations/bulk_upload.html.erb, app/views/locations/upload_locations_csv.html.erb, config/routes.rb, lib/bulk_upload/address_headers.rb, lib/bulk_upload/bulk_upload.rb, public/locations_upload_template.csv, spec/features/locations/bulk_upload_spec.rb, spec/fixtures/csv/locations_upload_extra_spaces.csv, spec/fixtures/csv/locations_upload_invalid_headers.csv, spec/fixtures/csv/locations_upload_no_dupes.csv, spec/fixtures/csv/locations_upload_no_dupes_commas.csv, spec/fixtures/csv/locations_upload_no_dupes_invalid_postcode.csv, spec/fixtures/csv/locations_upload_no_dupes_tabs.csv, spec/fixtures/csv/locations_upload_only_headers_no_data.csv, spec/fixtures/csv/locations_upload_with_dupes.csv, spec/requests/locations/confirm_upload_spec.rb
Describe the change
I changed few things in Location upload feature.
* I added a downloadable Template
* The upload now processes using Commas instead of Tabs.
* I have added extra columns in the upload to handle Address.
* Fix issue with Blank values for IP addresses.
Describe why the change was necessary
Blank error messages showing for IP addresses.
https://technologyprogramme.atlassian.net/browse/GW-290
=> Gw 290 blank error location uploads

app/views/super_admin/wifi_user_searches/show.html.erb
User interface fix to show 'User details for _search_term_ ' correctly and not with a blank string for _search_term_
Previous code showed an inconsistency in User interface.
JIRA: https://technologyprogramme.atlassian.net/browse/GW-873
=> User Search View Fix

app/views/layouts/application.html.erb
Changed the link used for Service Performance in footer -
from: https://www.gov.uk/performance/govwifi
to: https://www.data.gov.uk/search?q=GovWifi
Link was out of date
https://technologyprogramme.atlassian.net/browse/GW-181
=> Changed link for Service Performance

.github/workflows/workflow.yml, Makefile
Instead of building the GitHub runner container twice, just build once and run separate steps for lint and test rather than separate jobs.
Speed up the dev-PR-merge cycle, save the environment ;)
=> Join Lint and Test

config/gov_notify.yml
Add Notify Template ID's to the config for Dev.
This is needed to allow the Admin app to work properly on the Development Environment. 
GW-1125
=> fix: [GW-1125] Add Notify Templates to Dev Env

config/application.rb, config/environments/development.rb, lib/gateways/email_gateway.rb, lib/services.rb, spec/gateways/email_gateway_spec.rb
Created a stub implementation of EmailGateway which just prints out info and does not use notify or send actual email
db migration was attempting to use notify and failing since dev notify was not fully configured. Easier to not need notify in some localdev circumstances
=> Enable EmailGatewayStub use in development env

config/database.yml, config/environments/alpaca.rb, config/gov_notify.yml, config/secrets.yml, config/site.yml
Create an Alpaca config and Add notify templates to them.
So the Admin app can run in Alpaca with no links to the Staging environment. 
GW-1125
=> GW-1125 notify templates dev

config/gov_notify.yml
This is needed when Rails runs into development mode, i.e. running locally
=> Add development back into gov_notify.yml

docker-compose.yml, mysql/Dockerfile
Upgrade mysql docker containers from 5.7 to version 8.0.34
We are upgrading our databases to mysql 8. For more information see the linked Jira card below. Version 8.0.34 is the latest stable release.
https://technologyprogramme.atlassian.net/jira/software/projects/GW/boards/251?selectedIssue=GW-1132
https://technologyprogramme.atlassian.net/browse/GW-1144
=> Upgrade mysql docker containers from 5.7 to version 8.0.34

docker-compose.yml
For previous versions of mysql a specific platform had to be selected to make the admin app work on M1 macs. This has now changed with using a newer version of mysql and so these can be removed
=> Remove platform directives from docker-compose.yml

.github/pull_request_template.md, app/views/help/new.html.erb, app/views/help/user_support.html.erb, app/views/layouts/application.html.erb, config/site.yml
Describe the change
Correcting broken links.
Describe why the change was necessary
So that correct documentation can be accessed
[GW-1324](https://technologyprogramme.atlassian.net/browse/GW-1324)
[GW-1324]: https://technologyprogramme.atlassian.net/browse/GW-1324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [GW-1324] update broken links.

Gemfile, Gemfile.lock, app/helpers/pagy_helper.rb, config/initializers/pagy.rb, spec/features/super_admin/organisations/view_organisation_page_spec.rb
Bump pagy to 7.0.2
This has some breaking changes:
With the new version of Pagy, we now have to explicitly set how each
pager is to be rendered and the 'gap' has now a different i18n reference.
=> Dependabot/bundler/pagy 7.0.2

app/controllers/super_admin/organisations_controller.rb, app/models/organisation.rb, app/views/super_admin/organisations/index.html.erb, spec/features/super_admin/organisations/sort_organisation_list_spec.rb, spec/features/super_admin/organisations/view_organisation_list_spec.rb
Add another column to superadmin view to show which orgs use CBA
So that it is easy to see which organisations actively use CBA
[[GW-xxxx](https://technologyprogramme.atlassian.net/browse/GW-xxxx)
](https://technologyprogramme.atlassian.net/jira/software/projects/GW/boards/251?assignee=557058%3Add853f03-c9ea-4b86-a72e-1f14eb7f1aaf&selectedIssue=GW-1607)
=> Add another column to superadmin view to show which orgs use CBA

lib/use_cases/certificate_exporter.rb
avoid repeated queries in certificate exporter
=> avoid repeated queries in certificate exporter

app/controllers/application_controller.rb, app/controllers/super_admin/current_organisation_controller.rb, app/models/user.rb, app/views/shared/sidebar/_default.html.erb, app/views/super_admin/current_organisation/edit.html.erb, config/routes.rb, spec/features/super_admin/switch_organisation_spec.rb
Add a screen that allows a super admin to switch to any organisation
This can make diagnosing issues by super admins easier
https://technologyprogramme.atlassian.net/browse/GW-1746
=> Add a screen that allows a super admin to switch to any organisation

app/models/session.rb, lib/gateways/sessions.rb, spec/features/logging/filter_logs_spec.rb
The bug was caused by the cert_* attributes sometimes being an empty string instead of NULL. An easier and more reliable method to distinguish between EAP-TLS and MSCHAP is by selecting on the username being NULL.
https://technologyprogramme.atlassian.net/browse/GW-1764
=> Fix filtering logging by EAP-TLS and MSCHAP

app/views/super_admin/organisations/_cba_form.html.erb
The button to enable/disable CBA for an organisation used to be used to enable/disable logging for CBA only, but is now used to enable all CBA functionality and so the button is renamed accordingly
=> Rename CBA button

lib/deploy.rb
APP_ENV overrides RAILS_ENV and is therefore a bad choice for this.
=> Use DEPLOY_ENV instead of APP_ENV to indicate the platform to deploy on

lib/notify_templates.rb, spec/notify_templates_spec.rb, spec/support/notify_gateway_spy.rb
Templates from notify return a TemplateCollection and not an array.
=> Fix template error

app/controllers/super_admin/wifi_user_searches_controller.rb, app/mailers/gov_wifi_mailer.rb, lib/notify_templates.rb, spec/features/support/email_helpers.rb, spec/features/support/sms_helpers.rb
The templates we use to tell users their credentials have been removed are the same in the admin portal and the user signup api.
However they were named differently in both. This change ensures they are the same in both repositories
=> Rename remove user templates

lib/notify_templates.rb, lib/tasks/verify_notify_templates.rake, spec/features/ips/first_ip_survey_spec.rb, spec/features/super_admin/invite_user_to_organisation_spec.rb, spec/features/super_admin/lookup_wifi_user_contact_details_spec.rb, spec/features/team/invite_with_permissions_spec.rb, spec/notify_templates_spec.rb, spec/requests/users/invitations/create_spec.rb, spec/spec_helper.rb
The healthcheck now includes a call to check if all notify templates are defined.
We need to ensure all notify templates have been defined before the container starts.
https://technologyprogramme.atlassian.net/jira/software/projects/GW/boards/251
=> Add template check to healthcheck

app/models/certificate.rb, spec/factories/x509_certificate.rb, spec/models/certificate_spec.rb
The has_child? method should use a certificate model as a parameter of the Certificate#verify method.
This bug only shows when using an EC based key.
https://technologyprogramme.atlassian.net/browse/GW-1991
=> Fix bug in certificate model

app/views/mous/show_options.html.erb
Ensure that inputs have a unique and descriptive programmatically associated label.
Further, as detailed by GOV.UK Design System: Radios (How it works), related radio buttons
should be grouped within a
element and be provided with a descriptive
(which should be the first direct child of the , as defined by the HTML standard, otherwise it might not be correctly picked up by assistive technology).
On the 'Memorandum of understanding' page, there are radio buttons that, due to a lack of
programmatic association between the label and input, lack an accessible name.
This affects screen reader users, as the radio buttons are not labelled and, therefore, their
purpose is not programmatically determinable, and it also affects voice activation users, as
there is no programmatic association between …
=> GW-1913- Accessibility audit radio buttons

app/controllers/application_controller.rb, spec/features/authentication/set_up_two_factor_authentication_spec.rb
Previously, it was impossible to sign out while setting up 2FA clicking the sign out link, would take the user back to the 2FA screen.
Now, signing out takes the user back to the sign in page while setting up 2FA
https://technologyprogramme.atlassian.net/jira/software/projects/GW/boards/251
=> Allow signing out while setting up 2FA

lib/use_cases/backup_service_emails.rb
Require CSV to fix the BackupServiceEmails class
Otherwise converting an array to CSV does not work
[GW-xxxx](https://technologyprogramme.atlassian.net/browse/GW-xxxx)
=> Require CSV to fix the BackupServiceEmails class

package.json, yarn.lock
Update URL of govwifi-shared-frontend
Update URL of govwifi-shared-frontend. We are migrating our repos from the alphagov github organisation to the govwifi organisation. We need to update the repos to the appropriate URLs.
https://technologyprogramme.atlassian.net/jira/software/projects/GW/boards/251?assignee=5e45277d29e6d00c970616c6&selectedIssue=GW-1851
=> Update URL of govwifi-shared-frontend

app/controllers/memberships_controller.rb, app/controllers/users/invitations_controller.rb, app/models/membership.rb, app/views/ips/_confirm_rotate_radius_key.html.erb, app/views/users/invitations/invite_second_admin.html.erb, app/views/users/invitations/new.html.erb, spec/features/support/sign_up_helpers.rb
- Replaced hardcoded permission strings with constants defined in `Membership::Permissions` to improve code maintainability and consistency.
- Centralised all permission-related values, minimising the risk of typos and ensuring consistency across the codebase.
This change enhances readability, reduces duplication, and makes the permission system easier to modify and debug.
=> Use constants for membership permissions throughout the app

app/models/user.rb
The rememberable module in Devise allows users to stay signed in across browser sessions by setting a persistent remember_me cookie. This cookie securely stores a token linked to the user’s account, enabling automatic authentication when the user revisits the app, unless the cookie is manually cleared or expired.
We currently don't use this functionality and it can therefore be removed
=> Remove Devise rememberable

app/models/user.rb, lib/tasks/delete_inactive_unconfirmed.rake, lib/use_cases/delete_inactive_unconfirmed.rb, spec/use_cases/delete_inactive_unconfirmed_spec.rb
Clean up unconfirmed users that have been created more than 2 weeks ago
These users have been sent an email with a link to confirm their account but have not accepted it
We want to keep the database free from clutter
https://technologyprogramme.atlassian.net/browse/GW-2102
=> Clean up unconfirmed users that have been created more than 2 weeks ago

app/controllers/application_controller.rb
When entering an incorrect route in the admin portal, it returns a 500 error code with a message: 
```
500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong. 
```
This is an incorrect message and should instead be a message saying that the page does not exist with a 404 error code
https://technologyprogramme.atlassian.net/browse/GW-2100
=> Ensure that error pages render the correct error page

.github/workflows/workflow.yml
Ubuntu 20.04 is being deprecated and can now no longer run tasks
=> Update Github action runner

app/controllers/application_controller.rb, app/controllers/nominations_controller.rb, app/views/logs/index.html.erb
ApplicationController's `current_organisation` method is getting called inside the loop which results in repeated  queries and slowing down the page load.
To optimise the log search/filters, 'current_organisation` method needs to be memoized. 
It is good candidate for  memoization as it is being used in different pages of the application.
[GW-449](https://technologyprogramme.atlassian.net/browse/GW-449)
=> GW-449: Optimise reading of sessions database

app/controllers/super_admin/organisations_controller.rb, config/environments/development.rb
Configure bullet gem for alerts and logs for development environment:  https://github.com/flyerhzm/bullet?tab=readme-ov-file#configuration
- Optimise performance for Organisation list and show pages
- Show popup if N+1 issue exists (only in `development` environment)
- <img width="809" alt="Screenshot 2025-03-24 at 12 20 16" src="https://github.com/user-attachments/assets/90711f5c-9fda-4963-9400-d9adaad830bf" />
[GW-2156](https://technologyprogramme.atlassian.net/browse/GW-2156)
=> GW-2156: Configure bullet gem and fix N+1 issues for organisation list and show pages

lib/gateways/sessions.rb, spec/gateways/sessions_spec.rb
Optimise query performance while filtering logs
- Load only required columns
- Ordering by `id(bigint)` is more efficient than ordering by `start(timestamp)`
> [!IMPORTANT]  
> TODO: Discuss if we should use `id` instead of `start` for ordering
```sql
SELECT `sessions`.* 
FROM `sessions` 
WHERE (start >= '2025-03-10 17:11:06.118846') 
ORDER BY `sessions`.`start` DESC;
-- Results
700000 rows in set (1.27 sec)
700000 rows in set (1.06 sec)
700000 rows in set (1.24 sec)
700000 rows in set (1.36 sec)
700000 rows in set (1.27 sec)
700000 rows in set (1.31 sec)
```
```sql
SELECT `sessions`.`start`, `sessions`.`username`, `sessions`.`siteIP`, `sessions`.`success`, `sessions`.`ap`, `sessions`.`mac`, `sessions`.`task_id` 
FROM `sessions` 
WHERE (start >= '2025-03-10 17:17:49.247730') 
ORDER BY …
```
=> GW-449-improve-query-performance-reading-sessions 

db/migrate/20250423141522_set_membership_invitation_token.rb, db/schema.rb
This is usually set in the before_create method in the model, but in the database there are a number that are NULL. This interferes with some code that expects this to be set.
This PR adds a migration that sets the invitation code to a random 20 character string
https://technologyprogramme.atlassian.net/browse/GW-2221
=> Set invitation token on memberships if set to NULL

app/controllers/users/invitations_controller.rb, app/views/users/invitations/invite_second_admin.html.erb
Fix `ActionView::Template::Error` for `Users::InvitationsController#create` action
Sentry: https://govwifi.sentry.io/issues/6560231065/?environment=production&project=1259357&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&stream_index=1
WHY
This error occurred because on form variable name inconsistency in 
`app/controllers/users/invitations_controller.rb` > `create`
https://github.com/GovWifi/govwifi-admin/blob/fix-template-error/app/controllers/users/invitations_controller.rb#L12-L21
[GW-2231](https://technologyprogramme.atlassian.net/browse/GW-2231)
=> GW-2231: Fix template error

app/controllers/ips_controller.rb, spec/features/ips/search_locations_spec.rb
Remove duplication in location search results
When using the search option in the the locations view, sometimes duplicate locations appear. This PR fixes this.
https://technologyprogramme.atlassian.net/browse/GW-2237
=> Remove duplication in log search results

Makefile
The erb linter has been renamed to erb_lint instead of erblint
=> The erb linter has been renamed to erb_lint instead of erblint

lib/tasks/reset_smoke_test_users.rake, lib/use_cases/reset_smoke_test_users.rb, spec/use_cases/reset_smoke_test_users_spec.rb
Create a Rake task to reset the smoke test users details to the expected state, which we can run manually should the smoke tests fail.
The smoke tests can break if ran concurrently, which can leave the admin site in an inconsistent state and the smoke tests will fail with, invalid user/password, or unable to add / remove user. This happens because one of the steps in the smoke tests change the password of a user and back again.
[[GW-xxxx](https://technologyprogramme.atlassian.net/browse/GW-xxxx)](https://technologyprogramme.atlassian.net/browse/GW-2195)
=> reset smoke test users

app/controllers/super_admin/allowlists/email_domains_controller.rb, app/views/super_admin/allowlists/email_domains/_confirm_remove_email_domain.html.erb, app/views/super_admin/allowlists/email_domains/_table.html.erb, app/views/super_admin/allowlists/email_domains/index.html.erb
Use the govuk table component for the email allowlist page
This ensures that the page is more compatible with the design system
https://technologyprogramme.atlassian.net/browse/GW-2259
=> Use the govuk table component for the email allowlist page
