GovWifi/govwifi-admin

config/application.rb
lib/radius_secret_key_generator.rb
spec/unit/radius_secret_key_generator_spec.rb

Generate a random RADIUS secret key

---

app/views/ips/_activation_notice.html.erb
app/views/ips/_how_to_links.html.erb
app/views/ips/new.html.erb
app/views/ips/show.html.erb
spec/features/add_an_ip_address_spec.rb
spec/features/support/activation_notice.rb
spec/monitoring/healthcheck_spec.rb

Add activation notice to New IP form:

See that I have to wait 24 hours

---

app/assets/stylesheets/utilities/layout.scss
app/views/layouts/application.html.erb

Add alpha badge and improve header.
- Desktop:
- Mobile closed:
- Mobile open:

Add Alpha Badge

---

app/views/users/registrations/new.html.erb
app/views/users/shared/_links.html.erb

Main thing is changes to copy.
Also added a password reset link and more hints (for users who aren't organisations, and around which emails are valid)

Improve UX of (what will likely be) landing page

---

app/controllers/users/confirmations_controller.rb
app/helpers/application_helper.rb
app/models/organisation.rb
app/models/user.rb
app/views/ips/new.html.erb
app/views/users/confirmations/new.html.erb
app/views/users/confirmations/show.html.erb
app/views/users/passwords/edit.html.erb
app/views/users/registrations/new.html.erb
db/migrate/20180822142329_create_organisations.rb
db/migrate/20180822142913_add_organisation_id_to_users.rb
db/schema.rb
db/seeds.rb
spec/factories/organisations.rb
spec/features/sign_up_as_an_organisation_spec.rb
spec/features/support/sign_up_helpers.rb
spec/models/organisation_spec.rb
spec/models/user_spec.rb

When a user signs up they are asked to enter an Organisation Name which has to be unique.
Refactored the error classes into a helper method for each form field in the app.

Create Organisations v2

---

app/controllers/ips_controller.rb
app/views/ips/index.html.erb
app/views/team_members/_table.html.erb
spec/features/view_team_members_spec.rb

Allow users to view team members

---

app/views/ips/index.html.erb
spec/features/add_an_ip_address_spec.rb
spec/features/reset_password_spec.rb
spec/features/team/accept_an_invitation_and_sign_up_spec.rb
spec/features/view_ip_addresses_spec.rb

Add Organisation Name to Home

---

app/assets/stylesheets/utilities/layout.scss
app/views/team_members/_table.html.erb
config/initializers/devise.rb
spec/features/team/invite_a_team_member_spec.rb

Allow users to resend invites on pending teammates

---

config/environments/production.rb
config/environments/staging.rb

We stub out AWS in development and test, but want it function as normal
on staging and production

Missed config values for staging and production

---

app/assets/stylesheets/utilities/layout.scss
app/views/layouts/application.html.erb
app/views/status/index.html.erb
spec/features/status/view_status_spec.rb

Link status

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/subnav.scss
app/helpers/application_helper.rb
app/views/application/_subnavigation.html.erb
app/views/layouts/application.html.erb

Modelled off [PaaS](https://admin.cloud.service.gov.uk/organisations/92755f7e-9cc4-44a2-9540-89251f420fb6/spaces/8c1213f3-4a0e-4857-b0d9-bcd586785a06/applications)
Desktop:
Mobile:

Subnav styling

---

app/controllers/ips_controller.rb
app/views/ips/_table.html.erb
app/views/ips/index.html.erb
db/seeds.rb
spec/features/view_ip_addresses_spec.rb

Also style the "Add IP Address" button to be consistent with the button
on the team page.

Display the location of an IP on the IP index page

---

app/controllers/ips_controller.rb
config/routes.rb
spec/features/view_ip_addresses_spec.rb

It looks like this is unused since no links point to it, and it has no
associated view.

Remove IP address show action

---

app/assets/stylesheets/components/ips.scss
app/views/ips/_table.html.erb

Split column spacing evenly for ip table columns

---

lib/use_cases/administrator/check_if_valid_ip.rb
spec/models/ip_spec.rb

This is not a valid IP address, don't allow it to be added.

Disallow 0.0.0.0

---

app/views/help/index.html.erb
app/views/home/index.html.erb
app/views/ips/index.html.erb
app/views/ips/new.html.erb
app/views/layouts/application.html.erb
app/views/team_members/index.html.erb
app/views/users/invitations/new.html.erb

- Edit tagline:
- Replace collapsible content with visible paragraph:
- Change title in Nav Page:
- Add explanation for adding team members
- Change select location to add IP to existing....

Improve Admin Platform Content 

---

app/views/organisations/index.html.erb
config/routes.rb

#176 Forgot to push suggested edits made locally before merging. Done with this PR

Implement PR comments from DisList PR

---

app/controllers/logs_controller.rb
app/views/logs/index.html.erb
spec/features/logging/view_auth_requests_for_a_username_spec.rb

- Better error messages for incorrect usernames
- Improve column table titles
- Add back button
- Add govuk classes to text
- Remove milliseconds from timestamp
- Sort results by latest first

Error handling for searching logs

---

Makefile

This fixes tests on a clean database

ensure the database is created before setting the environment

---

README.md

includes an introduction, how to set up and contribute.

Update README to include content

---

Dockerfile
Jenkinsfile
Makefile
docker-compose.development.yml
docker-compose.yml

Reverts alphagov/govwifi-admin#183
Jenkins Docker plugin has a bug that breaks for multi-stage dockerfiles. You need to change how you reference the stages.
Reverting until time is made for implementing this workaround.

Revert "Restructure dockerfile + make"

---

app/models/location.rb
app/views/ips/_table.html.erb
spec/features/view_ip_addresses_spec.rb
spec/models/location_spec.rb

Added a method to the model to provide this `full address`, didn't feel like enough logic to justify more components than that.

Show location postcode in list of IPs, if available

---

app/controllers/users/confirmations_controller.rb
app/models/organisation.rb
app/views/users/confirmations/show.html.erb
spec/factories/organisations.rb
spec/features/sign_up_as_an_organisation_spec.rb
spec/features/support/sign_up_helpers.rb

Set service email on Organisation signup

---

app/views/logs/search.html.erb
app/views/organisations/index.html.erb

Style organisations table

---

app/assets/stylesheets/components/ips.scss
app/views/ips/_table.html.erb
app/views/ips/index.html.erb
app/views/organisations/index.html.erb
spec/features/logging/view_auth_requests_for_an_ip_spec.rb

(Also as a bonus tweak, this PR limits the length of service e-mails so that table doesn't look bad)

Full-width IPs table

---

app/assets/stylesheets/utilities/layout.scss
app/views/ips/_table.html.erb
spec/features/logging/view_auth_requests_for_an_ip_spec.rb

Things don't look right on staging:
With this PR, they can look right:

Force third-width columns, pull link right

---

app/views/layouts/application.html.erb
config/site.yml

Add script to allow google analytics to collect user data

Add google analytics

---

app/controllers/organisations/mou_controller.rb
app/views/organisations/mou/index.html.erb
spec/features/upload_download_mous_spec.rb

Fix the crashing issue when the user clicks the MoU upload button when no file has been uploaded.

Fix MoU upload button crashing 

---

app/views/organisations/mou/index.html.erb

Looking at this feature on staging, I'm worried the look/language is a bit off. Had a quick pass to try and improve it, don't want to get too deep until we have design feedback.

Improve spacing, language on MOU page

---

app/assets/javascripts/googletagmanager.js
app/views/layouts/application.html.erb
config/initializers/assets.rb
config/site.yml

Add some changes to the codebase surrounding google tag manager such as extracting the javascript tags into a separate file.
Changes were based on suggestions in PR #262 
Purpose: To make GTM implementation easier to understand and change.
Suggestions/feedback on changes would be appreciated.

Implement suggested changes to the Google Tag Manager code

---

app/controllers/admin/mou_controller.rb
app/controllers/admin/organisations_controller.rb
app/views/admin/organisations/_locations.html.erb
app/views/admin/organisations/_mou_form.html.erb
app/views/admin/organisations/_section.html.erb
app/views/admin/organisations/_section_header.html.erb
app/views/admin/organisations/_team.html.erb
app/views/admin/organisations/_usage.html.erb
app/views/admin/organisations/index.html.erb
app/views/admin/organisations/show.html.erb
app/views/layouts/application.html.erb
config/routes.rb
db/seeds.rb
spec/features/admin/view_organisation_page_spec.rb
spec/features/support/user_not_authorised.rb

https://trello.com/c/NtsOACwL/17-8-show-page-for-organisation-in-super-admin

Organisation details page for super admin

---

app/controllers/admin/organisations_controller.rb
app/views/admin/organisations/index.html.erb
spec/features/admin/sort_view_in_organisation_list_spec.rb

Sort list of organisations by MoU upload date

---

spec/models/user_spec.rb

When I was playing with the User model around permissions, I did some work around the existing specs. Didn't want to confuse them with the rest of the changes, so here they are as a separate PR.
Don't want to spend too much time on it (it's small, opinionated changes), have pushed it up as I'm interested to hear if people have significantly different opinions / want to ask why I did a thing.

Better (?) user specs

---

app/assets/stylesheets/utilities/layout.scss
app/views/admin/organisations/index.html.erb
app/views/ips/_table.html.erb

OLD:
NEW
(thanks @tommotaylor for the govuk-width tip - I've scourged the custom one as part of this PR)

Limit width of org names

---

app/views/home/index.html.erb

Fix display of Overview page on Internet Explorer

---

app/controllers/admin_controller.rb
app/controllers/home_controller.rb
app/views/application/_subnavigation.html.erb
db/migrate/20181127155510_rename_admin_to_super_admin.rb
db/schema.rb
db/seeds.rb
spec/features/admin/sign_in_as_admin_spec.rb
spec/features/admin/sort_view_in_organisation_list_spec.rb
spec/features/admin/view_organisation_list_spec.rb
spec/features/admin/view_organisation_page_spec.rb
spec/features/admin/view_organisation_tab_spec.rb
spec/features/upload_download_mous_spec.rb

The method returns a boolean value from the user table in the database
The admin column in the user table was renamed to super_admin
The associated tests and their set-up were also edited to accomodate the new change.

Rename method that grants super admin access from admin? to super_admin?

---

app/assets/stylesheets/utilities/layout.scss
app/views/application/_radius_details.html.erb
app/views/application/_subnavigation.html.erb
app/views/ips/_table.html.erb
spec/features/guidance_after_sign_in_spec.rb
spec/features/ips/add_ip_to_location_spec.rb
spec/features/ips/view_ip_addresses_spec.rb

Move RADIUS secret keys to IP's page

---

app/views/status/_result.html.erb

Align rows in table on status page

---

Jenkinsfile

this allows us to have a user input + timeout without consuming a worker

break output the user input into a separate stage

---

app/views/help/existing_account.html.erb
app/views/help/signed_in.html.erb
app/views/help/signing_up.html.erb
app/views/layouts/application.html.erb

Add Beta phase banner 
Add some form of time frame when we will reply to support enquires

Giving admins more information

---

app/assets/stylesheets/components/overview.scss
app/assets/stylesheets/components/team_members.scss
app/views/home/index.html.erb
app/views/setup_instructions/index.html.erb
app/views/team_members/_table.html.erb

Small design fixes

---

db/seeds.rb

I thought this'd be very unlikely, but it's happened to me twice now, so I'm fixing it.

Stop IPs in seeds.rb clashing

---

app/controllers/organisations_controller.rb
app/views/application/_subnavigation.html.erb
app/views/organisations/edit.html.erb
app/views/organisations/show.html.erb
app/views/team_members/_service_email.html.erb
app/views/team_members/index.html.erb
config/routes.rb
spec/features/admin/edit_organisation_details_spec.rb
spec/features/team/invite_a_team_member_spec.rb

- Subnav condensed and rearranged
- Service email displayed on team page

Condense subnav

---

app/assets/stylesheets/components/sub_nav.scss

Change text size of subnav elements 

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/overview.scss
app/views/home/index.html.erb

Overview stats panel changes

---

Jenkinsfile

Don't use the API cluster for this.

Run migrations in the admin cluster

---

app/views/application/_radius_details.html.erb
app/views/setup_instructions/index.html.erb

Couldn't find a way to make this clear without changing the structure a bit, so that's what I did.
Thanks to Pippa for helping with a first round of feedback - happy to hear more though!

Recommend adding to many RADIUS servers

---

Jenkinsfile

We need launchType to be text so we get an unquoted value

specify the output type for each command

---

app/views/application/_subnavigation.html.erb

Highlight correct subnav link for MoU and locations pages

---

app/views/layouts/application.html.erb
config/site.yml

Add link to cookie policy

---

lib/gateways/s3.rb
lib/use_cases/administrator/publish_signup_whitelist.rb
lib/use_cases/performance_platform/publish_locations_ips.rb
lib/use_cases/radius/publish_whitelist.rb
spec/features/super_admin/authorised_email_domain_spec.rb
spec/gateways/s3_spec.rb
spec/requests/email_domain/delete_spec.rb
spec/use_cases/administrator/publish_signup_whitelist_spec.rb
spec/use_cases/performance_platform/publish_locations_ips_spec.rb
spec/use_cases/publish_radius_whitelist_spec.rb

Rename the upload method to write on the s3 gateway for consistency.

Rename upload to write

---

app/views/layouts/_google_analytics.html.erb
app/views/layouts/_google_tag_manager_no_script.html.erb
app/views/layouts/application.html.erb

This is a reimplementation.
The container is new so it has a different container ID which is why PR #466 wasn't reverted.
**Suggestions and feedback would be appreciated.**

Reimplement new GTM script

---

app/views/layouts/application.html.erb
app/views/status/index.html.erb

Add system status footer link

---

app/controllers/mou_controller.rb
app/views/mou/index.html.erb
spec/features/upload_download_mous_spec.rb

Better MoU upload feedback

---

app/views/team_members/edit.html.erb
spec/features/team/edit_permissions_spec.rb

Make team permissions clearer

---

app/controllers/team_members_controller.rb
spec/features/team/view_team_members_spec.rb

Order team members list by email

---

app/controllers/team_members_controller.rb
spec/features/team/view_team_members_spec.rb

Sort team members by name or email 

---

app/controllers/logs_searches_controller.rb
app/views/logs_searches/location.html.erb
spec/features/logging/view_auth_requests_for_a_location_spec.rb

Order locations logs search alphabetically 

---

app/controllers/logs_searches_controller.rb
spec/features/logging/view_auth_requests_for_a_location_spec.rb

This controller is used for the 'search again' route. Ensure we're testing it, and add locations to it.

ensure @locations is set on the location specific controller

---

app/views/users/invitations/new.html.erb
spec/features/team/invite_with_permissions_spec.rb

Normalise permissions to the user

---

app/controllers/users/registrations_controller.rb
app/views/users/registrations/new.html.erb
spec/features/registration/sign_up_as_an_organisation_spec.rb

Reword some error messages based on advice from a technical writer found [here](https://docs.google.com/document/d/1A5RbghwSrkAmIP-0Fk5PTgEZMbh_g8euaMbR5K44K3k/edit).
**BEFORE 1:**
**AFTER 1:**
**BEFORE 2:**
**AFTER 2:**
**BEFORE 3:**
**AFTER 3:**
**BEFORE 4:**
**AFTER 4:**
------------------------------------------------------------------------------------------------- …

Edit content language

---

.rubocop.yml
app/views/team_members/_table.html.erb
spec/features/team/accept_an_invitation_and_sign_up_spec.rb
spec/features/team/edit_permissions_spec.rb
spec/features/team/invite_a_team_member_spec.rb
spec/features/team/invite_with_permissions_spec.rb
spec/features/team/permissions_spec.rb
spec/features/team/remove_a_team_member_spec.rb
spec/features/team/resend_invitation_spec.rb
spec/features/team/view_team_members_spec.rb

Lint all specs in the `spec/features/team/` folder

Lint spec/features/team/ folder

---

.rubocop.yml
spec/features/admin/delete_custom_organisation_spec.rb

Lint `spec/features/admin/delete_custom_organisation_spec.rb`

Lint delete custom organisation spec

---

.rubocop.yml
spec/features/locations/add_new_location_spec.rb
spec/features/locations/remove_a_location_spec.rb

Lint `spec/features/locations/` folder

Lint spec/features/locations folder

---

.rubocop.yml
spec/features/status/view_status_spec.rb

Lints `spec/features/status/view_status_spec.rb`

Lint view status spec

---

app/controllers/users/invitations_controller.rb

This introduces caching for querying an already invited user
We also lean more on the base controller, which means we can remove our validation and authorisation checking

Refactor invitation controller

---

.rubocop.yml
spec/features/authentication/lock_user_account_spec.rb
spec/features/authentication/logging_in_after_signing_up_spec.rb
spec/features/authentication/reset_password_spec.rb

Lints the `spec/features/authentication/` folder

Lint authentication specs folder

---

app/controllers/admin/mou_controller.rb
app/views/admin/mou/index.html.erb

Before MoU uploaded:
After MoU uploaded:

Super admin dynamic MoU upload

---

app/controllers/locations_controller.rb
config/routes.rb
spec/features/locations/add_new_location_spec.rb

location creation doesn't pass validation:
`/locations/new -> /locations -> ...`
location created without an IP:
`/locations/new -> /ips/created/location`
location created with an IP:
`/locations/new -> /ips/created/location/with-ip`

set up adding a location to have special paths for analytics

---

app/controllers/locations_controller.rb
config/routes.rb
spec/features/locations/remove_a_location_spec.rb

`/location/<id>/remove -> /ips/removed/location`

add path for analytics for post location removal

---

app/controllers/team_members_controller.rb
app/controllers/users/invitations_controller.rb
config/routes.rb
spec/features/team/edit_permissions_spec.rb
spec/features/team/invite_a_team_member_spec.rb
spec/features/team/remove_a_team_member_spec.rb
spec/features/team/resend_invitation_spec.rb

`/users/invitation/new -> /team_members/created/invite`
`/team_members -> <click on resend> -> /team_members/recreated/invite`
`/team_members/<id>/edit -> /team_members/updated/permissions`
`/team_members/<id>/edit -> /team_members/<id>/edit?remove_team_member=true -> /team_members/removed`

Add in new paths for analytics when managing the team page

---

db/migrate/20190402134657_add_super_admin_to_organisations.rb
db/schema.rb

First stage for https://github.com/alphagov/govwifi-admin/pull/598

Add super_admin column to organisations 

---

db/migrate/20190402142239_remove_super_admin_from_users.rb
db/schema.rb

Last part of https://github.com/alphagov/govwifi-admin/pull/598

Remove super_admin from users table

---

app/views/layouts/application.html.erb

Fix favicon not appearing

---

.rubocop.yml
spec/models/ip_spec.rb
spec/models/location_spec.rb
spec/models/logs_search_spec.rb

**WHY:**
Consistency & general housekeeping.
Lint and refactor the following files in the `spec/models folder`:
- `spec/models/logs_search_spec.rb`
- `spec/models/ip_spec.rb`
- `spec/models/location_spec.rb`
**Any suggestions/feedback would be appreciated.**

Lint specs in models part one

---

Dockerfile

we use this for scripts, and our shell environment

ensure bash is installed

---

.rubocop.yml
spec/features/authentication/logging_in_after_signing_up_spec.rb
spec/features/invite_existing_user_spec.rb
spec/features/registration/resend_confirmation_instructions_spec.rb
spec/features/registration/sign_up_as_an_organisation_spec.rb
spec/features/super_admin/invite_user_to_organisation_spec.rb
spec/features/team/accept_an_invitation_and_sign_up_spec.rb
spec/features/team/invite_a_team_member_spec.rb
spec/features/team/resend_invitation_spec.rb
spec/requests/users/invitations/create_spec.rb
spec/support/confirmation_use_case.rb
spec/support/notifications_service.rb
spec/support/unlock_account_use_case_spy.rb

Lint and refactor the following files in the `spec/support` folder:
- `spec/support/notifications_service.rb`
- `spec/support/confirmation_use_case.rb`
- `spec/support/unlock_account_use_case_spy.rb`
Rename shared examples where relevant

Lint support specs part one v2

---

.rubocop.yml
spec/use_cases/administrator/generate_radius_secret_key_spec.rb
spec/use_cases/performance_platform/publish_locations_ips_spec.rb
spec/use_cases/publish_whitelist_spec.rb
spec/use_cases/radius/generate_radius_ip_whitelist_spec.rb

Lint:
```
spec/use_cases/radius/generate_ip_whitelist_spec.rb
spec/use_cases/generate_radius_secret_key_spec.rb
spec/use_cases/performance_platform/publish_locations_ips_spec.rb
spec/use_cases/publish_radius_whitelist_spec.rb
```

Lint use case specs part one

---

.rubocop.yml
spec/features/contact_us_when_not_signed_in_spec.rb
spec/features/registration/resend_confirmation_instructions_spec.rb
spec/features/registration/sign_up_as_an_organisation_spec.rb

Lints:
```
spec/features/registration/sign_up_as_an_organisation_spec.rb
spec/features/registration/resend_confirmation_instructions_spec.rb
spec/features/contact_us_when_not_signed_in_spec.rb
```

Lint feature specs part two

---

.rubocop.yml
app/views/ips/_table.html.erb
spec/features/ips/add_ip_to_existing_location_spec.rb
spec/features/ips/permissions_spec.rb
spec/features/ips/remove_an_ip_spec.rb
spec/features/ips/view_ip_address_readiness_spec.rb
spec/features/ips/view_ip_addresses_spec.rb

Lint:
```
spec/features/ips/permissions_spec.rb
spec/features/ips/view_ip_address_readiness_spec.rb
spec/features/ips/add_ip_to_existing_location_spec.rb
spec/features/ips/view_ip_addresses_spec.rb
spec/features/ips/remove_an_ip_spec.rb
```

Lint remaining feature specs

---

app/controllers/locations_controller.rb
spec/features/locations/add_new_location_spec.rb

Improve messaging when adding a location and IP 

---

app/controllers/admin/custom_organisations_controller.rb
app/views/admin/custom_organisations/index.html.erb
app/views/shared/_organisation_register_dropdown.html.erb
app/views/users/confirmations/show.html.erb

Allow a super admin to check the register before adding an organisation

---

app/views/admin/whitelists/_side_nav.html.erb
app/views/admin/whitelists/email_domains/index.html.erb
app/views/admin/whitelists/new.html.erb
app/views/admin/whitelists/organisation_names/index.html.erb
app/views/application/_subnavigation.html.erb
spec/features/super_admin/whitelists/whitelisting_process_spec.rb

Implements new page and subnav. The subnav appears on all whitelist pages. This PR doesn't tackle the step by step whitelisting process, thats next.

Implement new whitelist page

---

ci/pipelines/pr.yml

This prevents fetches from happening, as well as applies a sensible context

tweak how we do our PR status calls

---

app/views/ips/_table.html.erb
app/views/ips/index.html.erb
app/views/shared/_filter_search.html.erb

Adds a JS powered search bar to IPs list

Dynamic search filter for locations/Ips

---

app/controllers/admin/whitelists/organisation_names_controller.rb
app/helpers/application_helper.rb
app/jobs/application_job.rb
lib/gateways/coordinates.rb
spec/features/edit_organisation_details_spec.rb
spec/features/error_spec.rb
spec/features/logging/view_auth_requests_for_a_username_spec.rb
spec/features/super_admin/govwifi_map_spec.rb
spec/features/super_admin/upload_download_mou_spec.rb
spec/gateways/coordinates_spec.rb
spec/spec_helper.rb

Get spec coverage back up to 100%

---

ci/tasks/scripts/aws-helpers.sh
ci/tasks/scripts/deploy.sh
ci/tasks/scripts/lint.sh
ci/tasks/scripts/migrate.sh
ci/tasks/scripts/pre-build.sh
ci/tasks/scripts/test.sh
ci/tasks/scripts/with-docker.sh
spec/features/error_spec.rb

We've just had a false positive on our tests for PRs, so let's be better

be strict in all our concourse scripts

---

Gemfile
Gemfile.lock
spec/spec_helper.rb

This improves visibility of failing coverage locally and on CI

output coverage reports to the console

---

app/controllers/admin/whitelists_controller.rb
app/models/whitelist.rb
app/views/admin/whitelists/new.html.erb
app/views/admin/whitelists/steps/_fifth.html.erb
app/views/admin/whitelists/steps/_first.html.erb
app/views/admin/whitelists/steps/_fourth.html.erb
app/views/admin/whitelists/steps/_second.html.erb
app/views/admin/whitelists/steps/_sixth.html.erb
app/views/admin/whitelists/steps/_third.html.erb
config/routes.rb
spec/features/super_admin/whitelists/whitelisting_process_spec.rb
spec/requests/whitelist/create_spec.rb

Still needs some design love but works and is tested at this stage. I suggest we merge and then improve the rest in separate PRs.
Test by visiting `/admin/whitelist/new` and going through the flow:

Whitelisting flow

---

app/views/admin/organisations/index.html.erb
app/views/ips/_table.html.erb
app/views/ips/index.html.erb
app/views/shared/_filter_search.html.erb

This existed on locations, modify this to be general enough to be used
in more than one place.

Allow filtering by organisation for super admins

---

app/views/admin/organisations/index.html.erb
app/views/ips/index.html.erb
app/views/shared/_filter_search.html.erb

This prints an x icon in the input and when users click it, it resets
the search.

Allow users to clear search terms

---

README.md

This gives an overview of the steps that a deployment takes, as well as
details as to when Staging and Production are deployed

add process for deployment

---

app/views/users/sessions/new.html.erb

Update copy on `/users/sign_in`

Update copy on sign in page

---

app/views/layouts/application.html.erb
config/site.yml

Allow setting the page title and seo meta description or fall back to
defaults.

 Page title & seo descriptions

---

app/views/users/sessions/new.html.erb

Add meta data to sign in page

---

db/migrate/20190507110722_create_users_organisations_join_table.rb
db/migrate/20190507122113_add_indexes_to_users_organisations.rb
db/schema.rb

We're in the process of allowing a user to belong to more than 1
organisation.  This prepares the database before modifying the
relationship in ActiveRecord.

Create users => organisations join table

---

app/controllers/admin/organisations_controller.rb
spec/requests/admin/organisations/get_spec.rb

Notify expected the CSV file in a specific format in order to bulk add email addresses, this PR reflects this.

Reformat service email CSV file

---

app/controllers/users/invitations_controller.rb
app/mailers/authentication_mailer.rb
lib/use_cases/administrator/send_cross_organisation_invite_email.rb
spec/features/confirm_cross_organisation_invitation_spec.rb
spec/features/invite_user_to_join_organisation_spec.rb
spec/support/cross_organisation_invite_use_case.rb
spec/support/cross_organisation_invite_use_case_spy.rb
spec/use_cases/administrator/send_cross_organisation_invite_email_spec.rb

The message to join an organisation will be different to creating an account.

Cross Organisation Invite mailer

---

app/controllers/admin/locations_controller.rb
app/views/admin/locations/index.html.erb
app/views/admin/organisations/index.html.erb
app/views/application/_subnavigation.html.erb
config/routes.rb
spec/features/super_admin/search_locations_spec.rb

This PR involves adding a searchable table of all the locations using GovWifi. This allows super admins to dynamically search through the table to find a desired location, the searching works either by location name or via postcode
Searching via postcode:

View and search locations

---

app/controllers/users/cross_organisation_confirmations_controller.rb
app/controllers/users/invitations_controller.rb
app/controllers/users/memberships_controller.rb
app/mailers/authentication_mailer.rb
app/models/cross_organisation_invitation.rb
app/models/organisation.rb
app/models/user.rb
config/routes.rb
db/migrate/20190517150554_rename_create_cross_organisation_invitations_to_memberships.rb
db/migrate/20190517152315_remove_null_false_constraint_from_invitation_token_on_memberships.rb
db/migrate/20190517161342_remove_organisations_users.rb
db/schema.rb
spec/factories/cross_organisation_invitation.rb
spec/factories/memberships.rb
spec/features/confirm_cross_organisation_invitation_spec.rb
spec/features/invite_user_to_join_organisation_spec.rb
spec/models/cross_organisation_invitation_spec.rb
spec/models/organisation_spec.rb
spec/models/user_spec.rb

Reverts alphagov/govwifi-admin#731

Revert "Simplify user to organisation association"

---

db/migrate/20190520161325_create_memberships.rb
db/schema.rb

In order to create one table for  users <=> organisations. I need to first create a new memberships table as we need to incrementally deploy these changes to production.

Memberships Table

---

db/migrate/20190521092119_add_confirmed_at_col.rb
db/schema.rb

Add confirmed at column for memberships table so we can replicate the cross_orgs_inv table

Add confirmed at column for memberships table

---

app/controllers/logs_searches_controller.rb
app/models/logs_search.rb
app/views/logs_searches/ip.html.erb
app/views/logs_searches/location.html.erb
app/views/logs_searches/username.html.erb
spec/features/logging/view_auth_requests_for_a_location_spec.rb
spec/models/logs_search_spec.rb

Part of https://trello.com/c/oCYLBJ0y/9-reduce-sentry-errors-to-zero
Spotted there might be validation problems from [a production Sentry error](https://sentry.io/organizations/government-digital-services/issues/855105327/?environment=production&project=1259357&query=is%3Aunresolved)
The fix involved a bit of a refactor to use Rails validation helpers.

Refactor LogsSearch validation

---

mysql_user/Dockerfile

This should be 8.0 to be consistent with infrastructure.

Amend mysql version for the user db

---

spec/features/super_admin/lookup_wifi_user_contact_details_spec.rb
spec/rails_helper.rb

DatabaseCleaner will only clean the default database by default, so expose it to our other databases

setup DatabaseCleaner to properly clean all our databases

---

app/views/help/new.html.erb
spec/features/contact_us_when_not_signed_in_spec.rb
spec/features/registration/sign_up_as_an_organisation_spec.rb

Rebuild of https://github.com/alphagov/govwifi-admin/pull/805, I've appended a commit to make features pass.

Vgphb19 patch 3 - Provide network admins with clearer support options

---

app/assets/stylesheets/components/buttons_and_links.scss
app/controllers/memberships_controller.rb
app/views/memberships/edit.html.erb
app/views/super_admin/organisations/_team.html.erb
spec/features/super_admin/remove_user_from_organisation_spec.rb
spec/models/organisation_spec.rb
spec/requests/memberships/delete_spec.rb

https://trello.com/c/3yPlxHcR/43-allow-superadmins-to-remove-team-members

Allow super admins to destroy team memberships

---

app/views/help/admin_account.erb
app/views/help/signed_in.html.erb
app/views/help/technical_support.html.erb

https://trello.com/c/UvhS5cqr/166-update-user-support-details

Update user support text

---

db/schema.rb

No functional changes, but the generators now seem to produce different output from what's currently in master, so let's update it.

BAU: Update the automatically generated schema

---

app/assets/javascripts/password_validation.js
app/assets/stylesheets/components/team_members.scss
config/initializers/devise.rb

We used to require a password score of `4`, which was very high and not really necessary. This is because we already have account locking, password hashing and 2FA in place. With these measures, it's unrealistic for someone with reasonable skills to be able to hack passwords with scores of even `2` and above easily.
The [zxcvbn's](https://github.com/dropbox/zxcvbn) docs provide a rough estimation on how easy it is to guess passwords with various scores. This PR is an attempt to lower the required score while erring on the side of caution (by opting for a score of `2` instead of `1`), because some passwords with a score of `1` were found to be quite short, and passwords with scores of `2` were found to be reasonably complex but not onerous.
---
**Easy word (score: `0`):**
**Common password …

Relax the password strength requirement to a more sensible level

---

app/controllers/application_controller.rb
app/controllers/users/two_factor_authentication/setup_controller.rb
app/models/user.rb
db/migrate/20200624102836_add_second_factor_method_to_users.rb
db/schema.rb
spec/features/authentication/logging_in_after_signing_up_spec.rb
spec/features/authentication/logging_in_after_signing_up_with_enhanced_2fa_spec.rb
spec/features/authentication/set_up_enhanced_two_factor_authentication_spec.rb
spec/features/registration/sign_up_as_an_organisation_spec.rb
spec/features/registration/sign_up_as_an_organisation_with_enhanced_2fa_spec.rb
spec/features/support/sign_up_helpers.rb
spec/requests/users/two_factor_authentication/setup/update_spec.rb

Store the chosen 2FA method in the user model, and present the chosen 2FA screen when the user logs in again.

Feature: Save chosen 2FA method

---

config/environments/staging.rb

We want to preview the new 2FA functionality on staging.

Enable enhanced 2fa for the staging environment

---

config/environments/development.rb
config/environments/staging.rb

We will remove the enhanced 2fa code. In preparation the
feature flags will be turned off for all environments

Turn off enhanced 2fa

---

lib/gateways/govuk_organisations_register_gateway.rb

Client requested that their organisation name be updated.

Update Organisation Name

---

app/views/locations/add_ips.html.erb

* Update copy
* Add labels outside inputs.
DAC report requirements. Needs visible per field labels.
Link to Trello card (if applicable): https://trello.com/c/jdlWp9Ja

Restructure add IP page with new copy, and accessible labels.

---

app/views/logs_searches/new.html.erb

`</div>` and `</fieldset>` tags were the wrong way around
so we have valid HTML

Fixed: </div> and </fieldset> tags were the wrong way around

---

app/views/super_admin/organisations/_team.html.erb

Fix the `.erb` string interpolation
Because it's wrong

Use correct `.erb` string interpolation

---

db/schema.rb

Add the recent migration to the schema
Because it is missing in previous PR

Add schema update after migration

---

config/initializers/sentry.rb

Disable tracing
It's too expensive

disable tracing

---

.scss-lint.yml
Makefile
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/buttons_and_links.scss
app/assets/stylesheets/components/ip_address.scss
app/assets/stylesheets/components/key.scss
app/assets/stylesheets/components/label_inside_input.scss
app/assets/stylesheets/components/left_nav.scss
app/assets/stylesheets/components/sub_nav.scss
app/assets/stylesheets/components/team_members.scss
package.json
yarn.lock

Implement stylelint for linting `scss`
We don't currently lint `scss` and should.
Link to Trello card (if applicable): https://trello.com/c/BFKII4Iv

Use stylelint for scss

---

app/views/super_admin/organisations/index.html.erb

Small change to text in Admin Portal to test that secondary staging pipeline is working correctly.
We need to ensure that the new Secondary Staging pipeline can deploy code to production. We will revert this change when the test is complete.
Link to Trello card (if applicable): https://trello.com/c/r6dKgFUR/1542-story-integrate-existing-main-concourse-pipeline-with-secondary-staging-so-it-will-push-to-secondary-staging

Change To Test Secondary Staging Pipeline

---

app/views/super_admin/organisations/index.html.erb

Reverts alphagov/govwifi-admin#1421

Revert "Change To Test Secondary Staging Pipeline"

---

config/environments/staging.rb

Staging has been reverted from staging-temp to staging

Revert "Update default staging url"

---

package.json
yarn.lock

Bump `govwifi-shared-frontend` to the latest release version.
A new version of the repo was released today, this will ensure we're using the newest version.

Bump `govwifi-shared-frontend`

---

app/views/logs/index.html.erb
config/initializers/time_formats.rb
spec/features/logging/view_auth_requests_for_a_username_spec.rb
spec/features/logging/view_auth_requests_for_an_ip_spec.rb
spec/features/logging/view_logs_spec.rb
spec/features/super_admin/logging/view_logs_for_ip_spec.rb
spec/features/super_admin/logging/view_logs_for_username_spec.rb

Several improvements to the logs page.
To try and make it easier to use.

Logs page improvements

---

app/models/log_search_form.rb
app/views/logs/_no_logs_explanation.html.erb
app/views/logs/index.html.erb
spec/features/logging/view_auth_requests_for_a_username_spec.rb
spec/features/logging/view_auth_requests_for_an_ip_spec.rb
spec/features/super_admin/logging/view_logs_for_ip_spec.rb
spec/features/super_admin/logging/view_logs_for_username_spec.rb
spec/features/super_admin/lookup_wifi_user_contact_details_spec.rb

Review and improve error messages from logs
If we don't show something in the logs, it should be immediately clear to admins why something is not being shown
https://technologyprogramme.atlassian.net/browse/GW-287
Screenshots are available in the Jira Card with detailed description of change

review and improve error messages from logs

---

README.md

Trigger AWS pipeline
Test deployment
Link to Trello card (if applicable):

Test triggering our pipeline

---

buildspec.yml

Create production and staging ECR Images as part of one Codebuild project.
This is a necessary work around for the limitations of Codebuild.

Create production and staging ECR Images as part of one codebuild project.

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/docker-compose.vscdev.yml
.vscode/launch.json
.vscode/rdbg_autoattach.json
Makefile

Added folder and files for vscode related container setup
Enable simple vscode setup and configuration. 
Compose individual services in a way which supports vscode debugging.
Zero impact intended - should only affect vscode development.

Vs code dev container setup

---

Gemfile
app/models/organisation.rb
app/views/super_admin/organisations/index.html.erb

The Organisation list code was inefficient and should be optimised.
Makes the code clearer and reduces the number of queries performed
Link to JIRA / Trello card (if applicable): 
https://technologyprogramme.atlassian.net/jira/software/projects/GW/boards/251?selectedIssue=GW-965

Update organisation list

---

app/controllers/locations_controller.rb
app/models/location_ips_form.rb
config/gov_notify.yml
db/migrate/20230619152929_add_sent_first_ip_survey_to_users.rb
db/migrate/20230619161245_initialise_sent_first_ip_survey.rb
db/schema.rb
lib/use_cases/first_ip_added_survey_sender.rb
spec/factories/users.rb
spec/features/ips/first_ip_survey_spec.rb

When a newly created admin adds a new IP address to an
organisations, send a survey to the admin
We wish to know what new admins think of the process of creating a new site
Link to JIRA / Trello card (if applicable): 
https://technologyprogramme.atlassian.net/jira/software/projects/GW/boards/251?selectedIssue=GW-944

Send survey to new admins that add their first IP address

---

Dockerfile
Makefile
start.sh

Ensure migrations are run before rails starts
They didn't run before, which can cause issues when merging new Pull requests

Ensure migrations are run before rails starts

---

.devcontainer/devcontainer.json
.devcontainer/docker-compose.vscdev.yml
.erb-lint.yml
.github/dependabot.yml
.github/pull_request_template.md
.rubocop.yml
.vscode/launch.json
Makefile
README.md
app/.prettierignore
app/.prettierrc.js
app/assets/stylesheets/components/ip_address.scss
app/assets/stylesheets/components/key.scss
app/assets/stylesheets/components/label_inside_input.scss
app/assets/stylesheets/components/sub_nav.scss
config/gov_notify.yml
config/locales/devise.en.yml
config/locales/en.yml
config/site.yml
config/storage.yml
docker-compose.development.yml
docker-compose.yml
package.json
yarn.lock

Add the Prettier package into the system
So that the style formatting which is no longer done by stylelint is now handled by prettier. 
Link to JIRA / Trello card (if applicable): 
https://technologyprogramme.atlassian.net/browse/GW-996

Install and run prettier linting

---

Makefile
docker-compose-no2fa.yml

This allows a developer to start the server without having to worry about using 2FA to test a feature

Add a 'serve-no2fa' option to the Makefile

---

app/views/super_admin/current_organisation/edit.html.erb

So that it is easier to find the organisation you are looking for

Order organisations by name in assume membership screen

---

app/mailers/authentication_mailer.rb
lib/gateways/sms_gateway.rb
spec/gateways/email_gateway_spec.rb
spec/gateways/sms_gateway_spec.rb

Sentry error due to wrong parameters
Corrected parameters and added more test
[GW-xxxx](https://technologyprogramme.atlassian.net/browse/GW-xxxx)
https://technologyprogramme.atlassian.net/browse/GW-1778

fix parameters

---

Dockerfile
config/database.yml

This should be changed depending on the deploy environment the server is run in and not be hard coded

Use environment variable for database name

---

app/controllers/super_admin/wifi_user_searches_controller.rb
app/mailers/gov_wifi_mailer.rb

Fix arguments for notify templates

Fix arguments for notify templates

---

app/mailers/gov_wifi_mailer.rb
spec/features/ips/first_ip_survey_spec.rb

update notify email parameters

update notify email parameters

---

app/views/certificates/index.html.erb

Describe the change
Update certificates homepage text.
[GW-1868](https://technologyprogramme.atlassian.net/browse/GW-1868)
[GW-1868]: https://technologyprogramme.atlassian.net/browse/GW-1868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update certificates text

---

app/controllers/users/two_factor_authentication_setup_controller.rb
spec/features/authentication/set_up_two_factor_authentication_spec.rb

If you input an incorrect auth code. The following message appears: 
There is a problem
The 6 digit code entered is not valid. <br/> Check the code sent in the email or request a new email.
The code is visible.
[GW-1893](https://technologyprogramme.atlassian.net/browse/GW-1893
Code previously: 
Amended:
[GW-1893]: https://technologyprogramme.atlassian.net/browse/GW-1893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GW-1893 Remove visible code

---

.erb-lint.yml
.gitignore
app/assets/config/manifest.js
app/assets/javascripts/application.js.erb
app/assets/stylesheets/application.scss
app/assets/stylesheets/application_ie8.scss
app/views/layouts/application.html.erb
app/views/logs/index.html.erb
config/initializers/assets.rb
package.json
yarn.lock

Upgrade to Govuk-frontend version 5.4.0 and deprecate IE8

Upgrade to Govuk-frontend version 5.4.0

---

app/views/settings/_account.html.erb
app/views/settings/_organisation.html.erb
app/views/settings/_servers.html.erb

Accessibility Audit 
Table captions were not unique and sufficiently descriptive.
[GW-1912](https://technologyprogramme.atlassian.net/browse/GW-1912)
[GW-1912]: https://technologyprogramme.atlassian.net/browse/GW-1912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Table names amended

---

app/controllers/super_admin/locations_controller.rb
app/models/location.rb
app/views/super_admin/locations/edit.html.erb
app/views/super_admin/organisations/_locations.html.erb
config/locales/en.yml
config/routes.rb
spec/features/super_admin/locations/set_radius_secret_key_spec.rb
spec/use_cases/radius/publish_radius_ip_allowlist_spec.rb

Add a superuser option to update a secret radius key
We sometimes need to set the same freeradius secret keys for multiple locations.
https://technologyprogramme.atlassian.net/jira/software/projects/GW/boards/251

set secret key

---

app/views/current_organisation/edit.html.erb
app/views/locations/add_ips.html.erb
app/views/locations/bulk_upload.html.erb
app/views/shared/sidebar/_default.html.erb
app/views/super_admin/current_organisation/edit.html.erb

Pages did not have titles that sufficiently described its topic or purpose.
On the 'Upload multiple locations and IPs' page, there is a non-descriptive page title that
fails to uniquely describe the topic or purpose of the page
[GW-1909](https://technologyprogramme.atlassian.net/browse/GW-1909)
[GW-1909]: https://technologyprogramme.atlassian.net/browse/GW-1909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update non-descriptive page title

---

app/controllers/help_controller.rb

We have had a few Zendesk tickets informing us that Zendesk sometimes does not accept a support ticket sent from the Admin Portal
We need to figure out why and how often this happens so we can do something about it
https://technologyprogramme.atlassian.net/browse/GW-2075

Log Zendesk errors in Sentry

---

app/models/upload_form.rb

Errors on trying to use the bulk location upload form.
We need to fix errors reported by users
[GW-2076](https://technologyprogramme.atlassian.net/browse/GW-2076)

Update upload form

---

app/helpers/certificates_helper.rb
app/views/certificates/index.html.erb

Use govuk components gem for certificates index
Using the gem makes writing design system compatible frontend code easier
https://technologyprogramme.atlassian.net/browse/GW-2243

Use govuk components gem for certificates index

---

app/helpers/application_helper.rb
app/views/ips/_confirm_remove_ip.html.erb
app/views/settings/_servers.html.erb
app/views/shared/_ip_address.html.erb

Change the ip address from a partial to a helper

Change the ip address from a partial to a helper

---

app/controllers/logs_controller.rb
app/views/logs/index.html.erb

Use govuk components gem for logs index
Using the gem makes writing design system compatible frontend code easier
https://technologyprogramme.atlassian.net/browse/GW-2246

Use govuk components gem for logs index

---

lib/gateways/new_organisations.rb
lib/tasks/opensearch.rake
lib/use_cases/new_organisations.rb
spec/gateways/new_organisations_spec.rb
spec/use_cases/new_organisations_spec.rb

Add data for new organisations
Automate GovWifi monthly reports
[[GW-xxxx](https://technologyprogramme.atlassian.net/browse/GW-xxxx)](https://technologyprogramme.atlassian.net/browse/GW-2249)

Add new organisations data

---

app/views/application/error.html.erb
app/views/certificates/_confirm_remove_certificate.html.erb
app/views/certificates/edit.html.erb
app/views/certificates/index.html.erb
app/views/certificates/new.html.erb
app/views/certificates/show.html.erb

This allows for simpler, more compliant UI code
https://technologyprogramme.atlassian.net/browse/GW-2275

Use govuk component gem for certificate views

---

package.json

Update the shared frontend library
To keep it up to date with dependabot changes.
Tested and working on Alpaca.
[GW-2294](https://technologyprogramme.atlassian.net/browse/GW-2294)

chore: [GW-2294] Update shared package
